Repository ppy/osu-framework, pull requests merged in 2018-07, with the labels that each got.

#1658 Make mouse wheel bind actions know amount of scroll
  osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
  osu.Framework/Input/Bindings/IScrollBindingHandler.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
Labels: input

#1686 Delay first setActive call until event handlers are set up
  osu.Framework/Platform/GameHost.cs
Labels: resolves issue

#1694 Mark dependency-injected methods as implicitly-used
  osu.Framework/Allocation/BackgroundDependencyLoader.cs
Labels: code quality

#1695 Corrected minor typo in documentation
  osu.Framework/Graphics/Colour/ColourInfo.cs
Labels: documentation

#1698 Fix flashing in test case
  osu.Framework.Tests/Visual/TestCaseInputManager.cs
Labels: bug, testing

#1699 Fix joystick button handling being completely incorrect
  osu.Framework/Input/InputManager.cs
Labels: input, regression

#1696 Propagate min/max bindable value changes
  osu.Framework.Tests/Bindables/BindableBindingTest.cs
  osu.Framework/Configuration/BindableNumber.cs
Labels: bindable

#1680 Output debug logs for framework consumers based on executing assembly's release type
  osu.Framework/Development/DebugUtils.cs
  osu.Framework/Logging/Logger.cs
Labels: logging

#1681 Populate Logger's version with assembly version information by default
  osu.Framework/Logging/Logger.cs
  osu.Framework/Platform/GameHost.cs
Labels: logging

#1693 Remove net471 targeting
  README.md
  SampleGame/SampleGame.csproj
  appveyor.yml
  osu-framework.sln
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/Platform/GameHost.cs
  osu.Framework/RuntimeInfo.cs
Labels: code quality

#1700 Remove duplicate OpenGL initialisation
  osu.Framework/Platform/GameWindow.cs
Labels: code quality

#1682 Make PassThroughInputManager sync with parent input state
  osu.Framework.Tests/Visual/TestCaseInputManager.cs
  osu.Framework.Tests/Visual/TestCasePassThroughInputManager.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/ButtonInput.cs
  osu.Framework/Input/ButtonStates.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/JoystickButtonInput.cs
  osu.Framework/Input/KeyboardKeyInput.cs
  osu.Framework/Input/MouseButtonInput.cs
  osu.Framework/Input/PassThroughInputManager.cs
Labels: resolves issue

#1701 Fix incorrect intersection logic
  osu.Framework/Input/MouseButtonEventManager.cs
Labels: bug, input

#1685 Don't inject local dependencies on self
  osu.Framework/Game.cs
  osu.Framework/Graphics/Drawable.cs
Labels: dependency-injection, proposal

#1707 Fix draw visualiser title bar ignoring drags in some cases
  osu.Framework/Graphics/Visualisation/TitleBar.cs
  osu.Framework/Graphics/Visualisation/TreeContainer.cs
  osu.Framework/Graphics/Visualisation/TreeContainerStatus.cs
Labels: ux

#1706 Fix focus overlay focus
  osu.Framework.Tests/Visual/TestCaseFocus.cs
  osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
  osu.Framework/Input/InputManager.cs
Labels: drawable, input

#1708 Fix empty tooltips being shown incorrectly
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
Labels: resolves issue

#1704 Turn cache back on for chocolatey packages
  appveyor.yml
Labels: tooling

#1712 Fix multiple issues surrounding textbox per-character fades
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: resolves issue, user interface

#1722 Fixes font precache freezing
  osu.Framework/IO/Stores/GlyphStore.cs
Labels: bug

#1720 Use Enum.HasFlag
  osu.Framework.Tests/Visual/TestCaseIsMaskedAway.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/ContainerExtensions.cs
  osu.Framework/Graphics/Containers/FillFlowContainer.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/IO/File/FileSafety.cs
  osu.Framework/Input/Handlers/Mouse/OpenTKMouseState.cs
  osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
  osu.Framework/Input/UserInputManager.cs
  osu.Framework/Platform/GameWindow.cs
  osu.Framework/Platform/MacOS/MacOSGameWindow.cs
Labels: code quality

#1718 Fix cursors not getting positional updates during fade out transforms
  osu.Framework/Graphics/Cursor/CursorContainer.cs
Labels: drawable

#1723 Adjust several comments pertaining to drawable load states
  osu.Framework/Graphics/Drawable.cs
Labels: documentation, drawable

#1725 Add TryGet<T>() extension to dependency containers
  osu.Framework/Allocation/DependencyContainer.cs
  osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
Labels: dependency-injection

#1716 Allow frame statistics to expand without pausing
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Labels: tooling

#1613 Container component to dynamically replace an async loaded Drawable
  osu.Framework.Tests/Visual/TestCaseModelBackedDrawable.cs
  osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
  osu.Framework/Lists/ComparisonComparer.cs
  osu.Framework/Lists/FuncEqualityComparer.cs
  osu.Framework/Lists/SortedList.cs
Labels: drawable, overdue, pending review, user interface

#1715 Fix joystick input not working when first disabled then enabled
  osu.Framework.Tests/Visual/TestCaseJoystick.cs
  osu.Framework/Input/Bindings/InputKey.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
  osu.Framework/Input/Handlers/Joystick/OpenTKJoystickHandler.cs
  osu.Framework/Input/Handlers/Keyboard/OpenTKKeyboardHandler.cs
  osu.Framework/Input/Handlers/Mouse/OpenTKMouseHandler.cs
  osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
  osu.Framework/Input/InputManager.cs
Labels: input

#1687 Use NATIVE_DLL_SEARCH_DIRECTORIES to find libraries
  osu.Framework/Platform/Linux/Native/Library.cs
Labels: linux

#1731 Fix VisualisedDrawable not correctly considering CompositeDrawables
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
Labels: high priority, tooling

#1362 Add support for PageUp/PageDown/Home/End in ScrollContainers
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: input, overdue, overdue x2, pending review, user interface

#1727 Rewrite dependency injection to support injection/caching via class attributes
  osu.Framework.Tests/Dependencies/CachedAttributeTest.cs
  osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
  osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
  osu.Framework.Tests/Visual/TestCaseInputManager.cs
  osu.Framework/Allocation/BackgroundDependencyLoader.cs
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
  osu.Framework/Allocation/CachedAttribute.cs
  osu.Framework/Allocation/DependencyActivator.cs
  osu.Framework/Allocation/DependencyContainer.cs
  osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
  osu.Framework/Allocation/ResolvedAttribute.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/PlatformActionContainer.cs
  osu.Framework/Screens/Screen.cs
  osu.Framework/Testing/TestBrowserTestRunner.cs
  osu.Framework/Testing/TestCaseTestRunner.cs
Labels: resolves issue

#1735 Fix autosizing gridcontainer cells not resizing
  osu.Framework.Tests/Visual/TestCaseGridContainer.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
Labels: bug, drawable

#1748 Use .NET Core CodeFileSanity
  appveyor.yml
Labels: tooling

#1688 Add multi-monitor support for custom fullscreen resolutions
  osu.Framework.Tests/Visual/TestCaseFullscreen.cs
  osu.Framework/Platform/DesktopGameWindow.cs
  osu.Framework/osu.Framework.csproj
Labels: display

#1749 Improve DI exception output
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
  osu.Framework/Allocation/DependencyActivator.cs
  osu.Framework/Allocation/RecursiveLoadException.cs
  osu.Framework/Extensions/ExceptionExtensions/ExceptionExtensions.cs
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/Platform/GameHost.cs
Labels: blocked, dependency-injection

#1652 Select fullscreen resolution with max available refresh rate
  osu.Framework/Platform/DesktopGameWindow.cs
Labels: display, resolves issue
