Repository ppy/osu-framework, pull requests merged in 2018-02, with the labels that each got.

#1388 Debounce config saves
  osu.Framework/Configuration/ConfigManager.cs
Labels: resolves issue

#1389 Combine drag and click lenience into a single variable
  osu.Framework/Input/InputManager.cs
Labels: input

#1390 Fix regression in frame statistics display thread names
  osu.Framework/Development/ThreadSafety.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Threading/AudioThread.cs
  osu.Framework/Threading/DrawThread.cs
  osu.Framework/Threading/GameThread.cs
  osu.Framework/Threading/InputThread.cs
  osu.Framework/Threading/UpdateThread.cs
Labels: bug, regression

#1383 Make Path receive input only on the path bounds
  osu.Framework.Tests/Visual/TestCasePathInput.cs
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/Graphics/Lines/Path.cs
Labels: drawable, input

#1394 Various improvements to textbox input
  osu.Framework.Tests/Visual/TestCaseTextBox.cs
  osu.Framework/Graphics/Containers/TabbableContainer.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Input/PlatformActionContainer.cs
Labels: user interface

#1396 Fix backspace not working in some textboxes
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: regression, user interface

#1404 Revert retry test case changes
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework/IO/Network/WebRequest.cs
Labels: testing

#1406 Remove WebRequest workaround for mono bug which has since been resolved
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework/IO/Network/WebRequest.cs
Labels: code quality

#1407 Fix Bindable's GetBoundCopy using MemberwiseClone
  osu.Framework/Configuration/Bindable.cs
Labels: bug

#1405 Allow resource managers to accept and return null
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/Sample/SampleManager.cs
  osu.Framework/Audio/Track/TrackManager.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
Labels: code quality

#1410 Add a LoadAsyncComplete method
  osu.Framework/Graphics/Drawable.cs
Labels: drawable

#1412 Don't track all used objects
  osu.Framework/Allocation/ObjectStack.cs
Labels: performance

#1419 Add logging when threads fail to join in time
  osu.Framework/Platform/GameHost.cs
Labels: testing

#1415 Fix VisualTests crashing on first startup due to incorrect configuration
  osu.Framework/Testing/TestBrowserConfig.cs
Labels: high priority, testing

#1411 Reduce dependence on zero-duration transforms
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: drawable, performance

#1413 Fix transforms on RemoveCompletedTransforms drawables applying forever
  osu.Framework/Graphics/Transforms/Transform.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
Labels: performance, regression

#1421 Use same argument order in all transformable conditionals
  osu.Framework/Graphics/Transforms/Transformable.cs
Labels: code quality

#1427 Fix transforms of same type/time not being removed correctly
  osu.Framework/Graphics/Transforms/Transform.cs
Labels: bug, drawable, high priority

#1422 Catch exceptions thrown during dynamic compilation runtime
  osu.Framework/Testing/DynamicClassCompiler.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: resolves issue

#1424 Ensure bindings unbind in both directions when explicit UnbindBindings is called
  osu.Framework/Configuration/Bindable.cs
Labels: bug, code quality, pending review

#1408 Always confine cursor when left mouse button is pressed
  osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
Labels: resolves issue
