Repository ppy/osu-framework, pull requests merged in 2018-05, with the labels that each got.

#1537 Use pattern matching
  osu.Framework/Configuration/ConfigManager.cs
  osu.Framework/Extensions/ExceptionExtensions/ExceptionExtensions.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/TabbableContainer.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/Visualisation/InfoOverlay.cs
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
  osu.Framework/IO/Stores/CachedResourceStore.cs
  osu.Framework/IO/Stores/FontStore.cs
  osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
  osu.Framework/Input/InputManager.cs
Labels: code quality

#1541 Update CodeFileSanity
  appveyor.yml
Labels: testing

#1493 Add an option to exact-match keybindings
  osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
  osu.Framework/Input/PlatformActionContainer.cs
Labels: resolves issue

#1539 Add a way to transform bindables
  osu.Framework/Graphics/TransformSequenceExtensions.cs
  osu.Framework/Graphics/TransformableExtensions.cs
  osu.Framework/Graphics/Transforms/TransformBindable.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/MathUtils/Interpolation.cs
Labels: code quality, transformations

#1545 Change order of lines to properly raise events
  osu.Framework.Tests/Bindables/BindableBindingTest.cs
  osu.Framework/Configuration/Bindable.cs
Labels: code quality, testing

#1547 Commit missed change from #1545
  osu.Framework/Configuration/Bindable.cs
Labels: code quality

#1548 Fix SpriteText size not being computer when set to empty
  osu.Framework.Tests/Visual/TestCaseSpriteTextPresence.cs
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: bug, drawable

#1538 Add CircularProgress.FillTo method
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
Labels: transformations

#1549 Fix wrong signature on FillTo
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
Labels: code quality, transformations

#1546 Clean up BufferedContainer and fix alignment issues
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
Labels: drawable

#1542 Make children life update in BDL-load
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: bug, performance

#1551 Clear all trace listeners to avoid MessageBox popups on windows
  osu.Framework/Platform/GameHost.cs
Labels: testing

#1550 Fix textbox not always blocking all handled key presses
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: input, resolves issue

#1494 Implement joystick input
  osu.Framework.Tests/Visual/TestCaseJoystick.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Input/Bindings/InputKey.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
  osu.Framework/Input/Handlers/Joystick/OpenTKJoystickHandler.cs
  osu.Framework/Input/IJoystickState.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/InputState.cs
  osu.Framework/Input/JoystickAxis.cs
  osu.Framework/Input/JoystickButton.cs
  osu.Framework/Input/JoystickEventArgs.cs
  osu.Framework/Input/JoystickState.cs
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Statistics/FrameStatistics.cs
  osu.Framework/Threading/InputThread.cs
Labels: input

#1554 Fix autosize invalidations occurring with BypassAutoSIzeAxes
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
Labels: performance

#1555 Move custom AppearDelay into its own interface
  osu.Framework.Tests/Visual/TestCaseTooltip.cs
  osu.Framework/Graphics/Cursor/IHasAppearDelay.cs
  osu.Framework/Graphics/Cursor/IHasTooltip.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
Labels: code quality

#1556 Expose scroll wheel and key methods from ManualInputManager
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: testing

#1558 Added padding to the checkbox for running all steps.
  osu.Framework/Testing/TestBrowser.cs
Labels: testing, user interface

#1560 Add ability to ButtonDown and ButtonUp in ManualInputManager
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: testing

#1561 Add a way to override the ScrollContainer's scroll bar
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: user interface

#1564 Explicitly dispose previous TestCase when switching to a new one
  osu.Framework/Testing/TestBrowser.cs
Labels: testing

#1563 Make IBindable and IBindable<T> share some common interfaces
  osu.Framework/Configuration/IBindable.cs
  osu.Framework/Configuration/ICanBeDisabled.cs
  osu.Framework/Configuration/IHasDefaultValue.cs
  osu.Framework/Configuration/IHasDescription.cs
  osu.Framework/Configuration/IUnbindable.cs
Labels: configuration

#1565 Fix mouse input state inconsistencies and add unit tests
  osu.Framework.Tests/Visual/TestCaseMouseStates.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Input/FrameworkActionContainer.cs
  osu.Framework/Input/Handlers/Mouse/OpenTKMouseHandler.cs
  osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs
  osu.Framework/Input/IJoystickState.cs
  osu.Framework/Input/IMouseState.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/JoystickState.cs
  osu.Framework/Input/MouseState.cs
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: code quality, input, resolves issue

#1568 Always yield the new state when creating distinct states
  osu.Framework/Input/InputManager.cs
Labels: bug, input, regression

#1566 Improvement to project files using Directory.Build.props
  Directory.Build.props
  SampleGame/SampleGame.csproj
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/osu.Framework.csproj
Labels: code quality

#1570 Fix infinite queuing of expensive operations in GLWrapper
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: resolves issue
