Repository ppy/osu-framework, pull requests merged in 2018-10, with the labels that each got.

#1947 Restore modifier key getters of KeyboardState
  osu.Framework/Input/Events/UIEvent.cs
  osu.Framework/Input/States/KeyboardState.cs
Labels: input

#1928 Don't add intermediate container nodes to input queue
  osu.Framework.Tests/Visual/TestCaseConcurrentLoad.cs
  osu.Framework.Tests/Visual/TestCaseDelayedLoad.cs
  osu.Framework.Tests/Visual/TestCaseDelayedUnload.cs
  osu.Framework.Tests/Visual/TestCaseHandleInput.cs
  osu.Framework.Tests/Visual/TestCaseMouseStates.cs
  osu.Framework.Tests/Visual/TestCaseTooltip.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/OverlayContainer.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
  osu.Framework/Graphics/Containers/VisibilityContainer.cs
  osu.Framework/Graphics/Cursor/CursorContainer.cs
  osu.Framework/Graphics/Cursor/CursorEffectContainer.cs
  osu.Framework/Graphics/Cursor/IHasTooltip.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
  osu.Framework/Input/Bindings/IKeyBindingHandler.cs
  osu.Framework/Input/MouseButtonEventManager.cs
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Screens/Screen.cs
Labels: input, performance

#1943 Fix DrawVisualiser incorrectly using ref-counted textures
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
Labels: tooling

#1942 Make DrawVisualiser better target Drawables
  osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Labels: tooling

#1950 Implement SmoothPath which provides antialiasing capabilities
  osu.Framework.Tests/Visual/TestCaseDrawablePath.cs
  osu.Framework.Tests/Visual/TestCaseInputResampler.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/Lines/SmoothPath.cs
  osu.Framework/Graphics/Lines/TexturedPath.cs
Labels: drawable, pending review

#1959 Compile with Jetbrains annotations present
  osu-framework.sln.DotSettings
  osu.Framework/osu.Framework.csproj
Labels: code quality

#1913 Implement test case for borderless fullscreen on desktop platforms
  osu.Framework.Tests/Visual/TestCaseBorderless.cs
Labels: pending review

#1961 Prefer native MacOS code over SDL on OSX
  osu-framework.sln.DotSettings
  osu.Framework/Host.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
Labels: compatibility
