Repository ppy/osu-framework, pull requests merged in 2018-09, with the labels that each got.

#1838 Don't block all invalidation when parent is null
  osu.Framework/Graphics/Drawable.cs
Labels: drawable, regression

#1837 Don't recompute spritetext layout on colour invalidation
  osu.Framework.Tests/Visual/TestCaseEffects.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: drawable, performance

#1840 Reduce memory retention by MouseButtonEventManager
  osu.Framework/Input/MouseButtonEventManager.cs
Labels: input, memory

#1846 Reduce drawable finalizer overhead in SpriteText
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: performance

#1844 Have atlases return GL textures, not Textures
  osu.Framework/Game.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Textures/Texture.cs
  osu.Framework/Graphics/Textures/TextureAtlas.cs
  osu.Framework/Graphics/Textures/TextureLoader.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/IO/Stores/FontStore.cs
Labels: graphics, performance

#1852 Fix TestCaseSizing being empty by default
  osu.Framework.Tests/Visual/TestCaseSizing.cs
Labels: testing

#1854 Use Lazy<T> in every case we can
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
Labels: performance

#1850 Remove some remaining code from async endeavour
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Platform/GameHost.cs
Labels: code quality

#1861 Rewrite SpriteText to use DrawNodes + baked flow logic
  osu.Framework.Tests/Visual/TestCaseSpriteText.cs
  osu.Framework.Tests/Visual/TestCaseSpriteTextScenarios.cs
  osu.Framework/Graphics/Containers/IFillFlowContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRateSection.cs
Labels: drawable, performance

#1843 Add texture reference counting
  osu.Framework.Tests/Visual/TestCaseAnimation.cs
  osu.Framework.Tests/Visual/TestCaseRefCountTexture.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/Lines/PathDrawNode.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/Sprites/Sprite.cs
  osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
  osu.Framework/Graphics/Textures/LargeTextureStore.cs
  osu.Framework/Graphics/Textures/Texture.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/Graphics/Textures/TextureWhitePixel.cs
  osu.Framework/Graphics/Textures/TextureWithRefCount.cs
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
  osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
Labels: graphics, performance

#1847 Further changes to avoid reference retention
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/InputManager.cs
Labels: memory

#1859 Fix potential race condition causing collection modified exceptions
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioComponent.cs
Labels: audio, bug

#1848 Make TimedExpiryCache dispose eagerly on removal
  osu.Framework/Allocation/TimedExpiryCache.cs
Labels: performance

#1849 Dispose drawables aggressively
  osu.Framework.Tests/Visual/TestCaseProxyDrawables.cs
  osu.Framework/Graphics/Drawable.cs
Labels: drawable, memory, performance

#1864 Fix SpriteText presence changing mid-flow layout
  osu.Framework.Tests/Visual/TestCaseSpriteTextPresence.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: drawable, regression

#1863 Optimise away all allocations during font / texture lookups
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/IO/Stores/FontStore.cs
Labels: memory, performance

#1865 Fix texture sampling issue on Intel/Linux
  osu.Framework/Resources/Shaders/sh_TextureRounded.fs
Labels: graphics

#1866 Precache character textures during SpriteText's BDL load
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: drawable, performance

#1867 Fix SpriteTexts with only spaces not getting a width
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: drawable, regression

#1836 Separate out colour and presence invalidations
  osu.Framework/Graphics/Audio/WaveformGraph.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
  osu.Framework/Graphics/Containers/CompositeDrawNode.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/DrawColourInfo.cs
  osu.Framework/Graphics/DrawInfo.cs
  osu.Framework/Graphics/DrawNode.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Lines/PathDrawNode.cs
  osu.Framework/Graphics/Shapes/Triangle.cs
  osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
  osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
Labels: drawable, performance

#1877 Implement a custom SortedList enumerator to reduce allocations
  osu-framework.sln.DotSettings
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Lists/SortedList.cs
Labels: performance

#1876 Reduce allocations/performance overhead of draw nodes
  osu.Framework/Allocation/ValueInvokeOnDisposal.cs
  osu.Framework/Graphics/Batches/VertexBatch.cs
  osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
  osu.Framework/Graphics/Shaders/UniformMapping.cs
Labels: performance

#1872 Fix ResourceStore thread safety
  osu-framework.sln.DotSettings
  osu.Framework/IO/Stores/NamespacedResourceStore.cs
  osu.Framework/IO/Stores/ResourceStore.cs
Labels: resolves issue

#1874 Fix window size being ignored on macOS hosts
  osu.Framework/Platform/DesktopGameWindow.cs
  osu.Framework/Platform/MacOS/MacOSGameWindow.cs
Labels: graphics, regression

#1875 Propagate presence invalidations to children
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: drawable, regression

#1882 Fix references to VBOs causing disposal to never occur
  osu.Framework/Graphics/Batches/VertexBatch.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: performance, regression

#1883 Run aggressive disposal of drawables asynchronously
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Screens/Screen.cs
Labels: performance, regression

#1885 Disable mipmap generation for LargeTextureStore
  osu.Framework/Graphics/Textures/LargeTextureStore.cs
Labels: performance

#1890 Iterate by index in CompositeDrawNode for increased performance
  osu.Framework/Graphics/Containers/CompositeDrawNode.cs
Labels: performance

#1889 Fix not being able to add space character to FixedWidthExceptions
  osu.Framework.Tests/Visual/TestCaseSpriteTextScenarios.cs
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: drawable

#1879 Fix click event log message
  osu.Framework/Input/MouseButtonEventManager.cs
Labels: regression

#1892 Fix disposal checks throwing exceptions in drawnodes
  osu.Framework.Tests/Visual/TestCaseTextures.cs
  osu.Framework/Graphics/Audio/WaveformGraph.cs
  osu.Framework/Graphics/Lines/PathDrawNode.cs
  osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
  osu.Framework/Graphics/Textures/Texture.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/Graphics/Textures/TextureWithRefCount.cs
  osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
Labels: high priority

#1894 Avoid constructing per-frame Image<T>s in FrameStatisticsDisplay
  osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Textures/BufferStackTextureUpload.cs
  osu.Framework/Graphics/Textures/ITextureUpload.cs
  osu.Framework/Graphics/Textures/Texture.cs
  osu.Framework/Graphics/Textures/TextureUpload.cs
Labels: resolves issue

#1896 Fix unit tests failing due to async load
  osu.Framework.Tests/Visual/TestCaseTextures.cs
Labels: testing

#1899 Fix potential thread race condition in TextureStore's refresh logic
  osu.Framework/Graphics/Textures/TextureStore.cs
Labels: bug, threading

#1902 Improve dotnet test run storage cleanup and naming
  osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
  osu.Framework/Testing/TestCase.cs
Labels: code quality, testing

#1904 Update OpenTK and other dependencies
  osu.Framework/osu.Framework.csproj
Labels: libraries

#1897 Reduce allocations when iterating over children of a container
  osu.Framework/Graphics/Containers/Container.cs
Labels: drawable, performance

#1895 Make Bindable{T} serializable/deserializable
  osu.Framework.Tests/Bindables/BindableSerializationTest.cs
  osu.Framework/Configuration/Bindable.cs
  osu.Framework/IO/Serialization/BindableJsonConverter.cs
  osu.Framework/IO/Serialization/ISerializableBindable.cs
  osu.Framework/IO/Serialization/ISerializableSortedList.cs
  osu.Framework/IO/Serialization/SortedListJsonConverter.cs
  osu.Framework/Lists/SortedList.cs
Labels: bindable

#1905 Fix double click behavior regression
  osu.Framework.Tests/Visual/TestCaseMouseStates.cs
  osu.Framework/Input/MouseButtonEventManager.cs
Labels: input, resolves issue

#1912 Deploy a local httpbin server for webrequest tests
  appveyor.yml
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework.Tests/Visual/TestCaseNestedMenus.cs
  osu.Framework.Tests/Visual/TestCaseTransformRewinding.cs
  osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
Labels: testing

#1713 Introduce a new way of event handling
  osu-framework.sln.DotSettings
  osu.Framework.Tests/Visual/TestCaseDropdownBox.cs
  osu.Framework.Tests/Visual/TestCaseSliderbar.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Input/Events/ClickEvent.cs
  osu.Framework/Input/Events/DoubleClickEvent.cs
  osu.Framework/Input/Events/DragEndEvent.cs
  osu.Framework/Input/Events/DragEvent.cs
  osu.Framework/Input/Events/DragStartEvent.cs
  osu.Framework/Input/Events/FocusEvent.cs
  osu.Framework/Input/Events/FocusLostEvent.cs
  osu.Framework/Input/Events/HoverEvent.cs
  osu.Framework/Input/Events/HoverLostEvent.cs
  osu.Framework/Input/Events/JoystickButtonEvent.cs
  osu.Framework/Input/Events/JoystickPressEvent.cs
  osu.Framework/Input/Events/JoystickReleaseEvent.cs
  osu.Framework/Input/Events/KeyDownEvent.cs
  osu.Framework/Input/Events/KeyUpEvent.cs
  osu.Framework/Input/Events/KeyboardEvent.cs
  osu.Framework/Input/Events/MouseButtonEvent.cs
  osu.Framework/Input/Events/MouseDownEvent.cs
  osu.Framework/Input/Events/MouseEvent.cs
  osu.Framework/Input/Events/MouseMoveEvent.cs
  osu.Framework/Input/Events/MouseUpEvent.cs
  osu.Framework/Input/Events/ScrollEvent.cs
  osu.Framework/Input/Events/UIEvent.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/LocalMouseState.cs
  osu.Framework/Input/MouseButtonEventManager.cs
  osu.Framework/Input/StateChanges/ButtonInput.cs
  osu.Framework/Input/StateChanges/Events/ButtonStateChangeEvent.cs
  osu.Framework/Input/StateChanges/Events/InputStateChangeEvent.cs
  osu.Framework/Input/StateChanges/Events/MousePositionChangeEvent.cs
  osu.Framework/Input/StateChanges/Events/MouseScrollChangeEvent.cs
  osu.Framework/Input/StateChanges/IInputStateChangeHandler.cs
  osu.Framework/Input/StateChanges/JoystickButtonInput.cs
  osu.Framework/Input/StateChanges/KeyboardKeyInput.cs
  osu.Framework/Input/StateChanges/MouseButtonInput.cs
  osu.Framework/Input/StateChanges/MousePositionAbsoluteInput.cs
  osu.Framework/Input/StateChanges/MousePositionRelativeInput.cs
  osu.Framework/Input/StateChanges/MouseScrollRelativeInput.cs
  osu.Framework/Input/UserInputManager.cs
Labels: input

#1921 Don't return any resolutions for macOS
  osu.Framework/Platform/MacOS/MacOSGameWindow.cs
Labels: macOS

#1328 Add localisation/formatting capabilities to SpriteText
  osu-framework.sln.DotSettings
  osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework.Tests/Visual/TestCaseLocalisation.cs
  osu.Framework.Tests/Visual/TestCaseSpriteTextScenarios.cs
  osu.Framework/Game.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Localisation/FormatString.cs
  osu.Framework/Localisation/ILocalisedBindableString.cs
  osu.Framework/Localisation/IUnicodeBindableString.cs
  osu.Framework/Localisation/LocalisationEngine.cs
  osu.Framework/Localisation/LocalisationManager.cs
  osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
  osu.Framework/Localisation/LocalisedFormatString.cs
  osu.Framework/Localisation/LocalisedString.cs
  osu.Framework/Localisation/UnicodeBindableString.cs
  osu.Framework/Platform/GameHost.cs
Labels: drawable, localisation, overdue x2, pending review

#1924 Fix LocalisedText not using the correct fallback
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework/Localisation/LocalisedString.cs
Labels: localisation

#1925 Retrieve all inherited members for property display
  osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
Labels: tooling

#1929 Rename Keyboard/Mouse to NonPositional/Positional
  osu.Framework.Tests/Visual/TestCaseConcurrentLoad.cs
  osu.Framework.Tests/Visual/TestCaseDelayedLoad.cs
  osu.Framework.Tests/Visual/TestCaseDelayedUnload.cs
  osu.Framework.Tests/Visual/TestCaseFocus.cs
  osu.Framework.Tests/Visual/TestCaseKeyBindings.cs
  osu.Framework.Tests/Visual/TestCasePathInput.cs
  osu.Framework.Tests/Visual/TestCaseTooltip.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/OverlayContainer.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
  osu.Framework/Graphics/Containers/VisibilityContainer.cs
  osu.Framework/Graphics/Cursor/CursorContainer.cs
  osu.Framework/Graphics/Cursor/IHasCustomTooltip.cs
  osu.Framework/Graphics/Cursor/IHasTooltip.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/MouseButtonEventManager.cs
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Screens/Screen.cs
  osu.Framework/Statistics/FrameStatistics.cs
  osu.Framework/Threading/UpdateThread.cs
Labels: code quality

#1937 Fix incorrect behavior of hollow offset edge effects
  osu.Framework.Tests/Visual/TestCaseMasking.cs
  osu.Framework/Graphics/Containers/CompositeDrawNode.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
  osu.Framework/Graphics/Shaders/GlobalProperty.cs
  osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
  osu.Framework/Resources/Shaders/sh_TextureRounded.fs
Labels: resolves issue

#1938 Fix duplicates appearing in PropertyDisplay
  osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
Labels: regression, tooling

#1939 Make GetTextureForCharacter virtual
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: drawable

#1932 Fix setting of OriginPosition/RelativeAnchorPosition not invalidating
  osu.Framework/Graphics/Drawable.cs
Labels: resolves issue
