Repository ppy/osu-framework, pull requests merged in 2018-08, with the labels that each got.

#1755 Add default constructor for BackgroundDependencyLoader
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
Labels: dependency-injection

#1705 Add a way to step through previously drawn frames inside testcases
  osu.Framework.Tests/Visual/TestCaseSliderbar.cs
  osu.Framework.Tests/Visual/TestCaseUpdateBeforeDraw.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/CircularContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Drawable_ProxyDrawable.cs
  osu.Framework/Graphics/UserInterface/BasicCheckbox.cs
  osu.Framework/Graphics/UserInterface/BasicSliderBar.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Testing/DrawFrameRecordingContainer.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarAssemblySection.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRateSection.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs
  osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
  osu.Framework/Testing/Drawables/ToolbarSection.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestCase.cs
Labels: testing

#1751 Update nuget dependencies
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/osu.Framework.csproj
Labels: libraries

#1756 Fix SliderBar binding to events too early
  osu.Framework/Graphics/UserInterface/SliderBar.cs
Labels: regression

#1758 Fix shader log output being ugly and non-useful
  osu.Framework/Graphics/Shaders/ShaderManager.cs
  osu.Framework/Platform/GameWindow.cs
Labels: logging

#1691 Use macOS fullscreen window mask instead of changing resolution
  osu.Framework.Tests/Visual/TestCaseFullscreen.cs
  osu.Framework/Platform/DesktopGameWindow.cs
  osu.Framework/Platform/MacOS/MacOSGameWindow.cs
  osu.Framework/Platform/MacOS/Native/Class.cs
  osu.Framework/Platform/MacOS/Native/Cocoa.cs
  osu.Framework/Platform/MacOS/Native/NSApplication.cs
  osu.Framework/Platform/MacOS/Native/NSNotificationCenter.cs
  osu.Framework/Platform/MacOS/Native/NSPasteboard.cs
  osu.Framework/Platform/MacOS/Native/Selector.cs
Labels: resolves issue

#1764 Apply an interim fix for a StackOverflowException
  osu.Framework.Tests/Visual/TestCaseSizing.cs
Labels: bug, testing

#1763 Disallow doubly-caching objects as dependencies
  osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
  osu.Framework/Allocation/DependencyContainer.cs
  osu.Framework/Platform/GameHost.cs
Labels: dependency-injection

#1767 Move WebRequest to using pure async logic
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework/IO/Network/WebRequest.cs
Labels: performance

#1770 Fix incorrect DI error being reported by StepButton failures
  osu.Framework/Testing/Drawables/Steps/StepButton.cs
Labels: dependency-injection

#1769 Allow framework types to cache structs as dependencies
  osu.Framework.Tests/Dependencies/CachedAttributeTest.cs
  osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
  osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
  osu.Framework/Allocation/CachedAttribute.cs
  osu.Framework/Allocation/DependencyContainer.cs
  osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
  osu.Framework/Allocation/ResolvedAttribute.cs
  osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
  osu.Framework/Testing/Dependencies/CachedNullableProvider.cs
  osu.Framework/Testing/Dependencies/CachedStructProvider.cs
Labels: dependency-injection

#1774 Fix assertions breaking rider/cli outputs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Threading/GameThread.cs
Labels: testing

#1759 Allow exceptions to be resolved from LogEntries
  osu.Framework.Tests/IO/LoggerTest.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Audio/Track/Waveform.cs
  osu.Framework/Logging/Logger.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Threading/GameThread.cs
Labels: logging

#1775 Remove nullable type when using CacheValueAs()
  osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
  osu.Framework/Allocation/DependencyContainer.cs
Labels: dependency-injection

#1776 Support for cancellation on drawables’ load
  osu.Framework.Tests/Visual/TestCaseDrawableLoadCancallation.cs
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
Labels: drawable

#1778 Fix unhandled exceptions being thrown by textbox
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: resolves issue

#1781 Fix failing screen testcase
  osu.Framework.Tests/Visual/TestCaseScreen.cs
Labels: testing

#1779 Make screenshots not use System.Drawing
  osu.Framework.Tests/Visual/TestCaseScreenshot.cs
  osu.Framework/Platform/GameHost.cs
Labels: graphics

#1791 Reduce overhead of shader lookup caused by string concatenation
  osu.Framework/Graphics/Shaders/ShaderManager.cs
Labels: performance

#1788 Reduce allocations by ConcurrentQueue when collecting perf data
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Statistics/PerformanceMonitor.cs
Labels: performance

#1782 Display frame times in addition to FPS
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Timing/FramedClock.cs
  osu.Framework/Timing/ThrottledFrameClock.cs
Labels: performance

#1787 Remove usage of linq to handle unhovering
  osu.Framework/Input/InputManager.cs
Labels: performance

#1794 Reduce cancellation token overhead
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
Labels: drawable, performance

#1785 Improve shader uniform performance
  osu-framework.sln.DotSettings
  osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
  osu.Framework/Graphics/Shaders/GlobalProperty.cs
  osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
  osu.Framework/Graphics/Shaders/GlobalUniform.cs
  osu.Framework/Graphics/Shaders/IUniform.cs
  osu.Framework/Graphics/Shaders/IUniformMapping.cs
  osu.Framework/Graphics/Shaders/IUniformWithValue.cs
  osu.Framework/Graphics/Shaders/Shader.cs
  osu.Framework/Graphics/Shaders/Uniform.cs
  osu.Framework/Graphics/Shaders/UniformBase.cs
  osu.Framework/Graphics/Shaders/UniformMapping.cs
Labels: performance

#1795 Use named threads instead of LongRunning tasks
  osu.Framework/Logging/Logger.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Statistics/BackgroundStackTraceCollector.cs
  osu.Framework/Threading/GameThread.cs
Labels: logging

#1798 Remove completely incorrect BypassAutoSize optimisation
  osu.Framework.Tests/Visual/TestCaseSizing.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: regression

#1797 Limit rate of frame time display updates to reduce overhead
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
Labels: performance, testing

#1802 Fix CollectionModifiedException occurring when refreshing joystick devices
  osu.Framework/Input/Handlers/Joystick/OpenTKJoystickHandler.cs
Labels: input

#1806 Disallow TestCases to add/remove from InternalChildren
  osu.Framework.Tests/Visual/TestCaseFillModes.cs
  osu.Framework.Tests/Visual/TestCaseFitInsideFlow.cs
  osu.Framework/Testing/TestCase.cs
Labels: testing

#1805 Add support for TestCase execution in visual tests
  osu.Framework/Testing/TestBrowser.cs
Labels: testing

#1761 Fix interrupted transform sequences not rewinding correctly
  osu.Framework.Tests/Visual/TestCaseTransformRewinding.cs
  osu.Framework/Graphics/Transforms/TransformSequence.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
  osu.Framework/Testing/TestCaseTestRunner.cs
Labels: transformations

#1809 Fix nunit not correctly catching input thread exceptions
  osu.Framework/Testing/TestCase.cs
Labels: testing

#1807 Fix non-zero AutoSizeDuration causing a potentially incorrect transformation
  osu.Framework.Tests/Visual/TestCaseLayoutDurations.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
Labels: bug, drawable

#1808 Auto-unbind all bindables in drawables when disposed
  osu-framework.sln.DotSettings
  osu.Framework.Tests/Bindables/BindableBindingTest.cs
  osu.Framework/Graphics/Drawable.cs
Labels: bindable

#1792 Reduce flow overhead by avoiding transforms when possible
  osu.Framework.Tests/Visual/TestCaseLayoutDurations.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
Labels: performance

#1810 Fix TestBrowser crashing when changing testcases
  osu.Framework/Testing/TestBrowser.cs
Labels: testing

#1799 Fix layout invalidation issues related to BypassAutoSizeAxes
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
Labels: bug, drawable

#1793 Reduce thread concurrency and usage of LongRunning
  osu-framework.sln.DotSettings
  osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
  osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
  osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
  osu.Framework.Tests/IO/TestLogging.cs
  osu.Framework.Tests/Visual/TestCaseAnimation.cs
  osu.Framework.Tests/Visual/TestCaseConcurrentLoad.cs
  osu.Framework.Tests/Visual/TestCaseDrawableLoadCancellation.cs
  osu.Framework.Tests/Visual/TestCaseLocalisation.cs
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
  osu.Framework/Allocation/DependencyActivator.cs
  osu.Framework/Allocation/DependencyContainer.cs
  osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
  osu.Framework/Allocation/ResolvedAttribute.cs
  osu.Framework/Audio/Sample/SampleManager.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/Textures/RawTextureLoaderStore.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/IO/Stores/CachedResourceStore.cs
  osu.Framework/IO/Stores/DllResourceStore.cs
  osu.Framework/IO/Stores/FileSystemResourceStore.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/IResourceStore.cs
  osu.Framework/IO/Stores/ResourceStore.cs
  osu.Framework/IO/Stores/StorageBackedResourceStore.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/HeadlessGameHost.cs
  osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
Labels: performance

#1820 Fix LoadAsync ContinueWith not being cancelled
  osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
  osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
  osu.Framework.Tests/Visual/TestCaseDrawableLoadCancellation.cs
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
  osu.Framework/Allocation/DependencyContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Platform/GameHost.cs
Labels: blocked, drawable, regression

#1818 Use Timer for logger instead of GameThread
  osu.Framework/Logging/Logger.cs
Labels: performance

#1815 Reduce overhead of BackgroundStackTraceCollector
  osu.Framework/Statistics/BackgroundStackTraceCollector.cs
Labels: performance

#1819 Fix elapsed frame time not accounting for sleep time correctly
  osu.Framework.Tests/Visual/TestCaseTransformRewinding.cs
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Statistics/PerformanceMonitor.cs
  osu.Framework/Timing/FramedClock.cs
  osu.Framework/Timing/IFrameBasedClock.cs
  osu.Framework/Timing/ThrottledFrameClock.cs
Labels: performance

#1817 Correctly prioritize focused drawable for input propagation
  osu.Framework.Tests/Visual/TestCaseFocus.cs
  osu.Framework/Input/InputManager.cs
Labels: input

#1824 Remove shadow copy logic
  osu.Framework/Platform/DesktopGameHost.cs
Labels: code quality

#1823 Fix test failing when load is cancelled before BDL is reached
  osu.Framework.Tests/Visual/TestCaseDrawableLoadCancellation.cs
Labels: WIP, testing

#1825 Improve load logic of glyph stores
  osu.Framework/IO/Stores/FontStore.cs
  osu.Framework/IO/Stores/GlyphStore.cs
Labels: performance

#1830 Reduce async overhead in SpriteText layout
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: performance, regression

#1831 Restore synchronous store pathway where possible
  osu.Framework/Graphics/Textures/RawTextureLoaderStore.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/IO/Stores/DllResourceStore.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/OnlineStore.cs
  osu.Framework/IO/Stores/ResourceStore.cs
  osu.Framework/IO/Stores/StorageBackedResourceStore.cs
Labels: performance

#1834 Restore pre-async BDL/activator logic
  osu.Framework.Tests/Dependencies/DependencyContainerTest.cs
  osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
  osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
  osu.Framework/Allocation/DependencyActivator.cs
  osu.Framework/Allocation/DependencyContainer.cs
  osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
  osu.Framework/Allocation/ResolvedAttribute.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/IO/Stores/CachedResourceStore.cs
  osu.Framework/Platform/GameHost.cs
Labels: proposal

#1835 Improvements to LoadComponentAsync
  osu.Framework.Tests/Visual/TestCaseDrawableLoadCancellation.cs
  osu.Framework/Extensions/IEnumerableExtensions/EnumerableExtensions.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Threading/ThreadedTaskScheduler.cs
Labels: drawable, performance

#1832 Fix parent setter's invalidation never occurring
  osu.Framework.Tests/Visual/TestCaseSizing.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/Drawable.cs
Labels: resolves issue
