Repository ppy/osu-framework, pull requests merged in 2018-04, with the labels that each got.

#1492 Use Linq.Append and Prepend.
  osu.Framework/Input/FrameworkActionContainer.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Testing/DynamicClassCompiler.cs
Labels: code quality

#1498 Remove TestTestCase
  osu.Framework/Testing/Tests/TestTestCase.cs
Labels: code quality

#1499 Explicitly define the dynamic compilation namespace to avoid crosstalk
  osu.Framework/Properties/AssemblyInfo.cs
  osu.Framework/Testing/DynamicClassCompiler.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: testing

#1500 Make FrameworkTestCase abstract
  osu.Framework.Tests/Visual/FrameworkTestCase.cs
Labels: code quality, testing

#1501 Fix dynamic compiliation namespace suffix being appended multiple times
  osu.Framework/Testing/DynamicClassCompiler.cs
Labels: regression, testing

#1502 Fix test StepContainer light colours not always applying correctly
  osu.Framework/Testing/Drawables/Steps/AssertButton.cs
  osu.Framework/Testing/Drawables/Steps/StepButton.cs
  osu.Framework/Testing/Drawables/Steps/ToggleStepButton.cs
  osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestCase.cs
Labels: bug, testing

#1506 Fix regression in dynamic compilation
  osu.Framework/Testing/DynamicClassCompiler.cs
Labels: regression, testing

#1504 Significantly reduce number of IsMaskedAway calculations
  osu.Framework/Graphics/Drawable.cs
Labels: performance

#1518 Fix regression in input handler configuration
  osu.Framework/Configuration/FrameworkConfigManager.cs
  osu.Framework/Platform/GameHost.cs
Labels: input, regression

#1458 Simplify SetProportional in BindableNumber
  osu.Framework.Tests/Visual/TestCaseSliderbar.cs
  osu.Framework/Configuration/BindableNumber.cs
Labels: code quality

#1522 Fix potential nullref if GlyphStore is used too quickly
  osu.Framework/IO/Stores/GlyphStore.cs
Labels: resolves issue

#1524 Make sure each TestCase runs all tests under one GameHost
  osu.Framework.Tests/Visual/FrameworkTestCase.cs
  osu.Framework/Testing/TestCase.cs
  osu.Framework/Testing/TestCaseTestRunner.cs
Labels: testing

#1507 Fix ProxyDrawables not respecting whether the originals would be drawn
  appveyor.yml
  osu.Framework.Tests/Visual/TestCaseIsMaskedAway.cs
  osu.Framework.Tests/Visual/TestCaseProxyDrawables.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Drawable_ProxyDrawable.cs
  osu.Framework/Graphics/ProxyDrawable.cs
  osu.Framework/Platform/GameHost.cs
Labels: resolves issue

#1490 Make Screen.Push asynchronous when necessary
  osu.Framework.Tests/Visual/TestCaseScreen.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Screens/Screen.cs
Labels: blocked, user interface

#1529 Update to .NET 4.7.1
  .idea/.idea.osu-framework/.idea/runConfigurations/VisualTests__net471_.xml
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  SampleGame/SampleGame.csproj
  appveyor.yml
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/osu.Framework.csproj
Labels: compatibility

#1536 Fix new detections in rider 2018.1
  osu.Framework/Platform/Windows/TimePeriod.cs
Labels: code quality

#1530 Fix test steps being added in LoadComplete never running in nUnit
  osu.Framework/Testing/TestCase.cs
Labels: bug, testing

#1363 Switchable TabControl
  osu.Framework.Tests/Visual/TestCaseTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/UserInterface/TabItem.cs
  osu.Framework/Input/PlatformActionContainer.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
Labels: user interface

#1532 Replace PrimitiveType.Quads with PrimitiveType.TriangleStrip in CircularProgressDrawNode
  osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
Labels: code quality, compatibility
