Repository ppy/osu-framework, pull requests merged in 2019-07, with the labels that each got.

#2602 Centalise ToolWindow button creation
  osu.Framework/Graphics/Visualisation/ToolWindow.cs
  osu.Framework/Graphics/Visualisation/TreeContainer.cs
Labels: tooling

#2598 Global statistics display
  osu.Framework.Tests/Visual/Testing/TestSceneGlobalStatisticsDisplay.cs
  osu.Framework/Game.cs
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
  osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
  osu.Framework/Input/FrameworkActionContainer.cs
  osu.Framework/Statistics/GlobalStatistic.cs
  osu.Framework/Statistics/GlobalStatistics.cs
  osu.Framework/Statistics/IGlobalStatistic.cs
Labels: tooling

#2608 Schedule DrawNode's finalizer disposal path
  osu.Framework/Graphics/DrawNode.cs
Labels: graphics, regression

#2603 Add invalidation event when a parent changes
  osu.Framework/Graphics/Drawable.cs
Labels: drawable

#2604 Fix delayed load unload reference retention
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadWrapper.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedUnload.cs
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
  osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
Labels: drawable, memory

#2606 Add disk caching for GlyphStores to reduce LOH usage
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Game.cs
  osu.Framework/IO/Stores/FontStore.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/StorageBackedResourceStore.cs
  osu.Framework/Platform/NativeStorage.cs
  osu.Framework/Platform/Storage.cs
Labels: memory

#2612 Fix DelayedLoadUnloadWrapper unnecessarily reloading after removal
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
  osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
Labels: drawable, regression

#2614 Add some more basic statistics to GlobalStatistics
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Logging/Logger.cs
Labels: tooling

#2615 Show all FrameStatistics in GlobalStatistics
  osu.Framework/Statistics/PerformanceMonitor.cs
Labels: tooling

#2619 Add lifetime support to DelayedLoadUnloadWrapper
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
Labels: resolves issue

#2617 Avoid schedule invocations from global statistic changes
  osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
Labels: performance, tooling

#2616 Add basic formatting support to GlobalStatisticsDisplay
  osu.Framework/Statistics/GlobalStatistic.cs
Labels: tooling

#2592 Implement OpenUrlExternally on iOS
  osu.Framework.Tests/Visual/Platform/TestSceneExternalLinks.cs
  osu.Framework.iOS/IOSGameHost.cs
Labels: iOS

#2611 Make Dropdown a composite drawable
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
Labels: code quality, user interface

#2599 Allow to modify the shadow offset of SpriteText
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
Labels: code quality, drawable

#2620 Fix DelayedLoadUnloadWrapper loaded count being incorrect
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
Labels: bug

#2567 Implement clipboard on iOS
  osu.Framework.iOS/IOSClipboard.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework.iOS/IOSGameView.cs
  osu.Framework.iOS/Input/IOSKeyboardHandler.cs
Labels: iOS, input

#2626 Fix nullref on using logger without a target specification
  osu.Framework/Logging/Logger.cs
Labels: logging, regression, resolves issue

#2633 Update NuGet packages
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/osu.Framework.csproj
Labels: libraries

#2613 Add FlowContainer.Insert method
  osu.Framework/Graphics/Containers/FlowContainer.cs
Labels: drawable

#2607 Rename extra mouse buttons in the InputKey enum
  osu.Framework/Input/Bindings/InputKey.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
Labels: resolves issue

#2628 Replace Thread.Sleep waits with ManualResetEventSlim
  osu.Framework.Tests/IO/BackgroundGameHeadlessGameHost.cs
  osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
  osu.Framework/Platform/GameHost.cs
Labels: code quality

#2627 Reset StopwatchClock rate calculations on Reset and Restart
  osu.Framework.Tests/Audio/AudioComponentTest.cs
  osu.Framework.Tests/Clocks/StopwatchClockTest.cs
  osu.Framework/Timing/StopwatchClock.cs
Labels: clocks, resolves issue

#2632 Fix android keyboard input
  osu.Framework.Android/AndroidGameView.cs
  osu.Framework.Android/Input/AndroidInputConnection.cs
  osu.Framework.Android/Input/AndroidKeyboardHandler.cs
  osu.Framework.Android/Input/AndroidTextInput.cs
Labels: android, resolves issue

#2420 Initial implementation of safe area snapping
  osu.Framework.Tests/Visual/Containers/TestSceneSafeAreaContainer.cs
  osu.Framework.Tests/Visual/Containers/TestSceneSafeAreaOverrides.cs
  osu.Framework.Tests/Visual/Platform/TestSceneSafeArea.cs
  osu.Framework.Tests/VisualTestGame.cs
  osu.Framework.iOS/IOSGameWindow.cs
  osu.Framework/Bindables/BindableSafeArea.cs
  osu.Framework/Graphics/Containers/ISafeArea.cs
  osu.Framework/Graphics/Containers/SafeAreaContainer.cs
  osu.Framework/Graphics/Containers/SafeAreaDefiningContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/GameWindow.cs
  osu.Framework/Platform/IWindow.cs
  osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
  osu.Framework/Testing/Drawables/TestSceneButton.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: iOS, mobile

#2637 Remove FileSafety helper class
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/NativeStorage.cs
Labels: code quality

#2625 Improve glyph copy performance by using read offset
  osu.Framework/IO/Stores/GlyphStore.cs
Labels: performance

#2638 Adjust audio rate when changing playback rate in TestBrowser
  osu.Framework/Testing/TestBrowser.cs
Labels: testing

#2650 Fix non-loaded drawables potentially being drawn
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: drawable, performance

#2652 Use GC SustainedLowLatency again
  osu.Framework/Platform/GameHost.cs
Labels: performance

#2643 Dispose drawables that are not yet loaded inside CompositeDrawable
  osu.Framework.Tests/Visual/Containers/TestSceneLoadComponentAsync.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: drawable, resolves issue

#2657 Avoid creating joystick states for disconnected devices
  osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
Labels: input, memory

#2654 Remove bindable/string allocation overhead of global statistics
  osu.Framework.Tests/Visual/Testing/TestSceneGlobalStatisticsDisplay.cs
  osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
  osu.Framework/Statistics/GlobalStatistic.cs
  osu.Framework/Statistics/IGlobalStatistic.cs
Labels: memory

#2655 Reduce transform allocation overhead of autosize updates
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: memory

#2656 Reduce overhead incurred by TooltipContainer when no tooltip is visible
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
Labels: memory, performance

#2662 Fix HandleGC flag being set to an incorrect default
  osu.Framework/Statistics/PerformanceMonitor.cs
Labels: code quality

#2663 Add memory pooling for VBO arrays
  osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
Labels: memory, performance

#2660 Fix TabControl throwing bindable disabled errors on load complete
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
Labels: bug, user interface

#2653 Fix glyphs being read outside of cached texture bounds
  osu.Framework/IO/Stores/GlyphStore.cs
Labels: bug

#2665 Add basic GC stats to global statistics
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Statistics/DotNetRuntimeListener.cs
  osu.Framework/Statistics/GlobalStatistic.cs
Labels: logging

#2664 Add last disposed drawable statistic
  osu.Framework/Allocation/AsyncDisposalQueue.cs
  osu.Framework/Statistics/GlobalStatistic.cs
Labels: logging

#2670 Rework and simplify RenderBuffer to fix incorrect usages
  osu.Framework/Graphics/BufferedDrawNode.cs
  osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: resolves issue

#2674 Reduce LinearBatch size of CircularProgress
  osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
Labels: memory

#2676 Use TextureWithRefCount for paths
  osu.Framework/Graphics/Lines/SmoothPath.cs
  osu.Framework/Graphics/Textures/TextureWithRefCount.cs
Labels: performance

#2672 Avoid disposing Path texture
  osu.Framework/Graphics/Lines/Path.cs
Labels: code quality

#2673 Avoid creating mipmaps for SmoothPath
  osu.Framework/Graphics/Lines/SmoothPath.cs
Labels: performance

#2679 Fix vertex buffers overflowing too early
  osu.Framework/Graphics/Batches/VertexBatch.cs
Labels: performance, resolves issue

#2683 Fix FrameworkActions not being handled in some scenarios
  osu.Framework.Tests/Visual/Input/TestSceneMouseStates.cs
  osu.Framework/Game.cs
  osu.Framework/Input/FrameworkActionContainer.cs
Labels: input, resolves issue

#2684 Add native memory stats
  osu.Framework/Audio/Sample/SampleBass.cs
  osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
Labels: logging

#2687 Remove Shift-Delete platform binding
  osu.Framework/Platform/GameHost.cs
Labels: input

#2688 Optimise vertex buffer vertex additions
  osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
  osu.Framework/Graphics/OpenGL/Vertices/DepthWrappingVertex.cs
Labels: performance, regression

#2689 Only consume ETW events after GlobalStatistics has become visible
  osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
  osu.Framework/Platform/GameHost.cs
Labels: logging

#2690 Fix bindable potentially deadlocking on nested enumeration operations
  osu.Framework/Bindables/Bindable.cs
Labels: bindable, bug

#2691 Allow memory clean-up via GameHost.Collect
  osu.Framework.Android/AndroidGameActivity.cs
  osu.Framework.Android/AndroidGameView.cs
  osu.Framework.iOS/GameAppDelegate.cs
  osu.Framework.iOS/GameViewController.cs
  osu.Framework/Platform/GameHost.cs
Labels: memory

#2698 Fix DelayedLoadUnloadWrapper potentially entering wrong optimisation mode
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
Labels: drawable

#2696 Implement proper auto-sizing for Path
  osu.Framework.Tests/Visual/Drawables/TestScenePathApproximator.cs
  osu.Framework.Tests/Visual/Input/TestSceneInputResampler.cs
  osu.Framework.Tests/Visual/Input/TestScenePathInput.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneDrawablePath.cs
  osu.Framework/Graphics/Lines/Path.cs
Labels: drawable

#2668 Add media keys to InputKey enum
  osu.Framework/Input/Bindings/InputKey.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
  osu.Framework/osu.Framework.csproj
Labels: input

#2694 Expose CompositeDrawable's subtree specific positional input conditional
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: drawable

#2699 Eagerly dispose FrameBuffers' backing textures
  osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
Labels: performance

#2701 Fix iOS nullref on orientation change
  osu.Framework.iOS/GameViewController.cs
Labels: iOS, regression

#2704 Use NativeReference instead of -force_load for iOS
  SampleGame.iOS/SampleGame.iOS.csproj
  osu.Framework.NativeLibs/ios/libbass.a
  osu.Framework.NativeLibs/ios/libbass_fx.a
  osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj
  osu.Framework.Tests.iOS/osu.Framework.Tests.iOS.csproj
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.csproj
Labels: iOS

#2700 Make GL scissor stateful
  osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: graphics

#2702 Track native memory allocations via a central class
  osu.Framework/Allocation/InvokeOnDisposal.cs
  osu.Framework/Audio/Sample/SampleBass.cs
  osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Platform/NativeMemoryTracker.cs
Labels: logging, memory

#2708 Remove setting to bypass cached
  osu.Framework/Caching/Cached.cs
  osu.Framework/Configuration/FrameworkDebugConfig.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: resolves issue

#2709 Fix renderbuffers not attaching correctly
  osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
Labels: resolves issue

#2710 Cleanup framebuffer initialisation process
  osu.Framework/Graphics/BufferedDrawNode.cs
  osu.Framework/Graphics/BufferedDrawNodeSharedData.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
Labels: code quality, drawable, graphics

#2680 Explicity specify precision for all shader variables
  osu.Framework.Tests/Graphics/ShaderRegexTest.cs
  osu.Framework.Tests/Visual/Containers/TestSceneContainerState.cs
  osu.Framework/Graphics/Shaders/Shader.cs
  osu.Framework/Graphics/Shaders/ShaderManager.cs
  osu.Framework/Graphics/Shaders/ShaderPart.cs
  osu.Framework/Resources/Shaders/sh_Backbuffer_Internal.h
  osu.Framework/Resources/Shaders/sh_Blur.fs
  osu.Framework/Resources/Shaders/sh_Position.vs
  osu.Framework/Resources/Shaders/sh_Precision_Internal.h
  osu.Framework/Resources/Shaders/sh_Texture.fs
  osu.Framework/Resources/Shaders/sh_Texture2D.vs
  osu.Framework/Resources/Shaders/sh_Texture3D.vs
  osu.Framework/Resources/Shaders/sh_TextureRounded.fs
  osu.Framework/Resources/Shaders/sh_Utils.h
Labels: graphics, mobile
