Repository ppy/osu-framework, pull requests merged in 2019-11, with the labels that each got.

#2936 Remove detection of wine and some others
  osu.Framework/RuntimeInfo.cs
Labels: code quality, compatibility, size/M

#2934 Several minor code quality improvements
  osu.Framework.Tests/Visual/Containers/TestSceneTextFlowContainer.cs
  osu.Framework.iOS/GameUIApplication.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Extensions/IEnumerableExtensions/EnumerableExtensions.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
  osu.Framework/IO/Stores/FontStore.cs
  osu.Framework/MathUtils/Validation.cs
  osu.Framework/Platform/Linux/LinuxGameWindow.cs
  osu.Framework/Platform/MacOS/MacOSGameWindow.cs
Labels: code quality, size/M

#2943 Update Microsoft.Diagnostics.Runtime to latest official package
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#2946 Fix thread culture setting tests
  osu.Framework.Tests/Localisation/ThreadCultureTest.cs
Labels: size/S, testing

#2940 Fix initial mouse position being potentially in wrong coordinate space
  osu.Framework/Input/InputManager.cs
Labels: input, size/XS

#2939 Add LongRunningLoad attribute to better cater to online load components
  osu.Framework.Tests/Containers/TestSceneLongRunningLoad.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
  osu.Framework/Allocation/LongRunningLoadAttribute.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
Labels: code quality, drawable, performance, size/L

#2947 Update NativeLibs to new version
  osu.Framework.Tests/Audio/AudioComponentTest.cs
  osu.Framework.Tests/Audio/TrackBassTest.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/Platform/Architecture.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/osu.Framework.csproj
Labels: libraries, size/XS

#2957 Add missing ifdef around using to silence error on certain target frameworks
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: code quality, size/XS

#2962 Fix negative frame time on frame time display
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Statistics/PerformanceMonitor.cs
  osu.Framework/Threading/GameThread.cs
Labels: resolves issue, size/L, size/M

#2963 Refactor throttled frame time display
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Timing/ThrottledFrameClock.cs
Labels: code quality, size/L

#2958 Fix first drag event potentially not being triggered
  osu.Framework.Tests/Visual/Input/TestSceneMouseStates.cs
  osu.Framework/Input/MouseButtonEventManager.cs
Labels: input, size/S

#2959 Mark visual tests with no display as headless
  osu.Framework.Tests/Visual/Drawables/TestSceneIsMaskedAway.cs
  osu.Framework.Tests/Visual/Drawables/TestScenePropertyBoundaries.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
Labels: size/XS, testing

#2960 Add DragBlocksClick and more correctly handle off-axis drags
  osu.Framework.Tests/Visual/Input/TestSceneClickLenience.cs
  osu.Framework/Graphics/Containers/OverlayContainer.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/MouseButtonEventManager.cs
Labels: input, size/L

#2948 Apply new language features
  .editorconfig
  Directory.Build.props
  SampleGame.iOS/SampleGame.iOS.csproj
  osu-framework.sln.DotSettings
  osu.Framework.Android.props
  osu.Framework.Tests.Android/osu.Framework.Tests.Android.csproj
  osu.Framework.Tests.iOS/osu.Framework.Tests.iOS.csproj
  osu.Framework.Tests/IO/TestSortedListSerialization.cs
  osu.Framework.Tests/Polygons/LineIntersections.cs
  osu.Framework.Tests/Visual/Containers/TestSceneCircularContainerSizing.cs
  osu.Framework.Tests/Visual/Containers/TestSceneCoordinateSpaces.cs
  osu.Framework.Tests/Visual/Containers/TestSceneMasking.cs
  osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneFocusedOverlayContainer.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTooltip.cs
  osu.Framework.iOS.props
  osu.Framework.iOS/GameUIApplication.cs
  osu.Framework/Allocation/IReadOnlyDependencyContainer.cs
  osu.Framework/Allocation/ObjectHandle.cs
  osu.Framework/Audio/Track/ITrackStore.cs
  osu.Framework/Graphics/Containers/FillFlowContainer.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
  osu.Framework/Graphics/Containers/TableContainer.cs
  osu.Framework/Graphics/Primitives/RectangleF.cs
  osu.Framework/Graphics/Primitives/RectangleI.cs
  osu.Framework/Graphics/Sprites/FontUsage.cs
  osu.Framework/Graphics/Sprites/IconUsage.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/Input/States/ButtonStates.cs
  osu.Framework/Logging/Logger.cs
  osu.Framework/Testing/DynamicClassCompiler.cs
Labels: code quality, size/XXL

#2973 Catch exceptions thrown by BackgroundStackTraceCollector
  osu.Framework/Statistics/BackgroundStackTraceCollector.cs
Labels: size/S

#2975 Fix comment typo in UserInputManager
  osu.Framework/Input/UserInputManager.cs
Labels: size/XS

#2978 Allow all buttons to drag in scroll container
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: input, size/XS, user interface

#2980 Revert breaking scroll container changes
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: size/XS

#2976 Fix IHasCurrent UI components potentially unbinding unrelated bindables
  osu.Framework.Tests/Bindables/BindableWithCurrentTest.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneCheckboxes.cs
  osu.Framework.Tests/Visual/UserInterface/TestUIComponentsWithCurrent.cs
  osu.Framework/Bindables/BindableWithCurrent.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/UserInterface/Checkbox.cs
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: bindable, bug, size/L

#2983 Lower severity of suspicious type conversion inspections
  osu-framework.sln.DotSettings
Labels: size/XS, tooling

#2971 Fix completed scheduled tasks allowed to run multiple times
  osu.Framework.Tests/Threading/SchedulerTest.cs
  osu.Framework/Threading/Scheduler.cs
Labels: size/M, threading

#2931 Optimize KeyCombination
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
Labels: code quality, performance, size/L

#2972 Switch to use Microsoft.Extension.ObjectPool
  osu.Framework/Allocation/ObjectStack.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/Statistics/PerformanceMonitor.cs
  osu.Framework/osu.Framework.csproj
Labels: dependencies, proposal, size/M

#2987 Move menu testing helper functions and structure to a base class
  osu.Framework.Tests/Visual/UserInterface/TestSceneNestedMenus.cs
  osu.Framework/Testing/MenuTestScene.cs
Labels: size/L, testing, user interface

#2985 Fix top-parent menu not getting closed by action-item click
  osu.Framework.Tests/Visual/UserInterface/TestSceneClosableMenu.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
Labels: resolves issue, size/M, user interface

#2988 Allow menu items to not close menus on action click
  osu.Framework.Tests/Visual/UserInterface/TestSceneUnclosableMenu.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
Labels: resolves issue, size/M, user interface

#2989 Refactor context menu tests
  osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs
Labels: code quality, size/L, testing

#2994 Implement context menu pass-through + blocking
  osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs
  osu.Framework/Graphics/Cursor/ContextMenuContainer.cs
  osu.Framework/Graphics/Cursor/IHasContextMenu.cs
Labels: resolves issue, size/L, user interface

#3000 Implement IAggregateAudioAdjustment for IAdjustableResourceStore
  osu.Framework.Tests/Audio/AudioComponentTest.cs
  osu.Framework/Audio/IAdjustableResourceStore.cs
Labels: size/XS

#2996 Implement apple's "continuous curves"
  osu.Framework.Tests/Visual/Containers/TestSceneMasking.cs
  osu.Framework.Tests/Visual/Input/TestSceneNestedHover.cs
  osu.Framework/Graphics/Containers/CircularContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
  osu.Framework/Graphics/Containers/Container.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
  osu.Framework/Graphics/Primitives/RectangleF.cs
  osu.Framework/Graphics/Shaders/GlobalProperty.cs
  osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
  osu.Framework/Resources/Shaders/sh_TextureRounded.fs
Labels: graphics, size/L, user interface

#3008 Remove obsolete weaklist methods
  osu.Framework/Lists/IWeakList.cs
  osu.Framework/Lists/LockedWeakList.cs
  osu.Framework/Lists/WeakList.cs
Labels: code quality, size/S

#3006 Fix bad references in xml doc
  osu.Framework/Bindables/AggregateBindable.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Bindables/IBindable.cs
  osu.Framework/Bindables/IBindableNumber.cs
  osu.Framework/Bindables/ICanBeDisabled.cs
  osu.Framework/Extensions/ExceptionExtensions/ExceptionExtensions.cs
  osu.Framework/Extensions/PolygonExtensions/ConvexPolygonExtensions.cs
  osu.Framework/Graphics/Audio/WaveformGraph.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
  osu.Framework/Graphics/DrawNode.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
  osu.Framework/Graphics/OpenGL/Vertices/VertexUtils.cs
  osu.Framework/Graphics/Sprites/FontAwesome.cs
  osu.Framework/Graphics/Textures/Texture.cs
  osu.Framework/Graphics/TransformableExtensions.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/Graphics/Transforms/TransformSequence.cs
  osu.Framework/Input/Bindings/KeyBinding.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/MouseButtonEventManager.cs
  osu.Framework/Input/StateChanges/ButtonInput.cs
  osu.Framework/Input/States/ButtonStates.cs
  osu.Framework/Text/MultilineTextBuilder.cs
  osu.Framework/Timing/FramedClock.cs
  osu.Framework/osu.Framework.csproj
Labels: documentation, size/L

#3016 Move to .NET Standard 2.1 at framework side
  SampleGame.Android/Properties/AndroidManifest.xml
  SampleGame.Android/SampleGame.Android.csproj
  SampleGame/SampleGame.csproj
  osu.Framework.Android.props
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.Tests.Android/Properties/AndroidManifest.xml
  osu.Framework.Tests.Android/osu.Framework.Tests.Android.csproj
  osu.Framework/osu.Framework.csproj
Labels: size/S

#3014 Fix iOS slnf including Android test project
  osu-framework.iOS.slnf
Labels: size/XS

#2979 Convert expensive WebRequest properties to methods
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs
  osu.Framework/IO/Network/JsonWebRequest.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/IO/Stores/OnlineStore.cs
Labels: code quality, network, size/M

#3012 Hide context menu on target disappearance
  osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs
  osu.Framework/Graphics/Cursor/ContextMenuContainer.cs
Labels: resolves issue, size/S, user interface

#3022 Use .NET Standard 2.1 Math/MathF functions
  osu.Framework.Tests/Visual/Containers/TestSceneMasking.cs
  osu.Framework.Tests/Visual/Input/TestSceneInputResampler.cs
  osu.Framework/Extensions/MatrixExtensions/MatrixExtensions.cs
  osu.Framework/Graphics/BufferedDrawNode.cs
  osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
  osu.Framework/Graphics/Lines/Path_DrawNode.cs
  osu.Framework/Graphics/Primitives/Line.cs
  osu.Framework/Graphics/Primitives/RectangleF.cs
  osu.Framework/Graphics/Sprites/SpriteIcon.cs
  osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
  osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
  osu.Framework/Graphics/Vector2Extensions.cs
  osu.Framework/Input/InputResampler.cs
  osu.Framework/Physics/RigidBodyContainer.cs
Labels: code quality, size/M

#3023 Move performance logging setting to debug config
  osu.Framework/Configuration/FrameworkConfigManager.cs
  osu.Framework/Configuration/FrameworkDebugConfig.cs
  osu.Framework/Development/DebugUtils.cs
  osu.Framework/Platform/GameHost.cs
Labels: performance, size/XS

#3024 Fix TextureWithRefCount thread races
  osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
  osu.Framework/Graphics/Lines/SmoothPath.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
  osu.Framework/Graphics/Textures/DisposableTexture.cs
  osu.Framework/Graphics/Textures/LargeTextureStore.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/Graphics/Textures/TextureWithRefCount.cs
Labels: graphics, size/L

#3026 Fix interpolation extremities on exponential and elastic curves
  osu.Framework.Tests/MathUtils/TestInterpolation.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneEasingCurves.cs
  osu.Framework/MathUtils/Interpolation.cs
Labels: bug, graphics, resolves issue, size/L, user interface

#3028 Suppress MobileAuthenticatedStream exceptions
  osu.Framework.Android/AndroidGameView.cs
Labels: android, network, size/S

#3005 Use STBI backend to load images on Desktop
  osu.Framework/Graphics/Textures/TextureLoaderStore.cs
  osu.Framework/osu.Framework.csproj
Labels: dependencies, graphics, performance, size/S

#3035 Add support for TemporaryNativeStorage to create directory if non-existing
  osu.Framework.Tests/IO/FontStoreTest.cs
  osu.Framework.Tests/TemporaryNativeStorage.cs
Labels: code quality, size/S

#3036 Move texture loading logic to be more accessible
  osu.Framework/Graphics/Textures/TextureLoaderStore.cs
  osu.Framework/Graphics/Textures/TextureUpload.cs
Labels: code quality, size/M

#3037 Move common logic to base implementation of GlyphStore
  osu.Framework.Tests/IO/FontStoreTest.cs
  osu.Framework/Game.cs
  osu.Framework/IO/Stores/FontStore.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/RawCachingGlyphStore.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: code quality, size/L

#3025 Fix audio not working when no audio devices are present
  osu.Framework.Tests/Audio/AudioManagerWithDeviceLoss.cs
  osu.Framework.Tests/Audio/AudioThreadTest.cs
  osu.Framework.Tests/Audio/DeviceLosingAudioTest.cs
  osu.Framework.Tests/Audio/DevicelessAudioTest.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/Track/TrackBass.cs
Labels: audio, resolves issue, size/XL

#3032 Rework GL scissoring
  osu.Framework/Graphics/BufferedDrawNode.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: graphics, size/L

#3009 Remove some no longer required workarounds
  osu.Framework.Tests/Audio/AudioComponentTest.cs
  osu.Framework.Tests/Audio/TrackBassTest.cs
  osu.Framework.Tests/IO/FontStoreTest.cs
  osu.Framework.Tests/TestGame.cs
  osu.Framework.Tests/Visual/FrameworkTestScene.cs
  osu.Framework/Game.cs
  osu.Framework/IO/Stores/DllResourceStore.cs
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/Linux/Native/Library.cs
  osu.Framework/Platform/Windows/WindowsStorage.cs
Labels: code quality, size/M

#3045 Fix one remaining case of incorrect audio testing
  osu.Framework.Tests/Audio/DevicelessAudioTest.cs
Labels: size/XS, testing

#3040 Use per-platform texture loaders in GlyphStore
  osu.Framework/Game.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/RawCachingGlyphStore.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: code quality, performance, size/L

#3033 Implement FrameBufferScale for IBufferedDrawable/BufferedContainer
  osu.Framework.Tests/Visual/Containers/TestSceneBufferedContainer.cs
  osu.Framework/Graphics/BufferedDrawNode.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/IBufferedDrawable.cs
  osu.Framework/Graphics/Lines/Path.cs
Labels: graphics, size/L

#3042 Improve performance and reduce allocations of RawCachingGlyphStore
  osu.Framework/IO/Stores/RawCachingGlyphStore.cs
Labels: performance, size/L

#3039 Manually set alpha of all pixels rather than using ImageSharp's clear option
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/RawCachingGlyphStore.cs
Labels: performance, size/L

#3051 Fix FontStore test intermittently failing due to open file handles
  osu.Framework.Tests/IO/FontStoreTest.cs
  osu.Framework/IO/Stores/FontStore.cs
Labels: size/S, testing

#3050 Revert assembly load logic change to attempt to fix tests
  osu.Framework/IO/Stores/DllResourceStore.cs
Labels: regression, size/XS

#3057 Fix startup crash regression on Linux
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/Linux/Native/Library.cs
Labels: size/M
