Repository ppy/osu-framework, pull requests merged in 2019-12, with the labels that each got.

#3048 Change CornerExponent to default to 2
  osu.Framework/Graphics/Containers/CircularContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: drawable, size/XS

#3053 Add link to wiki explaining LongRunningLoad exception
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
Labels: documentation, size/XS

#3059 Replace macOS native osuTK reflection
  osu.Framework/Platform/MacOS/Native/Cocoa.cs
  osu.Framework/Platform/MacOS/Native/NSStringEncoding.cs
Labels: code quality, macOS, opentk, size/L

#3038 Add benchmarks project
  .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/Benchmarks.xml
  .vscode/launch.json
  build/Desktop.proj
  osu-framework.Desktop.slnf
  osu-framework.sln
  osu.Framework.Benchmarks/BenchmarkFontLoading.cs
  osu.Framework.Benchmarks/BenchmarkTest.cs
  osu.Framework.Benchmarks/Program.cs
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework/IO/Stores/RawCachingGlyphStore.cs
  osu.Framework/IO/Stores/TimedExpiryGlyphStore.cs
Labels: size/L, tooling

#3061 Fix audio thread disposal ordering
  osu.Framework/Game.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/Threading/AudioThread.cs
Labels: size/S, threading

#3067 Fix multiple enumeration in BindableList.AddRange
  osu.Framework.Tests/Bindables/BindableListTest.cs
  osu.Framework/Bindables/BindableList.cs
Labels: size/S

#3046 Refactor decoupled clock to better handle negative seeks
  osu.Framework.Tests/Clocks/DecoupleableClockTest.cs
  osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs
Labels: clocks, size/M

#3073 Fix LogOverlay causing a null reference on display via shortcut key
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
Labels: resolves issue, size/XS

#3070 Fix OnEntering being called before drawable is loaded
  osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: bug, screen, size/M

#3074 Always use latest c# version for dynamic compilation
  osu.Framework/Testing/DynamicClassCompiler.cs
Labels: size/XS, testing

#3075 Revert Microsoft.Extensions.ObjectPool update
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#3076 Fix debug log overlay setting not working correctly
  osu.Framework/Game.cs
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
Labels: resolves issue, size/M

#3082 Fix logger incorrectly using 12h hour format
  osu.Framework/Logging/Logger.cs
Labels: size/XS

#3079 Upon DLL load failure of libstbi, stop trying to use STBI forever
  osu.Framework/Graphics/Textures/TextureUpload.cs
Labels: graphics, libraries, size/XS

#3080 Fix GlyphStore finalizer potentially nullref-ing
  osu.Framework/IO/Stores/RawCachingGlyphStore.cs
  osu.Framework/IO/Stores/ResourceStore.cs
Labels: bug, size/S

#3084 Fix scheduler running in-place unintentionally
  osu.Framework.Tests/Threading/SchedulerTest.cs
  osu.Framework/Threading/Scheduler.cs
Labels: size/M, threading

#3085 Avoid incorrect exception being tested in screen test
  osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
Labels: size/XS, testing

#3086 Enable disabled audio tests
  osu.Framework.Tests/Visual/Audio/TestSceneLoopingSample.cs
Labels: size/XS, testing

#3089 Combine BindableNumber implementations into base class
  osu.Framework/Bindables/BindableDouble.cs
  osu.Framework/Bindables/BindableFloat.cs
  osu.Framework/Bindables/BindableInt.cs
  osu.Framework/Bindables/BindableLong.cs
  osu.Framework/Bindables/BindableNumber.cs
Labels: bindable, code quality, size/L

#3090 Fix SliderBar's Current implementation
  osu.Framework/Bindables/BindableNumberWithCurrent.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
Labels: bindable, size/L, user interface

#3093 Make BindableNumber able to handle more types
  osu.Framework.Tests/Bindables/BindableNumberTest.cs
  osu.Framework/Bindables/BindableNumber.cs
Labels: resolves issue, size/L

#3087 Add tempo adjustment support
  osu.Framework.Tests/Audio/TestAudioAdjustments.cs
  osu.Framework.Tests/Audio/TrackBassTest.cs
  osu.Framework.Tests/Visual/Audio/TestSceneTrackAdjustments.cs
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioAdjustments.cs
  osu.Framework/Audio/IAdjustableAudioComponent.cs
  osu.Framework/Audio/IAggregateAudioAdjustment.cs
  osu.Framework/Audio/IHasPitchAdjust.cs
  osu.Framework/Audio/IHasTempoAdjust.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Bindables/AggregateBindable.cs
  osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
Labels: blocked, size/L

#3091 Add basic tests ensuring using BindableWithCurrent is used in UI components
  osu.Framework.Tests/Bindables/BindableWithCurrentTest.cs
Labels: size/S, testing

#3094 Re-expose CurrentNumber in SliderBar for compatibility reasons
  osu.Framework/Graphics/UserInterface/SliderBar.cs
Labels: size/XS

#3095 Fix track rate not correctly accounting for aggregates
  osu.Framework.Tests/Audio/TrackBassTest.cs
  osu.Framework/Audio/Track/Track.cs
Labels: size/S

#3004 Clean up stale extension methods
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/IO/File/FileSafety.cs
  osu.Framework/IO/Network/FileWebRequest.cs
  osu.Framework/IO/Stores/DllResourceStore.cs
  osu.Framework/Platform/NativeStorage.cs
  osu.Framework/Platform/Storage.cs
Labels: code quality, size/L

#3017 Refine some generic constraints
  osu.Framework.Tests/Visual/Platform/TestSceneResourceStores.cs
  osu.Framework/Allocation/ObjectHandle.cs
  osu.Framework/Allocation/ObjectUsage.cs
  osu.Framework/Allocation/TripleBuffer.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Bindables/IBindableNumber.cs
  osu.Framework/Bindables/NonNullableBindable.cs
  osu.Framework/Configuration/ConfigManager.cs
  osu.Framework/Configuration/IniConfigManager.cs
  osu.Framework/Configuration/Tracking/ITrackedSetting.cs
  osu.Framework/Configuration/Tracking/TrackedSetting.cs
  osu.Framework/Configuration/Tracking/TrackedSettings.cs
  osu.Framework/Graphics/Containers/IContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/OpenGL/Vertices/DepthWrappingVertex.cs
  osu.Framework/Graphics/OpenGL/Vertices/VertexUtils.cs
  osu.Framework/Graphics/TransformSequenceExtensions.cs
  osu.Framework/Graphics/TransformableExtensions.cs
  osu.Framework/Graphics/Transforms/Transform.cs
  osu.Framework/Graphics/Transforms/TransformBindable.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/Graphics/Transforms/TransformSequence.cs
  osu.Framework/IO/Stores/IGlyphStore.cs
  osu.Framework/IO/Stores/IResourceStore.cs
  osu.Framework/IO/Stores/NamespacedResourceStore.cs
  osu.Framework/IO/Stores/ResourceStore.cs
  osu.Framework/IStateful.cs
Labels: code quality, size/L

#3098 Make bindable min value update the current value
  osu.Framework.Tests/Bindables/BindableNumberTest.cs
  osu.Framework/Bindables/BindableNumber.cs
Labels: bindable, size/M

#3096 Use bindable constructor value as the default for the bindable
  osu.Framework.Tests/Bindables/BindableTest.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/BindableDouble.cs
  osu.Framework/Bindables/BindableFloat.cs
  osu.Framework/Bindables/BindableInt.cs
  osu.Framework/Bindables/BindableNumber.cs
Labels: bindable, size/M

#3099 Make bindable max value update the current value
  osu.Framework.Tests/Bindables/BindableNumberTest.cs
  osu.Framework/Bindables/BindableNumber.cs
Labels: bindable, size/M

#3097 Make bindable precision update the current value
  osu.Framework.Tests/Bindables/BindableNumberTest.cs
  osu.Framework/Bindables/BindableNumber.cs
Labels: bindable, size/M

#3100 Revert vertex sizeof marshalling
  osu.Framework/Graphics/OpenGL/Vertices/VertexUtils.cs
Labels: graphics, regression, size/XS

#3101 Fix LogOverlay initialisation occurring before ShaderManager
  osu.Framework/Game.cs
Labels: size/M

#3102 Fix potential failure in screen test
  osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
Labels: size/XS, testing

#3103 NativeStorage should not throw when path does not exist
  osu.Framework/Platform/NativeStorage.cs
Labels: size/XS

#3007 Apply outstanding FxCop rules
  CodeAnalysis/BannedSymbols.txt
  CodeAnalysis/osu-framework.ruleset
  Directory.Build.props
  osu-framework.sln
  osu-framework.sln.DotSettings
  osu.Framework.Android/AndroidGameView.cs
  osu.Framework.Android/Graphics/Video/AndroidVideoDecoder.cs
  osu.Framework.Tests/Dependencies/CachedAttributeTest.cs
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework.Tests/Lists/TestArrayExtensions.cs
  osu.Framework.Tests/MathUtils/TestInterpolation.cs
  osu.Framework.Tests/Visual/Layout/TestSceneFillFlowContainer.cs
  osu.Framework.iOS/Graphics/Video/IOSVideoDecoder.cs
  osu.Framework/Allocation/CachedAttribute.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Graphics/Containers/ContainerExtensions.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs
  osu.Framework/Graphics/Primitives/RectangleI.cs
  osu.Framework/Graphics/Sprites/FontUsage.cs
  osu.Framework/Graphics/Sprites/IconUsage.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/Graphics/Transforms/TransformSequence.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/MathUtils/Interpolation.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/GameWindow.cs
  osu.Framework/Platform/HeadlessGameHost.cs
  osu.Framework/Platform/MacOS/Native/NSApplication.cs
  osu.Framework/Platform/MacOS/Native/NSNotificationCenter.cs
  osu.Framework/Platform/NativeMemoryTracker.cs
  osu.Framework/Platform/Storage.cs
  osu.Framework/Platform/Windows/Native/Input.cs
  osu.Framework/Statistics/DotNetRuntimeListener.cs
  osu.Framework/Testing/Drawables/TestGroupButton.cs
  osu.Framework/Testing/DynamicClassCompiler.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/osu.Framework.csproj
Labels: code quality

#3104 Fix finalizer potentially polluting disposal test results
  osu.Framework.Tests/Containers/TestSceneContainerState.cs
Labels: size/XS, testing

#3109 Don't initialise toolkit in headless mode
  osu.Framework/Platform/GameHost.cs
Labels: macOS, performance, size/XS, testing

#3110 Fix nunit starting up window in headless mode
  osu.Framework/Platform/GameHost.cs
Labels: macOS, size/XS, testing

#3111 Fix toolkit not initialising for headed game hosts
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/HeadlessGameHost.cs
Labels: regression, size/S

#3112 Ensure test isolation in TestBrowser by disposing eagerly
  osu.Framework/Testing/TestBrowser.cs
Labels: size/S, testing

#3114 Update osuTK to fix macOS window focus issues
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#3113 Refactor BindableNumber to reduce compiler warnings
  osu.Framework/Bindables/BindableNumber.cs
Labels: bindable, code quality, size/S

#3116 Fix runaway scenario in video decoding loop
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: performance, size/XS

#3117 Set framesync based on the refresh rate of the current display
  osu.Framework/Platform/GameHost.cs
Labels: size/XS

#3121 Minor fixes for benchmark project
  .editorconfig
  .vscode/launch.json
  Directory.Build.props
  osu.Framework.Android.props
  osu.Framework.Benchmarks/Program.cs
  osu.Framework.Benchmarks/Properties/launchSettings.json
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework.iOS.props
Labels: size/M, tooling

#3126 Fix decode loop potentially running after stream disposal
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: size/XS

#3119 Optimize some struct performance by using readonly methods and in modifier
  osu.Framework/Allocation/ValueInvokeOnDisposal.cs
  osu.Framework/Audio/Track/TrackAmplitudes.cs
  osu.Framework/Graphics/BlendingParameters.cs
  osu.Framework/Graphics/Colour/ColourInfo.cs
  osu.Framework/Graphics/Colour/SRGBColour.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/Container.cs
  osu.Framework/Graphics/Containers/LifetimeManagementContainer.cs
  osu.Framework/Graphics/DrawColourInfo.cs
  osu.Framework/Graphics/DrawInfo.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Effects/EdgeEffectParameters.cs
  osu.Framework/Graphics/MarginPadding.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
  osu.Framework/Graphics/OpenGL/Vertices/DepthWrappingVertex.cs
  osu.Framework/Graphics/OpenGL/Vertices/ParticleVertex2D.cs
  osu.Framework/Graphics/OpenGL/Vertices/TexturedVertex2D.cs
  osu.Framework/Graphics/OpenGL/Vertices/TexturedVertex3D.cs
  osu.Framework/Graphics/OpenGL/Vertices/TimedTexturedVertex2D.cs
  osu.Framework/Graphics/OpenGL/Vertices/UncolouredVertex2D.cs
  osu.Framework/Graphics/OpenGL/Vertices/Vertex2D.cs
  osu.Framework/Graphics/Primitives/ProjectionRange.cs
  osu.Framework/Graphics/Primitives/Quad.cs
  osu.Framework/Graphics/Primitives/Triangle.cs
  osu.Framework/Graphics/Primitives/Vector2I.cs
  osu.Framework/Graphics/Shapes/Box.cs
  osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
  osu.Framework/Input/JoystickAxis.cs
  osu.Framework/Input/States/ButtonStates.cs
  osu.Framework/Lists/LockedWeakList.cs
  osu.Framework/Lists/SortedList.cs
  osu.Framework/Lists/WeakList.cs
  osu.Framework/Platform/MacOS/MacOSClipboard.cs
  osu.Framework/Platform/MacOS/Native/NSArray.cs
  osu.Framework/Platform/MacOS/Native/NSDictionary.cs
  osu.Framework/Platform/MacOS/Native/NSPasteboard.cs
  osu.Framework/Platform/Windows/Native/IconGroup.cs
  osu.Framework/Text/TextBuilderGlyph.cs
  osu.Framework/Timing/FrameTimeInfo.cs
Labels: performance, size/L

#3123 Add DefaultChanged event to bindables
  osu.Framework.Tests/Bindables/BindableBindingTest.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/ValueChangedEvent.cs
Labels: size/L

#3130 Fix transform rewinding test scene breaking scroll
  osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
Labels: size/S, testing

#3128 Fix framesync regression on Android and iOS
  osu.Framework.Android/AndroidGameWindow.cs
  osu.Framework.iOS/IOSGameWindow.cs
Labels: android, iOS, opentk, resolves issue, size/S

#3132 .NET Core 3.1 at framework side
  .editorconfig
  .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/Benchmarks.xml
  .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/SampleGame.xml
  .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/VisualTests.xml
  .vscode/launch.json
  README.md
  SampleGame.Desktop/SampleGame.Desktop.csproj
  build/build.cake
  global.json
  osu-framework.sln.DotSettings
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/Graphics/Containers/CustomizableTextContainer.cs
  osu.Framework/Graphics/Containers/FillFlowContainer.cs
  osu.Framework/Graphics/Vector2Extensions.cs
  osu.Framework/MathUtils/Clipping/ConvexPolygonClipper.cs
  osu.Framework/Text/TextBuilder.cs
  osu.Framework/Text/TruncatingTextBuilder.cs
Labels: code quality, size/M, tooling

#3131 Add extension method to easily access children of a specific type without manual traversal
  osu.Framework/Testing/MenuTestScene.cs
  osu.Framework/Testing/TestingExtensions.cs
Labels: code quality, size/M

#3133 Change TabControl.IsSwitchable to property
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
Labels: size/XS

#3072 Make TextBox abstract and add custom carets
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Graphics/UserInterface/BasicPasswordTextBox.cs
  osu.Framework/Graphics/UserInterface/BasicTextBox.cs
  osu.Framework/Graphics/UserInterface/Caret.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: size/L, user interface

#3139 Ensure ResourceStore returns null rather than exception on null request
  osu.Framework/IO/Stores/ResourceStore.cs
Labels: size/XS

#3140 Replace custom IsFinite(float) with netstandard one
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/MathUtils/Validation.cs
Labels: size/M

#3142 Add extension method to get SHA-2 from string input
  osu.Framework/Extensions/ExtensionMethods.cs
Labels: size/S

#3143 Add Drawable.Empty static helper for empty construction
  osu.Framework/Graphics/Drawable.cs
Labels: code quality, size/XS

#3144 Change Drawable.Empty to a method
  osu.Framework/Graphics/Drawable.cs
Labels: size/XS

#3141 Fix GetCommonPrefix extension method failing on empty enumerable source
  osu.Framework.Tests/Lists/TestEnumerableExtensions.cs
  osu.Framework/Extensions/IEnumerableExtensions/EnumerableExtensions.cs
Labels: size/M

#3145 Set UserAgent on WebRequest level
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework/IO/Network/WebRequest.cs
Labels: network, size/M

#3146 Disable sample ramping
  osu.Framework/Audio/Sample/SampleChannelBass.cs
Labels: audio, size/XS

#3115 Fix joystick-related binding issues
  osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
  osu.Framework/Input/JoystickButton.cs
Labels: input, size/M
