Repository ppy/osu-framework, pull requests merged in 2019-03, with the labels that each got.

#2206 Defer system gestures on screen edges on iOS
  osu.Framework.iOS/GameViewController.cs
Labels: iOS

#2207 Fix pasting on iOS arbitrarily inserting spaces
  osu.Framework.iOS/IOSGameView.cs
Labels: iOS

#2208 Fix buffered containers causing GL errors
  osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: graphics

#2209 Fix some typos in bindable list
  osu.Framework/Bindables/BindableList.cs
Labels: code quality

#2205 Ensure vertex buffers initialise on the draw thread
  osu.Framework/Graphics/OpenGL/Buffers/LinearVertexBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/QuadVertexBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
Labels: graphics

#2087 Add support for physical keyboard raw input for iOS
  osu.Framework.iOS/GameUIApplication.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework.iOS/Input/IOSRawKeyboardHandler.cs
Labels: iOS, input

#2213 Make BlendingInfo readonly
  osu.Framework/Graphics/BlendingInfo.cs
Labels: code quality

#2211 Increase the test timeout to 5 minutes per test
  build/build.cake
  build/vstestconfig.runsettings
Labels: testing

#2217 Update sourcelink version
  osu.Framework/osu.Framework.csproj
Labels: resolves issue

#2216 Add x64 BASS libraries
  osu.Framework.NativeLibs/x86/libbass.so
  osu.Framework.NativeLibs/x86/libbass_fx.so
  osu.Framework.NativeLibs/x86_64/libbass.so
  osu.Framework.NativeLibs/x86_64/libbass_fx.so
Labels: compatibility, libraries

#2210 Dispose DrawNodes and their associated vertex buffers
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseCircularProgress.cs
  osu.Framework/Graphics/Audio/WaveformGraph.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/BufferedContainerDrawNode.cs
  osu.Framework/Graphics/Containers/CompositeDrawNode.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/Container.cs
  osu.Framework/Graphics/DrawNode.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Drawable_ProxyDrawable.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/Lines/PathDrawNode.cs
  osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
  osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
  osu.Framework/Graphics/Shaders/IShader.cs
  osu.Framework/Graphics/Shaders/Shader.cs
  osu.Framework/Graphics/Shaders/ShaderManager.cs
  osu.Framework/Graphics/Shaders/ShaderPart.cs
  osu.Framework/Graphics/Sprites/Sprite.cs
  osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
  osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
Labels: graphics, performance

#2222 Add BindTarget to Bindable for use in object initializers
  osu.Framework/Bindables/Bindable.cs
Labels: bindable, code quality

#2223 Update NativeLibs target version
  osu.Framework/osu.Framework.csproj
Labels: libraries

#2220 Return all leases before OnResuming is called for a resuming screen
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreenStack.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: resolves issue

#2226 Use leased copy to make CI stop giving warnings
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreenStack.cs
Labels: testing

#2219 Fix CursorContainer's handling when mouse is not moved
  osu.Framework.Tests/Visual/TestCaseContainer/TestCaseCursorContainer.cs
  osu.Framework/Graphics/Cursor/CursorContainer.cs
Labels: resolves issue

#2224 Return any lease when calling UnbindAll on the lease source
  osu.Framework.Tests/Bindables/BindableLeasingTest.cs
  osu.Framework/Bindables/Bindable.cs
Labels: bindable

#2225 Rename PathWidth to PathRadius
  osu.Framework.Tests/Visual/TestCaseInput/TestCaseInputResampler.cs
  osu.Framework.Tests/Visual/TestCaseInput/TestCasePathInput.cs
  osu.Framework.Tests/Visual/TestCasePathApproximator.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseDrawablePath.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/Lines/PathDrawNode.cs
  osu.Framework/Graphics/Lines/SmoothPath.cs
Labels: code quality

#2232 Fix premature disposal of ResponseStream
  osu.Framework/IO/Network/WebRequest.cs
Labels: resolves issue

#2231 Check for parent lifetime when deciding focus
  osu.Framework/Input/InputManager.cs
Labels: input, resolves issue

#2235 Add ability to list contents of a DllResourceStore
  osu.Framework/IO/Stores/DllResourceStore.cs
Labels: testing

#2237 Disallow setting Track.Rate directly
  osu.Framework/Audio/IHasTempoAdjust.cs
  osu.Framework/Audio/Track/Track.cs
Labels: resolves issue

#2246 Inform about dependency loader method being potentially asynchronous
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
Labels: documentation

#2252 Address styling issues on CodeFactor
  osu.Framework.Tests/Dependencies/CachedAttributeTest.cs
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework.Tests/Visual/Containers/TestCaseSizing.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseDrawableLoadCancellation.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseFocus.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseIsMaskedAway.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseTransformRewinding.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseTransformSequence.cs
  osu.Framework.Tests/Visual/Input/TestCaseHandleInput.cs
  osu.Framework.Tests/Visual/Input/TestCaseInputQueueChange.cs
  osu.Framework.Tests/Visual/Layout/TestCaseLayoutDurations.cs
  osu.Framework.Tests/Visual/Layout/TestCaseScrollableFlow.cs
  osu.Framework.Tests/Visual/Platform/TestCaseBorderless.cs
  osu.Framework/Graphics/Animations/Animation.cs
  osu.Framework/Graphics/Animations/IAnimation.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownHeading.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
  osu.Framework/Graphics/Cursor/ITooltip.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Effects/IEffect.cs
  osu.Framework/Graphics/Lines/PathDrawNode.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Primitives/Line.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/Input/Events/FocusEvent.cs
  osu.Framework/Input/Events/FocusLostEvent.cs
  osu.Framework/Input/Events/HoverEvent.cs
  osu.Framework/Input/Events/HoverLostEvent.cs
  osu.Framework/Input/Events/MouseEvent.cs
  osu.Framework/Testing/TestCase.cs
  osu.Framework/Threading/Scheduler.cs
Labels: code quality

#2241 Add maximum size support to GridContainer dimensions
  osu.Framework.Tests/Visual/Layout/TestCaseGridContainer.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRateSection.cs
  osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
Labels: drawable

#2253 Ensure public actions specify the event keyword
  osu.Framework/Graphics/Containers/Markdown/MarkdownImage.cs
  osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: resolves issue

#2248 Add label test steps and run SetUp + n steps by default
  osu.Framework/Testing/Drawables/Steps/LabelStep.cs
  osu.Framework/Testing/Drawables/Steps/StepButton.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestCase.cs
Labels: testing

#2242 Add tests showing behaviour of drawable-bindable unbinding
  osu.Framework.Tests/Visual/Bindables/TestCaseBindableAutoUnbinding.cs
Labels: bindable, testing

#2249 Fix TextFlowContainer not laying out correctly
  osu.Framework.Tests/Visual/Containers/TestCaseTextFlowContainer.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
Labels: drawable

#2251 Add non-immediate suspend support and fix many sanity issues with screens
  osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
  osu.Framework/Screens/IScreen.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: drawable, pending review, screen

#2256 Fix AddUntilStep/AddWaitStep having incorrect argument ordering
  osu.Framework.Tests/Visual/Containers/TestCaseCachedBufferedContainer.cs
  osu.Framework.Tests/Visual/Containers/TestCaseCompositeMutability.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseConcurrentLoad.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseDelayedLoad.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseDelayedUnload.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseDrawableLoadCancellation.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseIsMaskedAway.cs
  osu.Framework.Tests/Visual/Drawables/TestCaseModelBackedDrawable.cs
  osu.Framework.Tests/Visual/Input/TestCaseMouseStates.cs
  osu.Framework.Tests/Visual/Sprites/TestCaseSpriteTextPresence.cs
  osu.Framework.Tests/Visual/Sprites/TestCaseTextures.cs
  osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
  osu.Framework/Testing/TestCase.cs
Labels: code quality, testing

#2263 Allow draw visualisers to be targetted by each other
  osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Labels: testing, tooling

#2264 Add obsolete methods to avoid breaking test API change
  osu.Framework/Testing/TestCase.cs
Labels: testing

#2262 Ensure [SetUp] is run at least once when defined by a user test
  osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestCase.cs
Labels: testing

#2261 Fix possible DrawVisualiser property display nullref
  osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Labels: tooling

#2266 Add attribute [SetUpSteps]
  osu.Framework.Tests/Visual/Testing/TestCaseTest.cs
  osu.Framework/Testing/SetUpStepsAttribute.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestCase.cs
Labels: testing

#2260 Fix various Scheduler failure cases
  osu.Framework.Tests/Threading/SchedulerTest.cs
  osu.Framework/Threading/Scheduler.cs
Labels: threading

#2269 Relax RNG exception conditions
  osu.Framework/MathUtils/RNG.cs
Labels: code quality

#2273 Apply general clean-ups to iOS classes
  osu.Framework.iOS/GameUIApplication.cs
  osu.Framework.iOS/GameViewController.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework.iOS/IOSGameView.cs
  osu.Framework.iOS/IOSGameWindow.cs
  osu.Framework.iOS/Input/IOSKeyboardHandler.cs
  osu.Framework.iOS/Input/IOSRawKeyboardHandler.cs
  osu.Framework/Platform/MacOS/MacOSClipboard.cs
Labels: code quality

#2257 Decrease the verbosity of the build script's inspections
  build.sh
  build/build.cake
  osu.Framework/osu.Framework.csproj
Labels: tooling

#2274 Bring nuget packages up to date
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs
  osu.Framework/osu.Framework.csproj
Labels: libraries

#2276 Fix http (insecure) tests failing locally
  osu.Framework.Tests/IO/TestWebRequest.cs
Labels: testing

#2279 Set executable flag on build scripts
  build.ps1
  build.sh
Labels: testing

#2282 Make Screen.RemoveWhenNotAlive sealed
  osu.Framework/Screens/Screen.cs
Labels: code quality, screen

#2283 Fix SliderBar not correctly handling disabled bindables in commit logic
  osu.Framework.Tests/Visual/UserInterface/TestCaseSliderBar.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
Labels: resolves issue

#2285 Remove potentially expensive iteration over all vertex batches
  osu.Framework/Graphics/Batches/VertexBatch.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: performance

#2286 Improve performance of ForEachAlive
  osu.Framework/Lists/WeakList.cs
Labels: performance

#2281 Use ISO 8601 datetime for logger output
  osu.Framework/Logging/Logger.cs
Labels: logging

#2287 Add container extensions to make adding nested drawables easier
  osu.Framework/Graphics/Containers/ContainerExtensions.cs
Labels: code quality

#2289 Increase usability of WithChild/WithChildren
  osu.Framework/Graphics/Containers/Container.cs
  osu.Framework/Graphics/Containers/ContainerExtensions.cs
  osu.Framework/Graphics/Containers/IContainer.cs
Labels: code quality

#2294 Protect Game's public fields
  osu.Framework/Game.cs
  osu.Framework/Platform/GameHost.cs
Labels: code quality

#2271 Add support for portable installations
  osu.Framework.Android/AndroidGameHost.cs
  osu.Framework.Android/AndroidStorage.cs
  osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
  osu.Framework.Tests/IO/BackgroundGameHeadlessGameHost.cs
  osu.Framework.Tests/IO/TestDesktopStorage.cs
  osu.Framework.Tests/IO/TestLogging.cs
  osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
  osu.Framework.Tests/Platform/PortableInstallationTest.cs
  osu.Framework.Tests/Program.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework.iOS/IOSStorage.cs
  osu.Framework/Configuration/FrameworkConfigManager.cs
  osu.Framework/Game.cs
  osu.Framework/Host.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Platform/DesktopStorage.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/HeadlessGameHost.cs
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/Linux/LinuxStorage.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/MacOS/MacOSStorage.cs
  osu.Framework/Platform/NativeStorage.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/Platform/Windows/WindowsStorage.cs
Labels: configuration

#2293 Add SpriteIcon class and include FontAwesome font
  SampleGame.Desktop/SampleGame.Desktop.csproj
  SampleGame/SampleGame.csproj
  osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj
  osu.Framework.Tests/Visual/Sprites/TestCaseSpriteIcon.cs
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/Game.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Sprites/FontAwesome.cs
  osu.Framework/Graphics/Sprites/IconUsage.cs
  osu.Framework/Graphics/Sprites/SpriteIcon.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/ResourceStore.cs
  osu.Framework/Resources/Fonts/FontAwesome/FontAwesome.bin
  osu.Framework/Resources/Fonts/FontAwesome/FontAwesome_0.png
  osu.Framework/Resources/Fonts/FontAwesome/FontAwesome_1.png
  osu.Framework/Resources/Fonts/FontAwesome/FontAwesome_2.png
  osu.Framework/Resources/Fonts/FontAwesome/FontAwesome_3.png
  osu.Framework/Resources/Fonts/FontAwesome/FontAwesome_4.png
  osu.Framework/Resources/Fonts/FontAwesome/FontAwesome_5.png
  osu.Framework/Testing/DynamicClassCompiler.cs
  osu.Framework/osu.Framework.csproj
Labels: drawable, graphics

#2297 Fix thread race condition breaking TestLoadAsyncCancel
  osu.Framework.Tests/Visual/Drawables/TestCaseDrawableLoadCancellation.cs
Labels: testing

#2288 Update TestButton design
  osu.Framework/Testing/Drawables/TestCaseButton.cs
  osu.Framework/Testing/Drawables/TestCaseButtonGroup.cs
  osu.Framework/Testing/Drawables/TestCaseHeaderButton.cs
  osu.Framework/Testing/Drawables/TestCaseSubButton.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: user interface

#2303 Make colour for input errors adjustable
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: user interface

#2298 Fix top-level test buttons acting like a group
  osu.Framework/Testing/Drawables/TestCaseButtonGroup.cs
  osu.Framework/Testing/Drawables/TestCaseSubButton.cs
Labels: testing, user interface

#2301 Fix tests with steps added in LoadComplete always passing
  osu.Framework/Testing/TestCase.cs
Labels: bug, testing

#2304 Fix TestCaseScreenStack endlessly loading
  osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
Labels: testing

#2302 Don't select tests which are filtered away
  osu.Framework.Tests/Visual/UserInterface/TestCaseSearchContainer.cs
  osu.Framework/Graphics/Containers/IFilterable.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
  osu.Framework/Testing/Drawables/TestCaseButton.cs
  osu.Framework/Testing/Drawables/TestCaseButtonGroup.cs
  osu.Framework/Testing/Drawables/TestCaseHeaderButton.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: testing

#2305 Fix appveyor test output
  osu.Framework/Development/DebugUtils.cs
  osu.Framework/Testing/TestCase.cs
Labels: testing

#2308 Fix glyph character fallback regression
  osu.Framework/IO/Stores/FontStore.cs
Labels: regression
