Repository ppy/osu-framework, pull requests merged in 2019-02, with the labels that each got.

#2132 Fix video memory consumption
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/Graphics/Video/VideoSprite.cs
Labels: drawable, performance

#2131 Fix DrawVisualiser targetting invisible drawables with AlwaysPresent enabled
  osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Labels: user interface

#2130 Implement CachedModelDependencyContainer, replaces BindingContainer
  osu.Framework.Tests/Dependencies/CachedModelDependenciesTest.cs
  osu.Framework.Tests/Visual/TestCaseBindingContainer.cs
  osu.Framework/Allocation/CachedModelDependencyContainer.cs
  osu.Framework/Allocation/DependencyActivator.cs
  osu.Framework/Graphics/Containers/BindingContainer.cs
Labels: dependency-injection, pending review

#2138 Make IBindableList an IBindable
  osu.Framework/Configuration/BindableList.cs
  osu.Framework/Configuration/IBindableList.cs
Labels: bindable

#2139 Update bass native libraries to 2.4.14
  osu.Framework.NativeLibs/libbass.a
  osu.Framework.NativeLibs/libbass.dylib
  osu.Framework.NativeLibs/libbass.so
  osu.Framework.NativeLibs/libbass_fx.a
  osu.Framework.NativeLibs/libbass_fx.dylib
  osu.Framework.NativeLibs/libbass_fx.so
  osu.Framework.NativeLibs/x64/bass.dll
  osu.Framework.NativeLibs/x64/bass_fx.dll
  osu.Framework.NativeLibs/x86/bass.dll
  osu.Framework.NativeLibs/x86/bass_fx.dll
Labels: libraries

#1989 Notify about Track completion and failure
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Audio/Track/TrackVirtual.cs
Labels: audio, pending review

#2140 Update framework dependencies
  osu.Framework.iOS.props
  osu.Framework/osu.Framework.csproj
Labels: libraries

#2141 Remove + dispose exited screens
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: resolves issue

#2053 Implement Lagrange polynomial interpolation
  osu.Framework.Tests/MathUtils/TestInterpolation.cs
  osu.Framework.Tests/MathUtils/TestPathApproximator.cs
  osu.Framework.Tests/Visual/TestCasePathApproximator.cs
  osu.Framework/MathUtils/Interpolation.cs
  osu.Framework/MathUtils/PathApproximator.cs
Labels: utils

#2146 Fix incorrect order of unbind/rebind of shadow model
  osu.Framework.Tests/Dependencies/CachedModelDependenciesTest.cs
  osu.Framework/Allocation/CachedModelDependencyContainer.cs
  osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
Labels: bindable

#2144 Add bindable for 'safe area' padding
  osu.Framework.Tests/Bindables/BindableMarginPaddingTest.cs
  osu.Framework.Tests/Visual/TestCaseContainer/TestCaseSafeArea.cs
  osu.Framework.iOS/IOSGameView.cs
  osu.Framework.iOS/IOSGameWindow.cs
  osu.Framework/Configuration/BindableMarginPadding.cs
  osu.Framework/Platform/GameWindow.cs
Labels: mobile

#2155 Disallow screens from being added to hierarchy without stack parent
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreen.cs
  osu.Framework/Screens/Screen.cs
  osu.Framework/Testing/TestCaseTestRunner.cs
Labels: drawable

#2153 Fix screens (drawables) retaining focus when not alive
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreenStack.cs
  osu.Framework/Input/InputManager.cs
Labels: input, resolves issue

#2157 Avoid stack-empty exception on private screen exitFrom calls
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreenStack.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: drawable

#2159 Make the float parses culture invariant.
  osu.Framework/Configuration/BindableMarginPadding.cs
Labels: testing

#2164 Add tests for clocks
  osu.Framework.Tests/Visual/TestCaseClocks/LaggyFramedClock.cs
  osu.Framework.Tests/Visual/TestCaseClocks/TestCaseClock.cs
  osu.Framework.Tests/Visual/TestCaseClocks/TestCaseClocks.cs
  osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs
  osu.Framework/Timing/FramedClock.cs
  osu.Framework/Timing/ISourceChangeableClock.cs
  osu.Framework/Timing/InterpolatingFramedClock.cs
Labels: testing

#2163 Add rider live templates
  osu-framework.sln.DotSettings
Labels: tooling

#2166 Fix interpolating clock going backwards
  osu.Framework.Tests/Clocks/DecoupleableClockTest.cs
  osu.Framework.Tests/Clocks/InterpolatingClockTest.cs
  osu.Framework.Tests/Clocks/TestClock.cs
  osu.Framework/Timing/InterpolatingFramedClock.cs
Labels: clocks

#2165 Rework GameHost/GameWindow IsActive state
  osu.Framework/Game.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKMouseHandler.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/GameWindow.cs
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/Threading/GameThread.cs
Labels: testing

#2012 Make ValueChanged give an EventArgs
  osu.Framework.Tests/Bindables/BindableBindingTest.cs
  osu.Framework.Tests/Dependencies/CachedModelDependenciesTest.cs
  osu.Framework.Tests/Visual/TestCaseBindableNumbers.cs
  osu.Framework.Tests/Visual/TestCaseContainer/TestCaseSafeArea.cs
  osu.Framework.Tests/Visual/TestCaseContainerExtensions/TestCaseFillFlowContainer.cs
  osu.Framework.Tests/Visual/TestCaseContainerExtensions/TestCaseSearchContainer.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseCheckboxes.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseSliderbar.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseWaveform.cs
  osu.Framework/Allocation/CachedModelDependencyContainer.cs
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Configuration/Bindable.cs
  osu.Framework/Configuration/IBindable.cs
  osu.Framework/Configuration/LeasedBindable.cs
  osu.Framework/Configuration/Tracking/TrackedSetting.cs
  osu.Framework/Configuration/ValueChangedEvent.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/UserInterface/BasicCheckbox.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
  osu.Framework/Graphics/UserInterface/TabItem.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
  osu.Framework/Input/Handlers/Keyboard/OsuTKKeyboardHandler.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKMouseHandler.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
  osu.Framework/Localisation/LocalisationManager.cs
  osu.Framework/Platform/DesktopGameWindow.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRateSection.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: bindable, proposal

#2043 Implement a FontUsage class, replacing simple font names
  osu.Framework.Tests/Visual/TestCaseBorderless.cs
  osu.Framework.Tests/Visual/TestCaseClocks/TestCaseClock.cs
  osu.Framework.Tests/Visual/TestCaseContainer/TestCaseMasking.cs
  osu.Framework.Tests/Visual/TestCaseContainerExtensions/TestCaseCachedBufferedContainer.cs
  osu.Framework.Tests/Visual/TestCaseContainerExtensions/TestCaseFillModes.cs
  osu.Framework.Tests/Visual/TestCaseContainerExtensions/TestCaseSearchContainer.cs
  osu.Framework.Tests/Visual/TestCaseDrawable/TestCaseColourGradient.cs
  osu.Framework.Tests/Visual/TestCaseDrawable/TestCaseDrawableLoadCancellation.cs
  osu.Framework.Tests/Visual/TestCaseDrawable/TestCaseEffects.cs
  osu.Framework.Tests/Visual/TestCaseDrawable/TestCaseHollowEdgeEffect.cs
  osu.Framework.Tests/Visual/TestCaseDrawable/TestCaseTransformRewinding.cs
  osu.Framework.Tests/Visual/TestCaseDrawable/TestCaseTransformSequence.cs
  osu.Framework.Tests/Visual/TestCaseInput/TestCaseInputManager.cs
  osu.Framework.Tests/Visual/TestCaseInput/TestCaseInputResampler.cs
  osu.Framework.Tests/Visual/TestCaseInput/TestCaseKeyBindings.cs
  osu.Framework.Tests/Visual/TestCaseInput/TestCaseMouseStates.cs
  osu.Framework.Tests/Visual/TestCaseLifetimeManagementContainer.cs
  osu.Framework.Tests/Visual/TestCasePathApproximator.cs
  osu.Framework.Tests/Visual/TestCaseSprites/TestCaseSmoothedEdges.cs
  osu.Framework.Tests/Visual/TestCaseSprites/TestCaseSpriteText.cs
  osu.Framework.Tests/Visual/TestCaseSprites/TestCaseSpriteTextPresence.cs
  osu.Framework.Tests/Visual/TestCaseSprites/TestCaseSpriteTextScenarios.cs
  osu.Framework.Tests/Visual/TestCaseSprites/TestCaseTextFlow.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseCountingText.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseDrawablePath.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreenStack.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs
  osu.Framework/Graphics/Containers/Markdown/NotImplementedMarkdown.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Graphics/Sprites/FontUsage.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/UserInterface/BasicTabControl.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs
  osu.Framework/Testing/Drawables/Steps/StepButton.cs
  osu.Framework/Testing/Drawables/TestCaseButton.cs
  osu.Framework/Testing/Drawables/TestCaseHeaderButton.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: resolves issue

#2152 Remove implicit operator from bindables
  osu.Framework.Tests/Visual/TestCaseContainerExtensions/TestCaseFillFlowContainer.cs
  osu.Framework.Tests/Visual/TestCaseDrawable/TestCaseBlending.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseDropdownBox.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseSliderbar.cs
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Audio/Track/TrackVirtual.cs
  osu.Framework/Configuration/Bindable.cs
  osu.Framework/Configuration/BindableBool.cs
  osu.Framework/Configuration/BindableMarginPadding.cs
  osu.Framework/Configuration/BindableNumber.cs
  osu.Framework/Configuration/BindableSize.cs
  osu.Framework/Graphics/UserInterface/Checkbox.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Platform/DesktopGameWindow.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs
Labels: resolves issue

#2170 Move variable local
  osu.Framework/Allocation/CachedModelDependencyContainer.cs
Labels: code quality

#2171 args -> e for ValueChangedEvent usages
  osu.Framework.Tests/Dependencies/CachedModelDependenciesTest.cs
  osu.Framework.Tests/Visual/TestCaseBindableNumbers.cs
  osu.Framework.Tests/Visual/TestCaseContainer/TestCaseSafeArea.cs
  osu.Framework.Tests/Visual/TestCaseContainerExtensions/TestCaseFillFlowContainer.cs
  osu.Framework.Tests/Visual/TestCaseContainerExtensions/TestCaseSearchContainer.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseCheckboxes.cs
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseWaveform.cs
  osu.Framework/Allocation/CachedModelDependencyContainer.cs
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/UserInterface/BasicCheckbox.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
  osu.Framework/Input/Handlers/Keyboard/OsuTKKeyboardHandler.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKMouseHandler.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
  osu.Framework/Platform/DesktopGameWindow.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRateSection.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: code quality

#2173 Add cursor to ManualInputManager for visual reference in tests
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseNestedMenus.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: testing

#2174 Fix SliderBar trying to change bindable values when not the target
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseSliderBar.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
Labels: resolves issue

#2160 Implement a cake buildscript for testing and building osu.Framework
  .gitignore
  .vscode/launch.json
  appveyor.yml
  appveyor_deploy.yml
  appveyor_native_deploy.yml
  build.ps1
  build.sh
  build/build.cake
  build/cakebuild.csproj
  cake.config
  osu.Framework.Tests/IO/TestWebRequest.cs
Labels: testing

#2178 Revert some more instances of 'e' variable names
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Platform/GameHost.cs
Labels: code quality

#2181 Fix interpolating clock not seeking backwards correctly
  osu.Framework.Tests/Clocks/InterpolatingClockTest.cs
  osu.Framework/Timing/InterpolatingFramedClock.cs
Labels: clocks, regression

#2182 Revert to the old version number style
  appveyor.yml
Labels: tooling

#2184 Use ArgumentNullException instead of NullReferenceException
  osu.Framework/Threading/Scheduler.cs
Labels: code quality

#2179 Throw InvalidCastException on retrieving a bindable from ConfigManage…
  osu.Framework/Configuration/ConfigManager.cs
Labels: resolves issue

#2185 Increase the documentation of RectangleF.
  osu.Framework/Graphics/Primitives/RectangleF.cs
Labels: code quality, documentation

#2187 Attempt to add iOS solution inspections
  build/build.cake
Labels: testing

#2197 Revert iOS inspections
  build/build.cake
Labels: tooling

#2201 Fix ScreenStack.Push behaving incorrectly when screen already present
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseScreenStack.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: drawable

#2191 Add a bindable for supported window modes per platform
  osu.Framework.Tests/Visual/TestCaseFullscreen.cs
  osu.Framework.iOS/IOSGameWindow.cs
  osu.Framework/Platform/DesktopGameWindow.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/GameWindow.cs
  osu.Framework/Platform/MacOS/MacOSGameWindow.cs
Labels: graphics

#2196 Add documentation to the Checkbox and BasicCheckbox classes.
  osu.Framework/Graphics/UserInterface/BasicCheckbox.cs
  osu.Framework/Graphics/UserInterface/Checkbox.cs
Labels: documentation

#2190 Add ability to populate a Dropdown from a BindableList
  osu.Framework.Tests/Visual/TestCaseUserInterface/TestCaseDropdownBox.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
Labels: drawable, user interface
