Repository ppy/osu-framework, pull requests merged in 2019-05, with the labels that each got.

#2386 Add parts of the new testbrowser toolbar's record section design
  osu.Framework/Testing/Drawables/Sections/ToolbarAssemblySection.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarRecordSection.cs
  osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
Labels: testing

#2387 Fix AoT crashes on iOS when rapidly creating callbacks
  osu.Framework/Allocation/ObjectHandle.cs
  osu.Framework/Audio/Callbacks/FileCallbacks.cs
  osu.Framework/Audio/Callbacks/SyncCallback.cs
Labels: iOS

#2389 Fix colour issue
  osu.Framework/Graphics/Lines/Path_DrawNode.cs
Labels: resolves issue

#2391 Add linear/srgb colour tests
  osu.Framework.Tests/Visual/Drawables/TestCaseColourGradient.cs
Labels: testing

#2145 Add truncation support to SpriteText
  osu.Framework.Tests/Visual/Sprites/TestCaseSpriteTextTruncate.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: drawable, overdue

#2393 Delay instant DelayedLoadWrapper intersection computation
  osu.Framework.Tests/Visual/Drawables/TestCaseDelayedLoad.cs
  osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
Labels: drawable

#2369 Prevent MakeCurrent from incorrectly exiting screens
  osu.Framework.Tests/Visual/UserInterface/TestCaseScreenStack.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: resolves issue, screen

#2400 Remove now-unnecessary custom comparer
  osu.Framework/Allocation/DependencyContainer.cs
Labels: performance

#2401 Make SearchContainer re-filter after new child is added
  osu.Framework.Tests/Visual/UserInterface/TestCaseSearchContainer.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
Labels: bug, code quality, testing

#2403 Fix markdown code block escaping
  osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdown.cs
  osu.Framework/Graphics/Containers/CustomizableTextContainer.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownFencedCodeBlock.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs
Labels: bug, drawable

#2412 Add enumerator to reduce WeakList allocations
  osu.Framework.Tests/Bindables/BindableBindingTest.cs
  osu.Framework.Tests/Lists/TestWeakList.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/BindableList.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Lists/LockedWeakList.cs
  osu.Framework/Lists/WeakList.cs
Labels: bindable, performance

#2405 Don't restart track when calling Start() at track's end
  osu.Framework.Tests/Platform/TrackBassTest.cs
  osu.Framework/Audio/Track/TrackBass.cs
Labels: audio, resolves issue

#2410 Implement an async disposal queue
  osu.Framework.Tests/Threading/AsyncDisposalQueueTest.cs
  osu.Framework/Allocation/AsyncDisposalQueue.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: performance

#2413 Avoid concurrent queue overhead in Scheduler.AddDelayed usage
  osu.Framework/Threading/Scheduler.cs
Labels: performance

#2406 Fix SearchContainer not correctly using Cached
  osu.Framework.Tests/Visual/UserInterface/TestSceneSearchContainer.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
Labels: performance, regression

#2411 Use ArrayPool instead of custom BufferStack
  osu.Framework/Allocation/BufferStack.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSub.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Textures/ArrayPoolTextureUpload.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: performance

#2404 Allow MarkdownContainer to autosize on the Y axis
  osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdown.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
Labels: drawable

#2409 Remove TextFlowContainer usage in TestCaseVideoSprite to improve performance
  osu.Framework.Tests/Visual/Sprites/TestSceneVideoSprite.cs
Labels: performance, testing

#2418 Update NuGet packages
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/osu.Framework.csproj
Labels: libraries

#2415 Fix looping tracks not restarting
  osu.Framework.Tests/Platform/TrackBassTest.cs
  osu.Framework/Audio/Track/TrackBass.cs
Labels: audio, regression

#2416 Fix TrackBass.Seek() potentially incorrectly returning early
  osu.Framework.Tests/Platform/TrackBassTest.cs
  osu.Framework/Audio/Track/TrackBass.cs
Labels: audio, bug

#2417 Don't reset current time to 0 when track is stopped upon completion
  osu.Framework.Tests/Platform/TrackBassTest.cs
  osu.Framework/Audio/Track/TrackBass.cs
Labels: audio, proposal

#2419 Remove unused PreFrame and PostFrame functions
  osu.Framework/Game.cs
Labels: code quality

#2422 Optimise DependencyContainer lookups
  osu.Framework/Allocation/CacheInfo.cs
  osu.Framework/Allocation/DependencyContainer.cs
Labels: performance

#2421 Fix removing items from WeakList while iterating causing incorrect execution
  osu.Framework.Tests/Lists/TestWeakList.cs
  osu.Framework/Lists/WeakList.cs
Labels: bindable

#2425 Change TabItem.IsRemovable default to true
  osu.Framework/Graphics/UserInterface/BasicTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/UserInterface/TabItem.cs
Labels: user interface

#2432 Fix potential disposal race condition
  osu.Framework/Graphics/Drawable.cs
Labels: bug, drawable

#2426 Interpolation<T> searches for interpolation method inside the generic class
  osu.Framework.Tests/MathUtils/TestInterpolation.cs
  osu.Framework/Graphics/MarginPadding.cs
  osu.Framework/MathUtils/Interpolation.cs
  osu.Framework/Testing/Drawables/TestSceneHeaderButton.cs
Labels: resolves issue

#2428 Allow null selections in dropdowns
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/BasicDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/DropdownMenuItem.cs
Labels: user interface

#2429 Clean up TabControl test scene
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
Labels: code quality

#2430 Allow null selections in tab controls
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
Labels: user interface

#2431 Add support for multiline tab controls
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/UserInterface/TabItem.cs
Labels: user interface

#2433 Have TrackManager return null rather than exception on lookup failure
  osu.Framework/Audio/Track/TrackManager.cs
Labels: audio

#2434 Throw ArgumentNullExeception on same thread it was called
  osu.Framework/Audio/Track/TrackBass.cs
Labels: code quality

#2437 Refactor ModelBackedDrawable and improve testing
  osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawable.cs
  osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
Labels: resolves issue

#2442 Fix potential ModelBackedDrawable testcase failures
  osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawable.cs
Labels: testing

#2440 Fix caps lock on macOS
  osu.Framework/Input/GameWindowTextInput.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/MacOS/MacOSTextInput.cs
  osu.Framework/Platform/MacOS/Native/Cocoa.cs
Labels: input, macOS, resolves issue

#2446 Improve performance of various Line operations
  osu.Framework/Graphics/Primitives/Line.cs
Labels: performance

#2443 Add parsing support for nullable bindables
  osu.Framework.Tests/Bindables/BindableEnumTest.cs
  osu.Framework/Bindables/Bindable.cs
Labels: bindable

#2445 Add AggregateBindable implementation
  osu.Framework.Tests/Bindables/AggregateBindableTest.cs
  osu.Framework/Bindables/AggregateBindable.cs
Labels: bindable

#2450 Adjust assertions for testing safety
  osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawable.cs
Labels: testing

#2452 Make TrackManager implement IResourceStore
  osu.Framework/Audio/Track/TrackManager.cs
Labels: audio

#2447 Use aggregate bindable in AdjustableAudioComponent
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioCollectionManager.cs
  osu.Framework/Audio/AudioComponent.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Audio/Track/TrackBass.cs
Labels: audio, code quality

#2449 Move audio adjustment logic to separate class
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioAdjustments.cs
  osu.Framework/Audio/IAggregateAudioAdjustment.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
  osu.Framework/Audio/Track/TrackBass.cs
Labels: audio

#2451 Add interfaces for audio components
  osu.Framework/Audio/Sample/ISampleChannel.cs
  osu.Framework/Audio/Sample/SampleChannel.cs
  osu.Framework/Audio/Track/ITrack.cs
  osu.Framework/Audio/Track/Track.cs
Labels: audio, code quality

#2456 Fix potential thread safety issues with AggregateBindable
  osu.Framework/Bindables/AggregateBindable.cs
Labels: resolves issue

#2453 Rename sample/track managers to stores
  osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioCollectionManager.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/IAdjustableAudioComponent.cs
  osu.Framework/Audio/IAdjustableResourceStore.cs
  osu.Framework/Audio/Sample/SampleStore.cs
  osu.Framework/Audio/Track/TrackStore.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: audio, code quality, proposal

#2464 Use IResourceStore for TextureLoaderStore instead of ResourceStore
  osu.Framework/Graphics/Textures/TextureLoaderStore.cs
Labels: resolves issue

#2444 Add a method to retrieve a list of available resources for IResourceStores
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework.Tests/Visual/Platform/TestSceneResourceStores.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextScenarios.cs
  osu.Framework/Audio/Sample/SampleStore.cs
  osu.Framework/Audio/Track/TrackStore.cs
  osu.Framework/Graphics/Textures/TextureLoaderStore.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/IO/Stores/DllResourceStore.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/IResourceStore.cs
  osu.Framework/IO/Stores/NamespacedResourceStore.cs
  osu.Framework/IO/Stores/OnlineStore.cs
  osu.Framework/IO/Stores/ResourceStore.cs
  osu.Framework/IO/Stores/StorageBackedResourceStore.cs
Labels: resolves issue
