Repository ppy/osu-framework, pull requests merged in 2020-04, with the labels that each got.

#3416 Fix freeze (and failure to exit) when exception is thrown in single threaded mode
  osu.Framework/Platform/GameHost.cs
Labels: area:threading, size/XS

#3408 Fix more edge cases in TextureAtlas
  osu.Framework.Tests/Graphics/TextureAtlasTest.cs
  osu.Framework/Graphics/Textures/TextureAtlas.cs
Labels: area:graphics, size/M

#3415 Rename classes that sound like they are test scenes
  osu.Framework/Testing/Drawables/TestButton.cs
  osu.Framework/Testing/Drawables/TestButtonBase.cs
  osu.Framework/Testing/Drawables/TestGroupButton.cs
  osu.Framework/Testing/Drawables/TestSubButton.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: size/S, type:code-quality

#3417 Fix first sprite on new atlas page overlapping white pixel
  osu.Framework.Tests/Graphics/TextureAtlasTest.cs
  osu.Framework/Graphics/Textures/TextureAtlas.cs
Labels: area:graphics, size/M

#3419 Ensure animation starts at zero if stopped before load complete
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework/Graphics/Animations/Animation.cs
Labels: area:drawable, size/S

#3421 Apply process frame fix to VideoSprite
  osu.Framework/Graphics/Video/VideoSprite.cs
Labels: size/XS

#3418 Fix transforms being applied on an animation from a parent's LoadComplete occurring at an incorrect point in time
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework/Graphics/Animations/Animation.cs
  osu.Framework/Graphics/Video/VideoSprite.cs
Labels: area:drawable, size/S

#3420 Ensure animation starts at correct frame/time if seeked+stopped to frame before load complete
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework/Graphics/Animations/Animation.cs
Labels: area:drawable, size/M

#3422 Fix animations incorrectly processing a parent clock
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs
  osu.Framework/Graphics/Animations/Animation.cs
  osu.Framework/Graphics/Animations/AnimationClockComposite.cs
  osu.Framework/Graphics/Animations/DrawableAnimation.cs
  osu.Framework/Graphics/Animations/FramedAnimationExtensions.cs
  osu.Framework/Graphics/Animations/IAnimation.cs
  osu.Framework/Graphics/Animations/IFramedAnimation.cs
  osu.Framework/Graphics/Animations/TextureAnimation.cs
  osu.Framework/Graphics/Video/Video.cs
  osu.Framework/Graphics/Video/VideoSprite.cs
  osu.Framework/Graphics/Video/VideoSpriteDrawNode.cs
  osu.Framework/Timing/FramedClock.cs
  osu.Framework/Timing/FramedOffsetClock.cs
Labels: area:drawable, size/XL

#3423 Fix blending not working through multiple parents
  osu.Framework.Tests/Visual/Drawables/TestSceneBlending.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneComplexBlending.cs
  osu.Framework/Graphics/Drawable.cs
Labels: area:graphics, size/XL

#3424 Remove left over logging
  osu.Framework/Graphics/Animations/Animation.cs
Labels: size/XS

#3425 Fix PrintWithSiSuffix handling large negative numbers incorrectly
  osu.Framework/Utils/NumberFormatter.cs
Labels: size/XS

#3428 Add temporary blending "fix" for BufferedContainer
  osu.Framework/Graphics/Containers/BufferedContainer.cs
Labels: area:graphics, size/S

#3426 Share layout logic between Animation and Video
  osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneVideoLayout.cs
  osu.Framework.Tests/Visual/Sprites/TestVideo.cs
  osu.Framework/Graphics/Animations/Animation.cs
  osu.Framework/Graphics/Animations/AnimationClockComposite.cs
  osu.Framework/Graphics/Animations/CustomisableSizeCompositeDrawable.cs
  osu.Framework/Graphics/Animations/DrawableAnimation.cs
  osu.Framework/Graphics/Animations/TextureAnimation.cs
  osu.Framework/Graphics/Video/Video.cs
Labels: area:drawable, size/L

#3432 Fix base call in Video
  osu.Framework/Graphics/Video/Video.cs
Labels: size/XS

#3434 Include base test scene types in dynamic compilation
  osu.Framework/Testing/DynamicClassCompiler.cs
Labels: size/XS, type:testing

#3435 Transfer FillAspectRatio outwards to fix Animation/Video fill modes scaling incorrectly
  osu.Framework.Tests/Visual/Sprites/TestSceneVideoLayout.cs
  osu.Framework/Graphics/Animations/CustomisableSizeCompositeDrawable.cs
  osu.Framework/Graphics/Animations/DrawableAnimation.cs
  osu.Framework/Graphics/Animations/TextureAnimation.cs
  osu.Framework/Graphics/Video/Video.cs
Labels: area:drawable, size/S

#3436 Expose original instance for dynamic compilation
  osu.Framework/Testing/DynamicClassCompiler.cs
  osu.Framework/Testing/IDynamicallyCompile.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestScene.cs
Labels: size/M, type:testing

#3437 Fix DynamicCompilationOriginal being null under nUnit
  osu.Framework/Testing/TestScene.cs
Labels: size/XS, type:testing

#3439 Fix position causing parent size invalidations
  osu.Framework.Tests/Layout/TestSceneContainerLayout.cs
  osu.Framework/Graphics/Drawable.cs
Labels: area:layout, size/M, type:performance

#3440 Ensure no flattening for custom composite drawnodes
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: area:drawable, size/S

#3441 Add undo/redo platform actions
  osu.Framework/Input/PlatformActionContainer.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
Labels: area:input, size/S

#3443 Never propagate DrawNode invalidations
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
Labels: area:layout, size/XS, type:performance

#3445 Remove atomic invalidation counter
  osu.Framework/Graphics/Drawable.cs
Labels: area:drawable, size/XS, type:code-quality

#3442 Don't invalidate non-alive children when not required
  osu.Framework.Benchmarks/BenchmarkInvalidationWithManyNotAlive.cs
  osu.Framework.Benchmarks/BenchmarkMakeChildAlive.cs
  osu.Framework.Benchmarks/BenchmarkSpinningParentWithManyAlive.cs
  osu.Framework.Tests/Layout/TestSceneContainerLayout.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/InvalidationList.cs
Labels: area:layout, size/L, type:performance

#3444 Optimise conservative draw quad computations
  osu.Framework.Benchmarks/BenchmarkSpinningParentWithManyAlive.cs
  osu.Framework/Graphics/Shapes/Box.cs
Labels: area:layout, size/L, type:performance

#3446 Fix edge effect exception happening one frame too late
  osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
Labels: size/XS, type:code-quality

#3302 Expose some ScrollContainer members as public
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: size/M

#3457 Fix dead children potentially not being removed
  osu.Framework.Tests/Containers/TestSceneContainerState.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: area:drawable, size/M

#3458 Add template projects to sln
  osu-framework.sln
Labels: dependencies, size/M

#3459 Fix BasicTabControl not working by default
  osu.Framework/Graphics/UserInterface/BasicTabControl.cs
Labels: size/S

#3478 Remove obsolete comparison comparer
  osu.Framework/Lists/ComparisonComparer.cs
Labels: size/S, type:code-quality

#3480 Disable blending in front-to-back pass
  osu.Framework/Graphics/DrawNode.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:graphics, size/XS, type:performance

#3481 Fix dynamic compilation potentially including files from wrong namespace
  osu.Framework/Testing/DynamicClassCompiler.cs
Labels: size/M, type:testing

#3485 Fix animation not ignoring time during pause
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework/Graphics/Animations/AnimationClockComposite.cs
Labels: area:drawable, size/S

#3427 Expose displays as bindables through IWindow
  osu.Framework.Android/AndroidGameWindow.cs
  osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
  osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
  osu.Framework.iOS/IOSGameWindow.cs
  osu.Framework/Platform/DesktopGameWindow.cs
  osu.Framework/Platform/Display.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/GameWindow.cs
  osu.Framework/Platform/IWindow.cs
  osu.Framework/Platform/IWindowBackend.cs
  osu.Framework/Platform/Sdl2WindowBackend.cs
  osu.Framework/Platform/Window.cs
  osu.Framework/Threading/Scheduler.cs
Labels: size/L

#3486 Add tree connection lines to make draw visualiser easier to visually parse
  osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
Labels: area:tooling, size/M

#3482 Remove obsoleted RuntimeInfo properties.
  osu.Framework/RuntimeInfo.cs
Labels: size/XS

#3496 Fix samples occasionally playing before volume adjustment can be applied
  osu.Framework/Audio/Sample/SampleChannelBass.cs
Labels: area:audio, size/XS
