Repository ppy/osu-framework, pull requests merged in 2020-07, with the labels that each got.

#3669 Schedule lifetime change callbacks after children
  osu.Framework.Tests/Visual/Containers/TestSceneLifetimeManagementContainer.cs
  osu.Framework/Graphics/Containers/LifetimeManagementContainer.cs
Labels: area:drawable, size/M

#3671 Add method to provide custom game storage
  osu.Framework/Game.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:storage, size/S

#3677 Fix bad LOD levels chosen on some Intel drivers
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
Labels: area:graphics, size/S

#3662 Decouple producing touch input on events from syncing with parent state
  osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
  osu.Framework/Input/PassThroughInputManager.cs
Labels: area:input, size/S

#3664 Add proper android touch action handler support
  osu.Framework.Android/Input/AndroidTouchHandler.cs
Labels: area:input, platform:android, size/M

#3679 Add iOS multitouch support
  osu.Framework.iOS/Input/IOSTouchHandler.cs
Labels: area:input, platform:iOS, size/L

#3678 Fix ScrollContainers accepting right-click drags on their scrollbars
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: area:UI, size/XS

#3682 Fix volatile usage warnings in AsyncBufferStream
  osu.Framework/IO/AsyncBufferStream.cs
Labels: size/XS, type:code-quality

#3684 Fix video decoding memory leaks
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: area:graphics, size/S, type:performance

#3690 Fix incorrect font specification for StepSlider
  osu.Framework/Testing/Drawables/Steps/StepSlider.cs
Labels: area:UI, size/XS, type:testing

#3640 Merge text addition logic into one single method
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: area:UI, size/M, type:code-quality

#3680 Add option to disable TabControl switch-on-remove behaviour
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
Labels: area:UI, size/L

#3670 Make OnTouchMove() return void instead of bool
  osu.Framework.Tests/Visual/Input/TestSceneTouchVisualiser.cs
  osu.Framework/Graphics/Drawable.cs
Labels: area:input, size/S

#3641 Allow deleting multiple text characters at once
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: area:UX, size/M, type:code-quality

#3689 Add MIDI input handling to passthrough input manager
  osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Input/StateChanges/MidiKeyInput.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: area:input, size/M

#3691 Improve robustness of MIDI event parsing
  osu.Framework/Input/Handlers/Midi/MidiInputHandler.cs
Labels: area:input, size/M

#3695 Fix font load exceptions potentially crashing the game
  osu.Framework/IO/Stores/FontStore.cs
Labels: size/XS, type:reliability

#3688 Map mouse input to new / moved touches instead of only first
  osu.Framework.Tests/Visual/Input/TestSceneTouchInput.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Input/StateChanges/Events/TouchStateChangeEvent.cs
  osu.Framework/Input/TouchSource.cs
Labels: area:input, size/L

#3701 Fix potential disposal deadlock in DelayedLoadUnloadWrapper
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
Labels: area:drawable, size/S

#3699 Fix RearrangeableListContainer attempting to async load children before loaded
  osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
  osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
Labels: area:drawable, size/S, type:reliability

#3289 Add TextBox event handlers
  osu.Framework/Graphics/UserInterface/BasicTextBox.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: area:UI, size/M

#3705 Disallow non-readonly fields in CachedModelDependencyContainer
  osu.Framework.Tests/Dependencies/CachedModelDependenciesTest.cs
  osu.Framework/Allocation/CachedModelDependencyContainer.cs
Labels: area:dependency-injection, size/M

#3706 Add the ability to disable the ManualInputManager cursor guide
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: size/S, type:testing

#3681 Add DrawablePool for avoiding allocation overhead of drawables
  osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs
  osu.Framework/Graphics/Pooling/DrawablePool.cs
  osu.Framework/Graphics/Pooling/IDrawablePool.cs
  osu.Framework/Graphics/Pooling/PoolableDrawable.cs
Labels: area:drawable, size/XL, type:performance

#3290 Remove all audio-related logic from TextBox
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: area:UI, size/S

#3707 Fix potential duplicate items in RearrangeableListContainer
  osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
  osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
Labels: area:drawable, size/M

#3711 Add property to allow sliderbar to handle input outside of its own hover area
  osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
Labels: area:UI, size/M

#3715 Fix seeking animation not consuming clock
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework/Graphics/Animations/AnimationClockComposite.cs
Labels: area:drawable, size/S

#3717 Fix exception when getting pooled drawables too early
  osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs
  osu.Framework/Graphics/Pooling/DrawablePool.cs
Labels: area:drawable, size/S

#3714 Fix unit tests under Rider 2020.2 EAP6
  osu.Framework/Development/DebugUtils.cs
Labels: size/XS, type:testing

#3718 Fix memory leak when retrieving stack traces
  osu.Framework/Statistics/BackgroundStackTraceCollector.cs
Labels: size/S, type:performance

#3716 Fix exception when adding loaded drawable to unloaded parent
  osu.Framework.Tests/Containers/TestSceneContainerState.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: area:drawable, size/M

#3720 Upload textures after clearing backbuffer
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: area:graphics, size/M

#3721 Always make the graphics context current on the draw thread
  osu.Framework/Threading/DrawThread.cs
Labels: area:graphics, size/XS

#3726 Add function in ManualInputManager to press and release a key
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: size/S, type:testing

#3728 Disable dynamic compilation with debugger attached
  osu.Framework/Testing/DynamicClassCompiler.cs
Labels: size/S, type:testing

#3730 Ensure nUnit runs with correct CurrentDirectory
  osu-framework.sln.DotSettings
Labels: size/XS, type:testing

#3749 Use ConcurrentQueue.Clear instead of TryDequeue loop in FrameStatisticsDisplay
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Labels: size/XS, type:code-quality

#3738 Fix hard crash if PerformanceOverlay is toggled before loaded
  osu.Framework/Graphics/Performance/PerformanceOverlay.cs
Labels: size/M, type:reliability

#3737 Reduce allocations caused by DepthValue
  osu.Framework/Graphics/OpenGL/DepthValue.cs
  osu.Framework/Platform/GameHost.cs
Labels: size/S, type:performance

#3741 Remove linq allocation on GlobalStatistics.Clear
  osu.Framework/Statistics/GlobalStatistics.cs
Labels: size/XS, type:performance

#3742 Fix LINQ allocations in focusTopMostRequestingDrawable
  osu.Framework/Input/InputManager.cs
Labels: size/S, type:performance

#3736 Fix excessive list allocation in GetPendingInputs paths
  osu.Framework/Input/Handlers/InputHandler.cs
  osu.Framework/Input/InputManager.cs
Labels: size/S, type:performance

#3732 Remove array allocations in BassAmplitudeProcessor by removing consistency guarantee
  osu.Framework/Audio/BassAmplitudeProcessor.cs
Labels: size/XS, type:performance

#3734 Fix delegate allocation in DrawFrameRecordingContainer
  osu.Framework/Testing/DrawFrameRecordingContainer.cs
Labels: size/XS, type:performance

#3735 Fix delegate allocation in PropagateBlockableEvent
  osu.Framework/Input/InputManager.cs
Labels: size/S, type:performance

#3729 Add marker interface and store source of last change to MouseState
  osu.Framework.Tests/Visual/Input/TestSceneTouchInput.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/StateChanges/ISourcedFromTouch.cs
  osu.Framework/Input/StateChanges/MouseButtonInputFromTouch.cs
  osu.Framework/Input/StateChanges/MousePositionAbsoluteInput.cs
  osu.Framework/Input/StateChanges/MousePositionAbsoluteInputFromTouch.cs
  osu.Framework/Input/StateChanges/MousePositionRelativeInput.cs
  osu.Framework/Input/StateChanges/MouseScrollRelativeInput.cs
  osu.Framework/Input/States/MouseState.cs
Labels: area:input, size/L

#3752 Add filtering mode to LargeTextureStore
  osu.Framework/Graphics/Textures/LargeTextureStore.cs
Labels: area:graphics, size/XS

#3753 Add wrapper to create a slim read-only list
  osu.Framework.Benchmarks/BenchmarkSlimReadOnlyCollection.cs
  osu.Framework/Extensions/ListExtensions/ListExtensions.cs
  osu.Framework/Lists/SlimReadOnlyListWrapper.cs
Labels: size/L, type:performance

#3739 Fix CursorEffectContainer allocating excessively
  osu.Framework/Graphics/Cursor/CursorEffectContainer.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
  osu.Framework/Input/InputManager.cs
Labels: blocked, size/M, type:performance

#3743 Fix LINQ / List alllocations in PropagateBlockableEvent
  osu.Framework/Input/InputManager.cs
Labels: size/S, type:performance

#3754 Update osuTK dependency
  osu.Framework/osu.Framework.csproj
Labels: dependencies, size/XS

#3755 Fix last mouse input source not updated for mouse buttons inputs
  osu.Framework.Tests/Visual/Input/TestSceneTouchInput.cs
  osu.Framework/Input/StateChanges/MouseButtonInput.cs
Labels: size/M

#3740 Fix TooltipContainer allocating excessively
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
Labels: size/M, type:performance

#3747 Avoid comparing buttons when there is guaranteed to be no difference
  osu.Framework/Input/StateChanges/ButtonInput.cs
  osu.Framework/Input/States/ButtonStates.cs
Labels: size/M, type:performance

#3748 Avoid using LINQ to calculate button differences
  osu.Framework/Input/States/ButtonStates.cs
Labels: size/S, type:performance

#3758 Remove HashSet enumeration via static readonly
  osu.Framework/Input/States/ButtonStates.cs
Labels: size/S, type:performance

#3744 Fix Enumerable allocations from AvailableInputHandlers
  osu.Framework/Platform/GameHost.cs
Labels: size/XS, type:performance

#3746 Avoid allocating MouseMoveEvents for high frequency when not required
  osu.Framework/Input/InputManager.cs
Labels: size/S, type:performance

#3745 Fix input handler enumerable allocs
  osu.Framework/Input/CustomInputManager.cs
  osu.Framework/Input/Handlers/InputHandler.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/UserInputManager.cs
Labels: size/M, type:performance

#3760 Improve performance/reduce allocations in ButtonInput
  osu.Framework.Benchmarks/BenchmarkButtonInput.cs
  osu.Framework.Benchmarks/BenchmarkButtonStates.cs
  osu.Framework/Input/StateChanges/ButtonInput.cs
Labels: area:input, size/L, type:performance

#3767 Fix android screen suspension logic
  osu.Framework.Android/AndroidGameActivity.cs
Labels: size/XS

#3769 Fix sample potentially being left in a playing state due to threading
  osu.Framework.Tests/Audio/SampleBassTest.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
Labels: area:audio, area:threading, size/L

#3771 Update to latest Microsoft.Diagnostics.Runtime
  osu.Framework/Statistics/BackgroundStackTraceCollector.cs
  osu.Framework/osu.Framework.csproj
Labels: size/M, type:performance

#3774 Fix crash on disposing an already disposed sample
  osu.Framework/Audio/AudioComponent.cs
  osu.Framework/Audio/Sample/SampleChannel.cs
Labels: area:audio, size/XS
