Repository ppy/osu-framework, pull requests merged in 2020-09, with the labels that each got.

#3860 Fix Game.Dispose potentially ending before children have been (async) disposed
  osu.Framework.Tests/Platform/ComponentAsyncDisposalTest.cs
  osu.Framework.Tests/Platform/GameHostSuspendTest.cs
  osu.Framework.Tests/Threading/AsyncDisposalQueueTest.cs
  osu.Framework/Allocation/AsyncDisposalQueue.cs
  osu.Framework/Game.cs
Labels: area:drawable, size/L

#3864 Change disposal order to better protect against async disposal queue failures
  osu.Framework/Game.cs
Labels: size/XS, type:reliability

#3869 Fix default deadzones not set properly for idle axes
  osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
Labels: area:input, size/XS

#3868 Typo fixes & Math.Clamp
  osu.Framework.Android/AndroidGameActivity.cs
  osu.Framework.Android/Input/AndroidKeyboardHandler.cs
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/Elements/Bird.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
  osu.Framework/Audio/Track/Waveform.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Extensions/ObjectExtensions/ObjectExtensions.cs
  osu.Framework/Graphics/Containers/AudioContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/LifetimeManagementContainer.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
  osu.Framework/Graphics/Primitives/Line.cs
  osu.Framework/Graphics/Primitives/RectangleF.cs
  osu.Framework/Graphics/Transforms/TransformSequence.cs
  osu.Framework/Input/Bindings/InputKey.cs
  osu.Framework/Input/ButtonEventManager.cs
  osu.Framework/Input/Events/DoubleClickEvent.cs
  osu.Framework/Input/Events/DragEndEvent.cs
  osu.Framework/Input/Events/DragEvent.cs
  osu.Framework/Input/Events/DragStartEvent.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Platform/ThreadRunner.cs
  osu.Framework/Threading/Scheduler.cs
  osu.Framework/Utils/Blur.cs
Labels: size/M

#3865 Exclude entire files from dynamic compilation
  osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Labels: size/S, type:testing

#3870 Ensure ThreadedTaskScheduler eventually disposes
  osu.Framework.Tests/Threading/ThreadedTaskSchedulerTest.cs
  osu.Framework/Threading/ThreadedTaskScheduler.cs
Labels: size/M, type:reliability

#3692 Fix setting GridContainer content by index
  osu.Framework.Tests/Visual/Layout/TestSceneGridContainer.cs
  osu.Framework.Tests/Visual/Layout/TestSceneTableContainer.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/Containers/GridContainerContent.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownTable.cs
  osu.Framework/Lists/INotifyArrayChanged.cs
  osu.Framework/Lists/ObservableArray.cs
Labels: area:drawable, size/L

#3874 Update Windows BASS libraries
  osu.Framework.NativeLibs/runtimes/win-x64/native/bass.dll
  osu.Framework.NativeLibs/runtimes/win-x86/native/bass.dll
Labels: area:libraries, platform:windows

#3875 Add holotrack to projects listing in README
  README.md
Labels: size/XS

#3876 Add IWBTM to projects listing in README
  README.md
Labels: size/XS

#3877 Don't pack templates when requesting NativeLibs deploy
  build/build.cake
Labels: area:tooling, size/XS

#3878 Update NativeLibs and other dependencies
  osu.Framework/osu.Framework.csproj
Labels: dependencies, size/XS

#3882 Fix BasicTabControl not working
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/BasicDropdown.cs
  osu.Framework/Graphics/UserInterface/BasicTabControl.cs
Labels: area:UI, size/S

#3883 Add BindableList.BindCollectionChanged()
  osu.Framework.Tests/Bindables/BindableListTest.cs
  osu.Framework/Bindables/BindableList.cs
Labels: area:bindable, size/M

#3884 Remove type constraint for ChildrenOfType<T>
  osu.Framework/Testing/TestingExtensions.cs
Labels: size/XS, type:testing

#3885 Fix ChildrenOfType<> early exit for matching composite types
  osu.Framework.Tests/Visual/Testing/TestSceneTestingExtensions.cs
  osu.Framework/Testing/TestingExtensions.cs
Labels: size/M, type:testing

#3781 SDL fullscreen implementation
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Platform/DesktopWindow.cs
  osu.Framework/Platform/DisplayMode.cs
  osu.Framework/Platform/GameWindow.cs
  osu.Framework/Platform/PassthroughGraphicsBackend.cs
  osu.Framework/Platform/Sdl/Sdl2GraphicsBackend.cs
  osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
  osu.Framework/Platform/Window.cs
  osu.Framework/Platform/WindowBackend.cs
Labels: size/XL

#3890 Fix virtual track tempo propagation
  osu.Framework.Tests/Audio/TrackVirtualTest.cs
  osu.Framework/Audio/Track/TrackVirtual.cs
Labels: area:clocks, size/M

#3891 Update bass library with recent fixes
  osu.Framework.Android/arm64-v8a/libbass.so
  osu.Framework.Android/armeabi-v7a/libbass.so
  osu.Framework.Android/x86/libbass.so
  osu.Framework.NativeLibs/runtimes/linux-x64/native/libbass.so
  osu.Framework.NativeLibs/runtimes/linux-x86/native/libbass.so
  osu.Framework.NativeLibs/runtimes/osx-x64/native/libbass.dylib
  osu.Framework.NativeLibs/runtimes/win-x64/native/bass.dll
  osu.Framework.NativeLibs/runtimes/win-x86/native/bass.dll
  osu.Framework.iOS/libbass.a
Labels: dependencies

#3892 Update osuTK & NativeLibs libraries
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework/osu.Framework.csproj
Labels: area:libraries, size/S

#3897 Improve performance of drawable disposal
  osu.Framework/Graphics/Drawable.cs
Labels: area:drawable, size/XS, type:performance

#3893 Improve WeakList performance during staggered removals
  osu.Framework.Benchmarks/BenchmarkWeakList.cs
  osu.Framework/Lists/LockedWeakList.cs
  osu.Framework/Lists/WeakList.cs
  osu.Framework/Lists/WeakList_ValidItemsEnumerator.cs
Labels: area:bindable, size/L, type:performance

#3895 Reduce TextureStore lock contention
  osu.Framework/Graphics/Textures/LargeTextureStore.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
Labels: size/M, type:performance

#3896 Allow all types of steps to be considered setup steps
  osu.Framework.Tests/Visual/Testing/TestSceneTest.cs
  osu.Framework/Testing/Drawables/Steps/AssertButton.cs
  osu.Framework/Testing/Drawables/Steps/RepeatStepButton.cs
  osu.Framework/Testing/Drawables/Steps/SetUpStepButton.cs
  osu.Framework/Testing/Drawables/Steps/SingleStepButton.cs
  osu.Framework/Testing/Drawables/Steps/StepButton.cs
  osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestScene.cs
Labels: size/M, type:testing

#3898 Add more xmldoc to ManualInputManager hinting at press&release methods
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: size/S, type:documentation

#3889 Handle exit shortcut via platform action
  osu.Framework/Game.cs
  osu.Framework/Input/PlatformActionContainer.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/Platform/Windows/WindowsGameWindow.cs
Labels: area:platform, platform:windows, size/M

#3904 Remove unnecessary interpolation delegate members
  osu.Framework/Graphics/Transforms/TransformBindable.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
Labels: area:transformations, size/S, type:code-quality

#3903 Fix offset-based position transform not respecting previous transforms
  osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
  osu.Framework/Graphics/TransformableExtensions.cs
  osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
Labels: area:transformations, size/M

#3906 Add BindCollectionChanged to IBindableList interface
  osu.Framework/Bindables/IBindableList.cs
Labels: size/XS
