Repository ppy/osu-framework, pull requests merged in 2020-01, with the labels that each got.

#2908 Add desktop game template
  build/build.cake
  template-game/.template.config/template.json
  template-game/Directory.Build.props
  template-game/TemplateGame.Desktop.slnf
  template-game/TemplateGame.Desktop/Program.cs
  template-game/TemplateGame.Desktop/TemplateGame.Desktop.csproj
  template-game/TemplateGame.Desktop/app.manifest
  template-game/TemplateGame.Desktop/game.ico
  template-game/TemplateGame.Game.Tests/Program.cs
  template-game/TemplateGame.Game.Tests/TemplateGame.Game.Tests.csproj
  template-game/TemplateGame.Game.Tests/Visual/TestSceneTemplateGameGame.cs
  template-game/TemplateGame.Game/TemplateGame.Game.csproj
  template-game/TemplateGame.Game/TemplateGameGame.cs
  template-game/TemplateGame.Game/Testing/TemplateGameTestBrowser.cs
  template-game/TemplateGame.sln
  template-game/app.manifest
  template-game/osu.Framework.Template.csproj
Labels: tooling

#3021 Replace all MathHelper.Clamp usages with Math.Clamp
  osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Audio/Track/TrackVirtual.cs
  osu.Framework/Audio/Track/Waveform.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/Containers/SafeAreaContainer.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
  osu.Framework/Graphics/Cursor/ContextMenuContainer.cs
  osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/IO/AsyncBufferStream.cs
  osu.Framework/Platform/Windows/TimePeriod.cs
Labels: code quality, size/M

#3159 Remove redundant logic in Drawable
  osu.Framework/Graphics/Drawable.cs
Labels: code quality, size/S

#3162 Downgrade NUnit adapter to fix discovery issue
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework.Tests/osu.Framework.Tests.csproj
Labels: size/XS, testing

#3164 Disallow binding to already bound object
  osu.Framework.Tests/Bindables/BindableBindingTest.cs
  osu.Framework/Bindables/Bindable.cs
Labels: bindable, size/S

#3160 Fix ScrollBarVisible calling unsafe method before loaded
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: resolves issue, size/XS, user interface

#3013 Initial SDL2 window implementation
  osu-framework.sln.DotSettings
  osu.Framework.Android/AndroidGameHost.cs
  osu.Framework.Tests/Program.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework.iOS/Input/IOSTextInput.cs
  osu.Framework/Extensions/BridgingExtensions.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
  osu.Framework/Host.cs
  osu.Framework/Input/GameWindowTextInput.cs
  osu.Framework/Input/Handlers/Keyboard/KeyboardHandler.cs
  osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKMouseHandlerBase.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/IGraphicsBackend.cs
  osu.Framework/Platform/IWindowBackend.cs
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/PassthroughGraphicsBackend.cs
  osu.Framework/Platform/SDLWindow.cs
  osu.Framework/Platform/Sdl2Functions.cs
  osu.Framework/Platform/Sdl2WindowBackend.cs
  osu.Framework/Platform/Window.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/osu.Framework.csproj
Labels: graphics, size/XXL

#3165 Fix weak list incorrectly containing removed objects
  osu.Framework.Tests/Lists/TestWeakList.cs
  osu.Framework/Lists/WeakList.cs
Labels: bindable, size/M

#3166 Add weaklist benchmarks
  osu.Framework.Benchmarks/BenchmarkWeakList.cs
Labels: size/M, testing

#3167 Improve performance/allocations of WeakList
  osu.Framework.Benchmarks/BenchmarkWeakList.cs
  osu.Framework/Lists/WeakList.cs
Labels: performance, size/L

#3168 Minor cleanup
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/Lists/WeakList.cs
Labels: code quality, size/S

#3172 Add GDEdit the the projects listing
  README.md
Labels: size/XS

#3171 Fix text boxes crashing upon trying to delete words when empty
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: input, resolves issue, size/M, user interface

#3174 Update bass configuration in line with stable changes
  osu.Framework/Audio/AudioManager.cs
Labels: audio, size/S

#3178 Add Save operation to PlatformActions
  osu.Framework/Input/PlatformActionContainer.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
Labels: size/XS

#1745 Change dropdown selection using keyboard
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/DropdownHeader.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Input/PlatformActionContainer.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
Labels: input, user interface

#3181 Expose alive children from Container
  osu.Framework.Tests/Containers/TestSceneContainerState.cs
  osu.Framework/Graphics/Containers/Container.cs
Labels: drawable, size/M

#3182 Make tab control not change tabs when clicked in a disabled state
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/UserInterface/TabItem.cs
Labels: drawable, resolves issue, size/M

#3185 Make Bindable.Parse() support all .NET conversions
  osu.Framework.Tests/Bindables/BindableTest.cs
  osu.Framework/Bindables/Bindable.cs
Labels: bindable, size/M

#3186 Fix WebRequest.ProcessResponse xmldoc referencing wrong event
  osu.Framework/IO/Network/WebRequest.cs
Labels: documentation, size/XS

#3183 Make TabControl better return contained items
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
Labels: drawable, resolves issue, size/M

#3180 Rework DLW/DLUW to support general unloads and intersections
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
  osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
  osu.Framework/Graphics/Drawable.cs
Labels: drawable, memory, size/L

#3187 Return if BASS failed to initialize instead of throwing assert exception
  osu.Framework/Audio/AudioManager.cs
Labels: logging, size/XS

#3188 Fix binding leased to bindable potentially throwing exceptions
  osu.Framework.Tests/Bindables/BindableLeasingTest.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/LeasedBindable.cs
Labels: bindable, size/M

#3190 Make OnDrag, OnDragEnd, and OnMouseUp return void instead of bool
  osu.Framework.Tests/Visual/Audio/TestSceneSamples.cs
  osu.Framework.Tests/Visual/Audio/TestSceneTrackAdjustments.cs
  osu.Framework.Tests/Visual/Containers/TestScenePadding.cs
  osu.Framework.Tests/Visual/Containers/TestSceneSizing.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs
  osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs
  osu.Framework.Tests/Visual/Input/TestSceneInputResampler.cs
  osu.Framework.Tests/Visual/Input/TestSceneMouseStates.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneBufferedContainerView.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneTriangles.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Graphics/Visualisation/TitleBar.cs
  osu.Framework/Testing/Drawables/Steps/StepSlider.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: input, size/L

#3191 Abstract general implementation of button event managers
  osu.Framework/Input/ButtonEventManager.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/MouseButtonEventManager.cs
Labels: input, size/L

#3194 Implement per-button joystick input handling
  osu.Framework.Tests/Input/JoystickInputTest.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/JoystickButtonEventManager.cs
Labels: input, size/L

#3192 Implement per-key keyboard input handling
  osu.Framework.Tests/Input/KeyboardInputTest.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/KeyEventManager.cs
Labels: input, size/L

#3189 Update license year
  Directory.Build.props
  LICENCE
Labels: size/XS

#3193 Make OnKeyUp return void instead of bool
  osu.Framework.Tests/Input/KeybindingInputTest.cs
  osu.Framework.Tests/Input/KeyboardInputTest.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
Labels: input, size/XL

#3195 Make OnJoystickRelease return void instead of bool
  osu.Framework.Tests/Input/JoystickInputTest.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
  osu.Framework.Tests/Visual/Input/TestSceneJoystick.cs
  osu.Framework/Graphics/Drawable.cs
Labels: input, size/L

#3199 Make IKeyBindingHandler<T>.OnRelease return void instead of bool
  osu.Framework.Tests/Input/KeybindingInputTest.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingInputQueueChange.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs
  osu.Framework/Game.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/DropdownHeader.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Input/Bindings/IKeyBindingHandler.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: input, size/L

#3200 Merge pull request #3200 from smoogipoo/fix-bindable-warning
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/LeasedBindable.cs
Labels: size/XS, tooling

#3196 Reorder text box characters depth after removal action
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: input, size/L, user interface

#3202 Refactor + add xmldocs to drawable input methods
  osu.Framework/Graphics/Drawable.cs
Labels: documentation, input, size/L

#3203 Allow using F11 to toggle fullscreen
  osu.Framework/Input/FrameworkActionContainer.cs
Labels: input, resolves issue, size/XS

#3204 Fix ManualInputManager's initial cursor position not being deterministic
  osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
  osu.Framework.Tests/Visual/Input/TestSceneInputQueueChange.cs
  osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneButton.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneNestedMenus.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Testing/ManualInputManagerTestScene.cs
  osu.Framework/Testing/MenuTestScene.cs
Labels: size/XS

#3205 Fix incorrect setup order during visual tests
  osu.Framework/Testing/TestBrowser.cs
Labels: size/S, testing

#3206 Fix ScrollContainer null-reference on key repeat
  osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: input, size/M

#3207 Remove remaining osuTK.MathHelper usages and an unused member in TextureAtlas
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/Textures/TextureAtlas.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
Labels: size/S

#3208 Fix typo in InputManager method
  osu.Framework/Input/InputManager.cs
Labels: size/XS

#3209 Make OnKeyDown() repeats only occur on still-valid Drawables
  osu.Framework.Tests/Input/KeyboardInputTest.cs
  osu.Framework.Tests/Input/MouseInputTest.cs
  osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Input/KeyEventManager.cs
Labels: input, size/L

#3211 Change default method style for better IDE autocompletion
  .editorconfig
  osu-framework.sln.DotSettings
Labels: size/XS

#3217 Add ability to lookup a screen's parent via extension method
  osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
  osu.Framework/Screens/IScreen.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: screen, size/S

#3219 Fix headless tests generating sound output
  osu.Framework/Platform/HeadlessGameHost.cs
Labels: size/XS, testing

#3220 Add the ability to add teardown steps to test scenes
  osu.Framework.Tests/Visual/Testing/TestSceneDerivedTest.cs
  osu.Framework.Tests/Visual/Testing/TestSceneTest.cs
  osu.Framework/Testing/TearDownStepsAttribute.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestScene.cs
Labels: size/M, testing

#3221 Remove any common test method prefix in test browser display
  osu.Framework/Testing/TestBrowser.cs
Labels: size/S, testing

#3225 Only trim test from test methods
  osu.Framework/Testing/TestBrowser.cs
Labels: size/S
