Repository ppy/osu-framework, pull requests merged in 2020-03, with the labels that each got.

#3307 Rework invalidations game-wide to fix subtle layout issues
  osu.Framework.Tests/Layout/ContainerLayout/TestSceneContainerLayout.cs
  osu.Framework.Tests/Layout/DrawableLayout/TestSceneDrawableLayout.cs
  osu.Framework.Tests/Layout/GridContainerLayout/TestSceneGridContainerLayout.cs
  osu.Framework.Tests/Visual/Containers/TestScenePadding.cs
  osu.Framework/Graphics/Audio/WaveformGraph.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
  osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownTable.cs
  osu.Framework/Graphics/Containers/SafeAreaContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/InvalidationList.cs
  osu.Framework/Graphics/Sprites/SpriteIcon.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
  osu.Framework/Layout/InvalidationSource.cs
  osu.Framework/Layout/LayoutMember.cs
  osu.Framework/Layout/LayoutValue.cs
Labels: area:drawable, size/XXL

#3323 Fix incorrect handling of TestCaseAttribute
  osu.Framework.Tests/Visual/Testing/TestSceneTest.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: area:tooling, size/M, type:testing

#3324 Mark layout tests as headless and combine namespaces
  osu.Framework.Tests/Layout/TestSceneContainerLayout.cs
  osu.Framework.Tests/Layout/TestSceneDrawableLayout.cs
  osu.Framework.Tests/Layout/TestSceneGridContainerLayout.cs
Labels: size/S, type:testing

#3325 Fix bindable list build warnings
  osu.Framework.Tests/Bindables/BindableListTest.cs
  osu.Framework/Bindables/BindableList.cs
Labels: size/M, type:code-quality

#3327 Add fast invalidation path for bypass autosize axes
  osu.Framework.Tests/Layout/TestSceneContainerLayout.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
Labels: area:layout, size/L, type:performance

#3329 Fix CircularProgress incorrectly SRGBing
  osu.Framework.Tests/Visual/UserInterface/TestSceneCircularProgress.cs
  osu.Framework/Graphics/UserInterface/CircularProgressDrawNode.cs
Labels: area:drawable, size/XS

#3334 Guard against potential TrackBass test failures
  osu.Framework.Tests/Audio/TrackBassTest.cs
Labels: area:audio, size/XS, type:testing

#3333 Fix virtual track entering a running state when length is zero
  osu.Framework.Tests/Audio/TrackVirtualTest.cs
  osu.Framework/Audio/Track/TrackVirtual.cs
Labels: area:audio, size/L

#3338 Automatically run setup steps in visual test browser
  osu.Framework.Tests/Visual/Testing/TestSceneTest.cs
  osu.Framework/Testing/Drawables/Steps/SetUpStepButton.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestScene.cs
Labels: size/M, type:testing

#3335 Remove custom interpolation function from TransformCustom/TransformBinable
  osu.Framework/Graphics/TransformSequenceExtensions.cs
  osu.Framework/Graphics/TransformableExtensions.cs
  osu.Framework/Graphics/Transforms/TransformBindable.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/Utils/Interpolation.cs
Labels: area:transformations, size/M, type:code-quality

#3332 Extend color extension
  osu-framework.sln.DotSettings
  osu.Framework/Extensions/Color4Extensions/Color4Extensions.cs
Labels: size/L

#3336 Expose Interpolation.ValueAt<T>
  osu.Framework.Tests/MathUtils/TestInterpolation.cs
  osu.Framework/Graphics/Transforms/TransformBindable.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/Utils/Interpolation.cs
Labels: area:transformations, size/M

#3337 Explicitly define type interpolations via interfaces
  osu.Framework.Benchmarks/BenchmarkInterpolation.cs
  osu.Framework.Tests/MathUtils/TestInterpolation.cs
  osu.Framework/Graphics/MarginPadding.cs
  osu.Framework/Utils/IInterpolable.cs
  osu.Framework/Utils/Interpolation.cs
Labels: area:transformations, size/L

#3340 Make tab switching include the dropdown items
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
Labels: area:UI, size/M

#3347 Fix stack traces not being logged when performance profiling is turned off
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Statistics/BackgroundStackTraceCollector.cs
  osu.Framework/Statistics/PerformanceMonitor.cs
  osu.Framework/Threading/GameThread.cs
Labels: area:threading, size/L

#3346 Implement a texture atlas visualisation tool
  osu.Framework/Game.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlas.cs
  osu.Framework/Graphics/Visualisation/TextureAtlasVisualiser.cs
  osu.Framework/Input/FrameworkActionContainer.cs
Labels: area:tooling, size/L

#3348 Remove stray android project from rider config
  .idea/.idea.osu-framework.Desktop/.idea/modules.xml
Labels: area:tooling, size/XS, type:code-quality

#3352 Add per-frame texture and pixel upload limits
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: area:graphics, size/S, type:performance

#3354 Fix stalls in audio playback after silence
  osu.Framework/Audio/AudioManager.cs
Labels: area:audio, size/XS

#3356 Add option for VideoSprite to not assume current clock time
  osu.Framework/Graphics/Video/VideoSprite.cs
Labels: area:drawable, size/M

#3355 Expose Animation's frame index and frame data
  osu.Framework/Graphics/Animations/Animation.cs
  osu.Framework/Graphics/Animations/IAnimation.cs
Labels: area:drawable, size/M

#3357 Fix pippidon not moving upwards immediately after starting game
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGame.cs
Labels: area:tooling, size/XS

#3359 Fix video test scene failing
  osu.Framework.Tests/Visual/Sprites/TestSceneVideoSprite.cs
Labels: size/M, type:testing

#3358 Fix multiple issues with TextureAtlasVisualiser
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlas.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/Visualisation/TextureAtlasVisualiser.cs
Labels: area:tooling, size/L, type:performance

#3368 Expose a method of detecting and intercepting user scroll events in ScrollContainer
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: area:UI, size/S

#3315 Add game host setting for disabling mobile system idle timers
  osu.Framework.Android/AndroidGameActivity.cs
  osu.Framework.Android/AndroidGameView.cs
  osu.Framework.Tests/Visual/Platform/TestSceneAllowSuspension.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:platform, platform:mobile, size/M

#3339 Implement custom easing functions
  osu.Framework.Benchmarks/BenchmarkTransform.cs
  osu.Framework.Tests/MathUtils/TestInterpolation.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneCustomEasingCurve.cs
  osu.Framework/Graphics/MarginPadding.cs
  osu.Framework/Graphics/TransformSequenceExtensions.cs
  osu.Framework/Graphics/TransformableExtensions.cs
  osu.Framework/Graphics/Transforms/DefaultEasingFunction.cs
  osu.Framework/Graphics/Transforms/IEasingFunction.cs
  osu.Framework/Graphics/Transforms/Transform.cs
  osu.Framework/Graphics/Transforms/TransformBindable.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
  osu.Framework/Utils/IInterpolable.cs
  osu.Framework/Utils/Interpolation.cs
Labels: area:transformations, size/XXL

#3367 Suspend/Resume all threads when app is backgrounded in iOS
  osu.Framework.Tests/Platform/GameHostSuspendTest.cs
  osu.Framework.iOS/GameAppDelegate.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/ThreadRunner.cs
Labels: area:threading, platform:iOS, size/M, type:performance

#3371 Refresh audio DeviceInfo async from AudioThread
  osu.Framework/Audio/AudioManager.cs
Labels: size/M

#3351 Add Dynamic Audio Mode Switching on iOS
  osu.Framework.iOS/GameAppDelegate.cs
  osu.Framework/Audio/AudioManager.cs
Labels: area:audio, platform:iOS, size/S

#3379 Fix VideoTexture causing characters to disappear
  osu.Framework/Graphics/Video/VideoTexture.cs
Labels: area:graphics, size/XS

#3380 Fix normal video shader not respecting vertex colour
  osu.Framework.Tests/Visual/Sprites/TestSceneVideoSprite.cs
  osu.Framework/Resources/Shaders/sh_Video.fs
  osu.Framework/Resources/Shaders/sh_VideoRounded.fs
Labels: area:graphics, size/L

#3381 Add generic easing overload for CircularProgress.FillTo()
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
Labels: area:drawable, size/XS

#3378 Fix change detection in audioDevices list
  osu.Framework.Tests/Audio/AudioComponentTest.cs
  osu.Framework.Tests/Audio/AudioThreadTest.cs
  osu.Framework.Tests/Visual/Audio/TestSceneLoopingSample.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Threading/AudioThread.cs
Labels: size/S

#3385 Add game benchmark
  osu.Framework.Benchmarks/BenchmarkManySpinningBoxes.cs
  osu.Framework.Benchmarks/GameBenchmark.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/ThreadRunner.cs
Labels: area:tooling, size/L, type:testing

#3388 Reduce allocations during dependency injection
  osu.Framework.Benchmarks/BenchmarkDependencyContainer.cs
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
  osu.Framework/Allocation/DependencyContainer.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
Labels: area:audio, size/L, type:performance

#3386 Reduce IScreen extension method allocations
  osu.Framework.Benchmarks/BenchmarkScreenExtensions.cs
  osu.Framework/Screens/IScreen.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: size/L, type:performance

#3391 Remove allocations from InvokeOnDisposal delegates
  osu.Framework/Allocation/InvokeOnDisposal.cs
  osu.Framework/Allocation/ValueInvokeOnDisposal.cs
  osu.Framework/Graphics/BufferedDrawNode.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Transforms/ITransformable.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
  osu.Framework/Platform/NativeMemoryTracker.cs
Labels: size/L, type:performance

#3392 Expose Target field in ScrollContainer
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: size/M

#3390 Remove some minor delegate allocations
  osu-framework.sln.DotSettings
  osu.Framework/Graphics/Transforms/TransformBindable.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
Labels: size/XS, type:performance

#3394 Update .gitignore to support JetBrain Rider
  .gitignore
  .idea/.idea.osu-framework.Android/.idea/modules.xml
  .idea/.idea.osu-framework.Desktop/.idea/modules.xml
  .idea/.idea.osu-framework.iOS/.idea/modules.xml
Labels: size/M

#3393 Push screen before OnExiting instead of after
  osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: size/S

#3396 Handle TextureAtlas findPosition() edge cases
  osu.Framework.Tests/Graphics/TextureAtlasTest.cs
  osu.Framework/Graphics/Textures/TextureAtlas.cs
Labels: area:graphics, size/XS

#3401 Expose less backend-specific types in IWindow
  osu.Framework/Extensions/BridgingExtensions.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKMouseHandler.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
  osu.Framework/Platform/DesktopGameWindow.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/GameWindow.cs
  osu.Framework/Platform/IWindow.cs
  osu.Framework/Platform/IWindowBackend.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/Sdl2WindowBackend.cs
  osu.Framework/Platform/Window.cs
  osu.Framework/Platform/WindowState.cs
  osu.Framework/osu.Framework.csproj
Labels: size/L

#3407 Allow caching via attribute on interfaces
  osu.Framework.Tests/Dependencies/CachedAttributeTest.cs
  osu.Framework/Allocation/CachedAttribute.cs
Labels: area:dependency-injection, size/M

#3406 Fix video sprite start-at-current offset being applied in the wrong direction
  osu.Framework.Tests/Visual/Sprites/TestSceneVideoSprite.cs
  osu.Framework/Graphics/Video/VideoSprite.cs
Labels: area:drawable, size/M

#3405 Add animation rewinding support
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimationLayout.cs
  osu.Framework/Graphics/Animations/Animation.cs
  osu.Framework/Graphics/Animations/FrameData.cs
  osu.Framework/Graphics/Animations/TextureAnimation.cs
Labels: area:drawable, size/XL

#3411 Better support custom clocks in VideoSprite and Animation
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework/Graphics/Animations/Animation.cs
  osu.Framework/Graphics/Video/VideoSprite.cs
Labels: area:drawable, size/L
