Repository ppy/osu-framework, pull requests merged in 2020-08, with the labels that each got.

#3783 Approximate IsMaskedAway with Precision
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Utils/Precision.cs
Labels: area:drawable, size/M

#3786 Fix allocations by hidden drawable visualisers
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
Labels: area:tooling, size/S, type:performance

#3779 Improve performance of transform logic when many transforms are present
  osu.Framework.Benchmarks/BenchmarkTransformUpdate.cs
  osu.Framework.Tests/Visual/Containers/TestSceneVisibilityContainer.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Transforms/TargetMemberTransformTracker.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
Labels: blocked, size/XL, type:performance

#3759 Rescale joystick axis values according to deadzones
  osu.Framework.Tests/Visual/Input/TestSceneJoystick.cs
  osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs
Labels: area:input, size/S

#3787 Complete the ITrack interface and DrawableTrack implementation
  osu.Framework/Audio/Track/ITrack.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Graphics/Audio/DrawableTrack.cs
Labels: area:audio, size/M

#3676 Perform mouse-from-touch input only when no drawable handled the touch
  osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
  osu.Framework.Tests/Visual/Input/TestSceneTouchInput.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Input/TouchEventManager.cs
Labels: area:input, platform:mobile, size/L

#3793 Disable confine mouse mode in macOS to fix fullscreen cursor movement
  osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
  osu.Framework/Platform/MacOS/MacOSGameWindow.cs
Labels: area:input, platform:macOS, size/S

#3790 Add more DrawableAudioWrapper transform support
  osu.Framework.Tests/Visual/Audio/TestSceneSamples.cs
  osu.Framework/Audio/IAdjustableAudioComponent.cs
  osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
Labels: area:audio, size/L

#3792 Fix previous sample channels not immediately freed on new playbacks
  osu.Framework/Audio/Sample/SampleChannelBass.cs
Labels: area:audio, size/XS

#3794 Fix DrawableTrack not resetting adjustments correctly
  osu.Framework.Tests/Audio/TestSceneDrawableTrack.cs
  osu.Framework/Graphics/Audio/DrawableTrack.cs
Labels: area:audio, size/M

#3795 Add better separator for KeyCombination display
  osu.Framework/Input/Bindings/KeyCombination.cs
Labels: area:UI, size/XS

#2808 Handle Sample Channels with 0 frequencies
  osu.Framework.Tests/Visual/Audio/TestSceneLoopingSample.cs
  osu.Framework.Tests/Visual/Audio/TestSceneSampleLooping.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
Labels: area:audio, size/L

#3809 Expose property to retrieve load state of underlying track
  osu.Framework/Graphics/Audio/DrawableTrack.cs
Labels: area:audio, size/XS

#3810 Make ITrack an IAdjustableAudioComponent and IAdjustableClock
  osu.Framework/Audio/Track/ITrack.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Graphics/Audio/DrawableTrack.cs
Labels: area:audio, size/M

#3814 Disable mipmapping on FrameStatisticsDisplay textures
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Labels: size/XS, type:performance

#3813 Implement a mechanism for freeing unused static VBOs
  osu.Framework/Graphics/OpenGL/Buffers/IVertexBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: size/L, type:performance

#3819 Atlas viewer view all textures
  osu.Framework/Game.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlas.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/Visualisation/TextureVisualiser.cs
  osu.Framework/Graphics/Visualisation/ToolWindow.cs
Labels: area:tooling, size/L

#3820 Fix VideoTexture not working with the texture viewer
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/Video/VideoTexture.cs
  osu.Framework/Graphics/Visualisation/TextureVisualiser.cs
Labels: area:graphics, size/M

#3805 Prevent menus from consuming Escape keypresses when fading out
  osu.Framework.Tests/Visual/UserInterface/TestSceneClosableMenu.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
Labels: area:UI, size/M

#3823 Reconfigure bass for lower latency on linux
  osu.Framework/Audio/AudioManager.cs
Labels: area:audio, platform:linux, size/XS

#3824 Fix LargeTextureStore never purging textures
  osu.Framework/Graphics/Textures/LargeTextureStore.cs
  osu.Framework/Graphics/Textures/Texture.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
Labels: size/M, type:performance

#3828 Disable stack trace collection on windows
  osu.Framework/Statistics/BackgroundStackTraceCollector.cs
Labels: size/S, type:performance

#3830 Fix build warnings
  osu.Framework.Tests/Clocks/DecoupleableClockTest.cs
  osu.Framework.Tests/Visual/Containers/TestSceneSizing.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/IO/Stores/IResourceStore.cs
  osu.Framework/Platform/MacOS/MacOSGameWindow.cs
  osu.Framework/Statistics/PerformanceMonitor.cs
  osu.Framework/Timing/InterpolatingFramedClock.cs
Labels: size/M, type:code-quality

#3832 Revert device period to fix linux audio crackling
  osu.Framework/Audio/AudioManager.cs
Labels: area:audio, blocked, platform:linux, size/XS

#3822 Fix transforms operating on same properties being applied out of order
  osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
  osu.Framework/Graphics/TransformableExtensions.cs
  osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
  osu.Framework/Graphics/Transforms/Transform.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
Labels: area:transformations, size/L

#3838 Fix transforms added during load being potentially not processed
  osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
  osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
Labels: area:transformations, size/M

#3839 Invoke text mutation method events only when done by user input
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: area:UI, size/L

#3841 Update MarkDig package
  osu.Framework.iOS.props
  osu.Framework/Graphics/Containers/Markdown/MarkdownTable.cs
  osu.Framework/osu.Framework.csproj
Labels: dependencies, size/XS

#3842 Fix transforms potentially being skipped due to incorrect order of application
  osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
  osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
Labels: area:transformations, size/M

#3845 Disable CA2225 warning regarding operator overloads
  .editorconfig
Labels: size/XS, type:code-quality

#3848 Add support for seeking a non-loaded animation
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework/Graphics/Animations/AnimationClockComposite.cs
Labels: area:drawable, size/M

#3850 Remove obsolete members
  osu.Framework.Tests/Bindables/BindableListTest.cs
  osu.Framework/Bindables/BindableList.cs
  osu.Framework/Bindables/IBindableList.cs
  osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Utils/Validation.cs
Labels: size/L

#3835 Move IAggregateAudioAdjustment.GetAggregate() to extensions method
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AggregateAdjustmentExtensions.cs
  osu.Framework/Audio/AudioAdjustments.cs
  osu.Framework/Audio/IAggregateAudioAdjustment.cs
  osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
Labels: area:audio, proposal, size/M, type:code-quality

#3851 Add Animation.ClearFrames()
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimation.cs
  osu.Framework/Graphics/Animations/Animation.cs
Labels: area:drawable, size/S

#3852 Fix regression in GlobalStatisticsDisplay behaviour
  osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
Labels: size/XS

#3853 Avoid firing CollectionChanged on no-op BindableList.RemoveAll
  osu.Framework.Tests/Bindables/BindableListTest.cs
  osu.Framework/Bindables/BindableList.cs
Labels: area:bindable, size/S

#3818 Remember window position between sessions (SDL)
  osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
  osu.Framework/Input/UserInputManager.cs
  osu.Framework/Platform/DesktopWindow.cs
  osu.Framework/Platform/Display.cs
  osu.Framework/Platform/DisplayMode.cs
  osu.Framework/Platform/IWindowBackend.cs
  osu.Framework/Platform/Sdl/Sdl2Extensions.cs
  osu.Framework/Platform/Sdl/Sdl2WindowBackend.cs
  osu.Framework/Platform/Window.cs
Labels: area:platform, size/L
