Repository ppy/osu-framework, pull requests merged in 2021-02, with the labels that each got.

#4183 Make window render to the cutout areas of android devices
  osu.Framework.Android/AndroidGameActivity.cs
Labels: platform:android, size/XS

#4185 Re-retrieve syntax trees on the correct compilation
  osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
Labels: area:tooling, size/S, type:testing

#4186 Add cancellation support to WebRequest
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework/IO/Network/WebRequest.cs
Labels: area:network, size/L

#4188 Update NUnit and pull in dependent (removed) code locally
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/Development/ReflectionUtils.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/osu.Framework.csproj
Labels: size/L

#4189 Improve the exception message when Child is accessed with incorrect Children count
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/Container.cs
Labels: size/XS

#4190 Fix RearrangeableListContainer considering hidden items when dragging selection
  osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
  osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
Labels: area:UI, size/S

#4191 Add IPv4 fallback support on IPv6 failures
  osu.Framework/IO/Network/WebRequest.cs
Labels: area:network, size/M

#4192 Fix input propagating to drawables which are not yet in a loaded state
  osu.Framework.Tests/Visual/Input/TestSceneInputPropagationForLoadStates.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: area:input, size/M

#4161 Rework Sample and SampleChannel to better handle concurrent playbacks
  osu.Framework.Tests/Audio/SampleBassTest.cs
  osu.Framework.Tests/Audio/SampleChannelVirtualTest.cs
  osu.Framework.Tests/Audio/TrackBassTest.cs
  osu.Framework.Tests/Visual/Audio/TestSceneSampleAmplitudes.cs
  osu.Framework.Tests/Visual/Audio/TestSceneSampleChannels.cs
  osu.Framework.Tests/Visual/Audio/TestSceneSampleLooping.cs
  osu.Framework.Tests/Visual/Audio/TestSceneSamples.cs
  osu.Framework/Audio/AudioComponent.cs
  osu.Framework/Audio/Sample/ISample.cs
  osu.Framework/Audio/Sample/ISampleChannel.cs
  osu.Framework/Audio/Sample/ISampleStore.cs
  osu.Framework/Audio/Sample/Sample.cs
  osu.Framework/Audio/Sample/SampleBass.cs
  osu.Framework/Audio/Sample/SampleBassFactory.cs
  osu.Framework/Audio/Sample/SampleChannel.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
  osu.Framework/Audio/Sample/SampleChannelVirtual.cs
  osu.Framework/Audio/Sample/SampleStore.cs
  osu.Framework/Audio/Sample/SampleVirtual.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Graphics/Audio/DrawableSample.cs
Labels: area:audio, size/XL

#4194 Internalise per-sample playback concurrency for now
  osu.Framework/Audio/Sample/SampleBassFactory.cs
Labels: area:audio, size/XS

#4199 Fix samples allowing retrieval after they are disposed
  osu.Framework.Tests/Audio/SampleBassTest.cs
  osu.Framework/Audio/Sample/Sample.cs
Labels: area:audio, size/S, type:reliability

#4201 Change IAdjustableAudioComponent/AudioAdjustments to use IBindable instead of BindableNumber
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioAdjustments.cs
  osu.Framework/Audio/IAdjustableAudioComponent.cs
  osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
Labels: size/S

#4197 Fix TextureStore and ResourceStore locks being held globally across all lookups
  osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/IO/Stores/OnlineStore.cs
  osu.Framework/IO/Stores/ResourceStore.cs
Labels: area:storage, size/L, type:performance

#4204 Fix RawCachingGlyphStore performing operations on same files from multiple threads
  osu.Framework/IO/Stores/RawCachingGlyphStore.cs
Labels: size/S, type:reliability

#4205 Fix remaining portion of glyph store lookup happening outside of locked region
  osu.Framework/IO/Stores/RawCachingGlyphStore.cs
Labels: area:fonts, size/S

#4207 Fix incorrect entry assembly selection on android
  osu.Framework/Development/DebugUtils.cs
Labels: area:platform, platform:android, size/S

#4210 Correct misspelled word in the interface summary
  osu.Framework/Timing/IFrameBasedClock.cs
Labels: size/XS, type:documentation

#4203 Use ISample in DrawableSample
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioAdjustments.cs
  osu.Framework/Audio/IAdjustableAudioComponent.cs
  osu.Framework/Audio/Sample/ISample.cs
  osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
  osu.Framework/Graphics/Audio/DrawableSample.cs
Labels: area:audio, size/M

#4209 Make `IAdjustableAudioComponent` inherit `IAggregateAudioAdjustment`
  osu.Framework/Audio/AdjustableAudioComponent.cs
  osu.Framework/Audio/AudioAdjustments.cs
  osu.Framework/Audio/IAdjustableAudioComponent.cs
  osu.Framework/Audio/IAdjustableResourceStore.cs
  osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
Labels: area:audio, size/S

#4211 Fix annoying inspection due to conditional-compilation
  osu.Framework/IO/Network/WebRequest.cs
Labels: area:tooling, size/XS

#4213 Rename built-in font OpenSans to OpenSans-Regular
  osu.Framework.Tests/IO/FontStoreTest.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteText.cs
  osu.Framework/Game.cs
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-Regular.bin
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-RegularItalic.bin
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-RegularItalic_0.png
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-Regular_0.png
Labels: area:fonts

#3157 Localisation overhaul
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework.Tests/Visual/Layout/TestSceneFillFlowContainer.cs
  osu.Framework.Tests/Visual/Layout/TestSceneGridContainer.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneRomanisableSpriteText.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextScenarios.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/Sprites/IHasText.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/UserInterface/BasicButton.cs
  osu.Framework/Graphics/UserInterface/BasicCheckbox.cs
  osu.Framework/Graphics/UserInterface/BasicDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/DropdownHeader.cs
  osu.Framework/Graphics/UserInterface/DropdownMenuItem.cs
  osu.Framework/Graphics/UserInterface/MenuItem.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Localisation/ILocalisationStore.cs
  osu.Framework/Localisation/ILocalisedBindableString.cs
  osu.Framework/Localisation/LocalisableString.cs
  osu.Framework/Localisation/LocalisationManager.cs
  osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
  osu.Framework/Localisation/LocalisedString.cs
  osu.Framework/Localisation/RomanisableString.cs
  osu.Framework/Localisation/TranslatableString.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarAssemblySection.cs
  osu.Framework/Testing/Drawables/Steps/StepButton.cs
  osu.Framework/Testing/Drawables/Steps/StepSlider.cs
Labels: area:localisation, size/XL

#4216 Fix leak of pinned sample handles
  osu.Framework/Audio/Sample/SampleBassFactory.cs
Labels: area:audio, size/XS, type:performance

#4217 Switch order of parameters on RomanisableString to make the original version come first
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneRomanisableSpriteText.cs
  osu.Framework/Localisation/RomanisableString.cs
Labels: size/M

#4218 Add optimised HasFlagFast<T> extension to Enum
  .editorconfig
  CodeAnalysis/BannedSymbols.txt
  osu.Framework.Benchmarks/BenchmarkEnum.cs
  osu.Framework.Benchmarks/Program.cs
  osu.Framework.Tests/Visual/Containers/TestSceneSafeAreaOverrides.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneIsMaskedAway.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs
  osu.Framework/Extensions/EnumExtensions/EnumExtensions.cs
  osu.Framework/Graphics/Containers/AudioContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/ContainerExtensions.cs
  osu.Framework/Graphics/Containers/FillFlowContainer.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
  osu.Framework/Graphics/Containers/SafeAreaContainer.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/Pooling/PoolableDrawable.cs
  osu.Framework/Graphics/Textures/Texture.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKMouseState.cs
  osu.Framework/Input/Handlers/Mouse/OsuTKRawMouseHandler.cs
  osu.Framework/Input/UserInputManager.cs
  osu.Framework/Platform/MacOS/OsuTKMacOSWindow.cs
  osu.Framework/Platform/OsuTKWindow.cs
  osu.Framework/Platform/SDL2/SDL2Extensions.cs
  osu.Framework/Platform/SDL2DesktopWindow.cs
Labels: size/L, type:performance

#4219 Update analyser package
  Directory.Build.props
Labels: area:tooling, size/XS

#4222 Fix empty POST requests always having multipart body specification
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework/IO/Network/WebRequest.cs
Labels: size/M

#4223 Don't use transforms in frame statistics
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Labels: size/XS, type:performance

#4224 Fix enumerating HoveredDrawables causing excessive allocations
  osu.Framework/Input/InputManager.cs
Labels: size/XS, type:performance

#4225 Remove remaining enumerator allocations from frame time display updates
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Labels: size/XS, type:performance

#4226 Reuse TextBuilder when validating SpriteText
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Text/TextBuilder.cs
  osu.Framework/Text/TruncatingTextBuilder.cs
Labels: size/M, type:performance

#4227 Fix number formatter allocating many arrays
  osu.Framework/Utils/NumberFormatter.cs
Labels: size/XS, type:performance
