Repository ppy/osu-framework, pull requests merged in 2021-12, with the labels that each got.

#4908 Fixes for `TextBox`, and a `TextInputSource` refactor
  osu.Framework.Android/AndroidGameHost.cs
  osu.Framework.Android/Input/AndroidTextInput.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework.iOS/Input/IOSTextInput.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Input/ITextInputSource.cs
  osu.Framework/Input/SDL2DesktopWindowTextInput.cs
  osu.Framework/Input/TextInputSource.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:input, size/L

#4925 Change `Resolved` attribute to only have implicit `set` usage
  osu.Framework.Benchmarks/BenchmarkDependencyContainer.cs
  osu.Framework.Tests/Dependencies/ResolvedAttributeTest.cs
  osu.Framework/Allocation/ResolvedAttribute.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownHeading.cs
Labels: type:code-quality, size/XS

#4926 Apply new rider/resharper method body refactors
  osu.Framework.Tests/Audio/AudioThreadTest.cs
  osu.Framework.Tests/Visual/Containers/TestSceneCircularContainerSizing.cs
  osu.Framework.Tests/Visual/Containers/TestSceneCursorContainer.cs
  osu.Framework.Tests/Visual/Containers/TestSceneLifetimeManagementContainer.cs
Labels: type:code-quality, size/M

#4927 Keep BASS audio output from pausing on device processing timeout
  osu.Framework/Audio/AudioManager.cs
Labels: area:audio, size/XS

#4928 Force flushing logger during unhandled/unobserved exception handling
  osu.Framework/Platform/GameHost.cs
Labels: size/XS, type:reliability

#4907 Add SDL2 IME support
  osu.Framework.Android/Input/AndroidTextInput.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs
  osu.Framework/Extensions/PlatformActionExtensions/PlatformActionExtensions.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Input/SDL2DesktopWindowTextInput.cs
  osu.Framework/Input/TextInputSource.cs
  osu.Framework/Platform/SDL2/SDL2Extensions.cs
  osu.Framework/Platform/SDL2DesktopWindow.cs
  osu.Framework/osu.Framework.csproj
Labels: area:input, size/XXL

#4929 Disable minimum frame durations on iOS framework projects
  SampleGame.iOS/Info.plist
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.Tests.iOS/Info.plist
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework/osu.Framework.csproj
Labels: type:performance, platform:iOS, size/S

#4930 Improve exception messaging when calling `CompositeDrawable.InternalChild` on disposed drawable
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/Container.cs
Labels: type:code-quality, size/S

#4931 Update osuTK to fix compatibility with iOS 14 and lower
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#4932 Add extension for checking if a character is an ASCII digit
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Extensions/ExtensionMethods.cs
Labels: area:UI, size/S

#4933 Update osuTK once more (for iOS compatibility)
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#4934 Refactor `TcpIpcProvider` to bring up to date with code standards
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Platform/TcpIpcProvider.cs
Labels: type:code-quality, size/L

#4935 Add screen stack logging
  osu.Framework/Screens/ScreenStack.cs
Labels: area:logging, area:screens, size/XS

#4936 Fix `AddOnce` scheduled tasks not getting updates to data from subsequent calls
  osu.Framework.Tests/Threading/SchedulerTest.cs
  osu.Framework/Threading/ScheduledDelegate.cs
  osu.Framework/Threading/ScheduledDelegateWithData.cs
  osu.Framework/Threading/Scheduler.cs
Labels: area:threading, size/M

#4937 Use icons and reduce clutter in test logging
  osu.Framework.Tests/Visual/Containers/TestSceneLifetimeManagementContainer.cs
  osu.Framework.Tests/Visual/Input/TestSceneMidi.cs
  osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
  osu.Framework/Screens/ScreenStack.cs
  osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
  osu.Framework/Testing/TestBrowserTestRunner.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/Testing/TestSceneTestRunner.cs
Labels: area:logging, size/M

#4938 Log loading components on test failure or game exit
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Logging/LoadingComponentsLogger.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/osu.Framework.csproj
Labels: area:logging, size/M

#4940 Fix incorrect usages of `ConditionalAttribute` for debug isolation
  osu.Framework/Logging/LoadingComponentsLogger.cs
  osu.Framework/Logging/Logger.cs
Labels: area:logging, size/S

#4943 Stop virtual tracks on disposal
  osu.Framework.Tests/Audio/TrackBassTest.cs
  osu.Framework.Tests/Audio/TrackVirtualTest.cs
  osu.Framework/Audio/Track/TrackVirtual.cs
Labels: area:audio, size/M

#4939 Add Shadow Colour and Offset to SpriteIcon
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs
  osu.Framework/Graphics/Sprites/SpriteIcon.cs
Labels: area:UI, size/M

#4944 Improve test logging output further
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Logging/LoadingComponentsLogger.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/Threading/ThreadedTaskScheduler.cs
Labels: area:logging, size/M

#4945 Add more detailed `ScreenStack` logging
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: area:logging, area:screens, size/M

#4948 Use `Drawable.ToString` in `LoadingComponentsLogger`
  osu.Framework/Logging/LoadingComponentsLogger.cs
Labels: area:logging, size/XS

#4947 Add logging of `ScreenStack` push failures due to `ValidForPush` being `false`
  osu.Framework/Screens/ScreenStack.cs
Labels: area:screens, size/XS

#4949 Update nativelibs package
  osu.Framework/osu.Framework.csproj
Labels: size/XS, dependencies

#4953 Add missing xmldoc to `InputConfigManager`
  osu.Framework/Configuration/InputConfigManager.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:configuration, type:documentation, size/S

#4954 Add `CancellationToken` support to `IResourceStore.GetAsync`
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework.Tests/Visual/Localisation/TestSceneTextFlowContainerLocalisation.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextScenarios.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
  osu.Framework/Audio/Sample/SampleStore.cs
  osu.Framework/Audio/Track/TrackStore.cs
  osu.Framework/Graphics/Textures/TextureLoaderStore.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/IO/Stores/DllResourceStore.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/IResourceStore.cs
  osu.Framework/IO/Stores/OnlineStore.cs
  osu.Framework/IO/Stores/ResourceStore.cs
  osu.Framework/IO/Stores/StorageBackedResourceStore.cs
Labels: area:threading, size/M

#4951 Adjust Android lifecycle code in line with context preservation changes
  osu.Framework.Android/AndroidGameActivity.cs
  osu.Framework.Android/AndroidGameView.cs
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework/osu.Framework.csproj
Labels: platform:android, size/S

#4956 Fix multiple test failures in screen stack tests
  osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
Labels: type:testing, size/S

#4955 Avoid throwing exception during log file cleanup
  osu.Framework/Logging/Logger.cs
Labels: size/S, type:reliability

#4958 Fix incorrect number formatting on failure reptition output
  osu.Framework/Testing/TestScene.cs
Labels: size/XS

#4957 Output test method name in log output
  osu.Framework/Testing/Drawables/Steps/StepButton.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/Testing/TestSceneTestRunner.cs
Labels: area:logging, size/S

#4959 Use fullscreen mode in Android visual test activity
  osu.Framework.Tests.Android/TestGameActivity.cs
Labels: type:testing, platform:android, size/XS

#4960 Standardize Android activity and permissions
  SampleGame.Android/SampleGameActivity.cs
  osu.Framework.Android/AndroidGameActivity.cs
  osu.Framework.Android/Properties/AssemblyInfo.cs
  osu.Framework.Tests.Android/TestGameActivity.cs
Labels: size/M

#4961 Avoid doing individual file operations for each line of log output
  osu.Framework.Benchmarks/BenchmarkLogger.cs
  osu.Framework/Logging/Logger.cs
Labels: area:logging, size/L

#4963 Add logging of TPL threadpool state on test failures
  osu.Framework/Logging/LoadingComponentsLogger.cs
Labels: area:logging, size/XS

#4962 Fix `RearrangeableListContainer` not disposing removed items
  osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
  osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
Labels: type:performance, size/S

#4964 Expose `GameHost.Name`
  osu.Framework/Platform/GameHost.cs
Labels: size/XS

#4965 Opportunistically trim WeakList<T> on additions after many removals or additions
  osu.Framework.Benchmarks/BenchmarkWeakList.cs
  osu.Framework/Lists/WeakList.cs
Labels: type:performance, area:bindable, size/L

#4967 Fix `LoadComponentAsync` running load continuation asynchronously
  osu.Framework.Tests/Containers/TestSceneLoadComponentAsync.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Logging/LoadingComponentsLogger.cs
Labels: size/M, type:reliability

#4968 Reduce allocation overheads on all GL disposal paths
  osu.Framework/Graphics/BufferedDrawNodeSharedData.cs
  osu.Framework/Graphics/DrawNode.cs
  osu.Framework/Graphics/OpenGL/Buffers/FrameBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/VertexBuffer.cs
  osu.Framework/Graphics/OpenGL/GLDisposalQueue.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
  osu.Framework/Graphics/Shaders/Shader.cs
  osu.Framework/Graphics/Shaders/ShaderManager.cs
  osu.Framework/Graphics/Shaders/ShaderPart.cs
  osu.Framework/Graphics/Video/VideoTexture.cs
Labels: type:performance, size/L

#4969 Reduce delegate allocation overheads
  osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
  osu.Framework/Graphics/Pooling/PoolableDrawable.cs
  osu.Framework/Platform/SDL2DesktopWindow.cs
  osu.Framework/Threading/ScheduledDelegate.cs
  osu.Framework/Threading/ScheduledDelegateWithData.cs
  osu.Framework/Threading/Scheduler.cs
Labels: type:performance, size/M

#4972 Don't fake-schedule SDL events
  osu.Framework/Platform/SDL2DesktopWindow.cs
Labels: type:performance, size/M, area:platform
