Repository ppy/osu-framework, pull requests merged in 2021-06, with the labels that each got.

#4474 Fix samples not reloading if loaded too early
  osu.Framework.Tests/Audio/SampleBassInitTest.cs
  osu.Framework/Audio/Sample/SampleBassFactory.cs
Labels: area:audio, size/L

#4481 Update dependencies
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/TemplateGame.Game.Tests.csproj
  osu.Framework.Templates/templates/template-empty/TemplateGame.Game/TemplateGame.Game.csproj
  osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/FlappyDon.Game.Tests.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDon.Game.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework.iOS.props
  osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
  osu.Framework/osu.Framework.csproj
Labels: dependencies, size/M

#4483 Fix `MarkdownContainer` not translating relative URLs correctly on android/iOS
  CodeAnalysis/BannedSymbols.txt
  osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
Labels: area:platform, size/S

#4484 Allow testing of `PlatformAction`s in `ManualInputManagerTestScene`s
  osu.Framework/Testing/ManualInputManagerTestScene.cs
Labels: size/XS, type:testing

#4485 Fix inability to backspace text after typing shifted characters
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: area:UI, area:input, size/M

#4471 Fix KeyBindingContainer using InputState to build combinations
  osu.Framework.Tests/Input/KeyBindingInputTest.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
Labels: area:input, size/L

#4490 Avoid changing windows time period when focus changes
  osu.Framework/Platform/Windows/TimePeriod.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
Labels: area:audio, platform:windows, size/M

#4492 Fix Markdown container crashing on absolute URIs with no authority part
  CodeAnalysis/BannedSymbols.txt
  osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
  osu.Framework/Utils/Validation.cs
Labels: area:platform, size/M, type:reliability

#4495 Fix typo in Waveform xmldoc
  osu.Framework/Audio/Track/Waveform.cs
Labels: size/XS, type:documentation

#4496 Add test coverage of bindable serialisation from ctor parameter initialisation
  osu.Framework.Tests/Bindables/BindableSerializationTest.cs
Labels: area:bindable, size/S, type:testing

#4497 Fix potential ScreenStack test failure
  osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
Labels: size/XS, type:testing

#4498 Avoid overwriting user configuration locale when falling back to a default locale
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework/Localisation/LocalisationManager.cs
Labels: area:localisation, size/S

#4499 Fix `FrameworkConfigManager.WindowSize` not updating during resize operations
  osu.Framework/Platform/SDL2DesktopWindow.cs
Labels: area:configuration, size/S

#4489 Add HSV colour picker component
  osu.Framework.Tests/Visual/UserInterface/TestSceneHSVColourPicker.cs
  osu.Framework/Graphics/UserInterface/BasicHSVColourPicker.cs
  osu.Framework/Graphics/UserInterface/HSVColourPicker.cs
  osu.Framework/Graphics/UserInterface/HSVColourPicker_HueSelector.cs
  osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
  osu.Framework/Resources/Shaders/sh_HueSelectorBackground.fs
  osu.Framework/Resources/Shaders/sh_HueSelectorBackgroundRounded.fs
  osu.Framework/Resources/Shaders/sh_Utils.h
Labels: area:UI, size/XL

#4500 Improve safety of `GameThread.Running` (and make `GameThread.Start` blocking)
  osu.Framework/Threading/GameThread.cs
Labels: area:threading, size/XS

#4501 Rename CI run-annotating workflow to explain its purpose better
  .github/workflows/report-nunit.yml
Labels: area:tooling, size/XS

#4503 Add `TryParseHex` methods to `Colour4`
  osu.Framework.Tests/Graphics/ColourTest.cs
  osu.Framework/Graphics/Colour4.cs
Labels: area:graphics, size/L

#4510 Fix switching to borderless window incorrectly overwriting window size configuration
  osu.Framework/Platform/SDL2DesktopWindow.cs
Labels: area:platform, size/XS

#4509 Fix platform actions activating twice in `ManualTestScene`s
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
  osu.Framework/Testing/ManualInputManagerTestScene.cs
Labels: size/M, type:testing

#4505 Add extra safety over thread start/pause logic
  osu.Framework/Threading/GameThread.cs
Labels: area:threading, size/M

#4513 Disable `dotnet format` from running on appveyor too
  build/build.cake
Labels: area:tooling, size/XS

#4506 Add hex colour picker
  osu.Framework.Tests/Visual/UserInterface/TestSceneHexColourPicker.cs
  osu.Framework/Graphics/UserInterface/BasicHexColourPicker.cs
  osu.Framework/Graphics/UserInterface/HexColourPicker.cs
Labels: area:UI, size/L

#4515 Add logging if dynamic compilation is disabled due to no solution file
  osu.Framework/Testing/DynamicClassCompiler.cs
Labels: size/S, type:testing

#4517 Add inspectcode scripts
  InspectCode.ps1
  InspectCode.sh
  README.md
Labels: area:tooling, size/S, type:testing

#4514 Make Resharper inspections fail the CI job
  .config/dotnet-tools.json
  .github/workflows/ci.yml
Labels: area:tooling, size/S, type:testing

#4518 Add LocalisableEnumAttribute and GetLocalisableDescription() extension method
  osu.Framework.Tests/Localisation/LocalisableEnumAttributeTest.cs
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Localisation/EnumLocalisationMapper.cs
  osu.Framework/Localisation/LocalisableEnumAttribute.cs
Labels: area:localisation, size/L

#4521 Add combined colour picker
  osu.Framework.Tests/Visual/UserInterface/TestSceneColourPicker.cs
  osu.Framework/Graphics/UserInterface/BasicColourPicker.cs
  osu.Framework/Graphics/UserInterface/ColourPicker.cs
  osu.Framework/Graphics/UserInterface/HSVColourPicker_HueSelector.cs
  osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
Labels: area:UI, size/L

#4526 Fix some new inspections from latest resharper EAP
  osu.Framework.Tests/Audio/TestAudioAdjustments.cs
  osu.Framework/Bindables/NonNullableBindable.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Localisation/LocalisationManager.cs
Labels: size/S, type:code-quality

#4529 Apply few changes to the `ShaderManager` structure
  osu.Framework/Graphics/Shaders/ShaderManager.cs
Labels: area:shader, size/L, type:code-quality

#4516 Use `Roboto` font as framework default and set explicitly in system interfaces
  osu.Framework.Tests/IO/FontStoreTest.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteText.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs
  osu.Framework/Game.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Graphics/UserInterface/BasicTabControl.cs
  osu.Framework/Graphics/Visualisation/DrawableTransform.cs
  osu.Framework/Graphics/Visualisation/LogOverlay.cs
  osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
  osu.Framework/Graphics/Visualisation/TextureVisualiser.cs
  osu.Framework/Graphics/Visualisation/TreeContainer.cs
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
  osu.Framework/Resources/Fonts/OpenSans/LICENSE.txt
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-Bold.bin
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-BoldItalic.bin
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-BoldItalic_0.png
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-Bold_0.png
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-Regular.bin
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-RegularItalic.bin
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-RegularItalic_0.png
  osu.Framework/Resources/Fonts/OpenSans/OpenSans-Regular_0.png
  osu.Framework/Resources/Fonts/Roboto/Roboto-BoldItalic.bin
  osu.Framework/Resources/Fonts/Roboto/Roboto-BoldItalic_0.png
  osu.Framework/Resources/Fonts/Roboto/Roboto-BoldItalic_1.png
  osu.Framework/Resources/Fonts/Roboto/Roboto-RegularItalic.bin
  osu.Framework/Resources/Fonts/Roboto/Roboto-RegularItalic_0.png
  osu.Framework/Testing/TestBrowser.cs
Labels: area:UI, size/M

#4531 Fix `LoadRaw` return value not marked as nullable
  osu.Framework/Graphics/Shaders/ShaderManager.cs
Labels: area:shader, size/XS, type:code-quality

#4532 Change markdown heading text size to use actual font size
  osu.Framework/Graphics/Containers/Markdown/MarkdownHeading.cs
Labels: area:drawable, size/S

#4527 Fix draw thread not releasing GL context when toggling threading mode
  osu.Framework.Tests/Visual/Platform/TestSceneExecutionModes.cs
  osu.Framework/Platform/SDL2/SDL2GraphicsBackend.cs
  osu.Framework/Threading/DrawThread.cs
  osu.Framework/Threading/GameThread.cs
Labels: area:threading, size/M, type:reliability

#4533 Expose an event from `GameHost` before update thread changes native threads
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Threading/DrawThread.cs
  osu.Framework/Threading/GameThread.cs
Labels: size/S

#4538 Move pause event to only exist at `GameThread`
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Threading/GameThread.cs
Labels: size/S

#4540 Make tooltips text localisable
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTooltip.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownLinkText.cs
  osu.Framework/Graphics/Cursor/IHasTooltip.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
  osu.Framework/Graphics/Visualisation/TextureVisualiser.cs
Labels: area:UI, size/M

#4545 Differentiate between maximised and fullscreen borderless state in macOS
  osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
  osu.Framework/Platform/SDL2/SDL2Extensions.cs
Labels: area:platform, platform:macOS, size/S

#4544 Restore window before maximising to ensure the correct size is used
  osu.Framework/Platform/SDL2DesktopWindow.cs
Labels: area:platform, size/XS

#4542 Rewrite `GameThread` and expose state as `IBindable<GameThreadState>`
  osu.Framework.Tests/Platform/GameHostSuspendTest.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/ThreadRunner.cs
  osu.Framework/Threading/AudioThread.cs
  osu.Framework/Threading/DrawThread.cs
  osu.Framework/Threading/GameThread.cs
  osu.Framework/Threading/GameThreadState.cs
  osu.Framework/Threading/InputThread.cs
Labels: area:threading, size/XL

#4494 Display border and edge effect for drawables with negative size
  osu.Framework.Tests/Visual/Containers/TestSceneMasking.cs
  osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
  osu.Framework/Graphics/Primitives/RectangleF.cs
Labels: area:graphics, size/M

#4546 Fix front-to-back incorrectly shrinking negative-sized draw rectangles
  osu.Framework.Tests/Polygons/ConvexPolygonClippingTest.cs
  osu.Framework.Tests/Visual/Containers/TestSceneFrontToBackBox.cs
  osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
  osu.Framework/Utils/ConvexPolygonClipper.cs
Labels: area:graphics, size/L

#4548 Fix deadlock if disposing a `GameHost` which was never `Run()`
  osu.Framework.Tests/IO/BackgroundGameHeadlessGameHost.cs
  osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:threading, size/M

#4551 Fix TrackVirtual seeks failing in unexpected ways
  osu.Framework.Tests/Audio/TrackVirtualTest.cs
  osu.Framework/Audio/Track/TrackVirtual.cs
Labels: area:clocks, size/M

#4553 Set more appropriate time limits for GH Actions workflows
  .github/workflows/ci.yml
  .github/workflows/report-nunit.yml
Labels: area:tooling, size/XS

#4549 Avoid running exit sequence when it has already been run once
  osu.Framework/Platform/GameHost.cs
Labels: area:threading, size/M

#4554 Add factory method creating `BindableWithCurrent`s depending on the value type
  osu.Framework.Tests/Bindables/BindableWithCurrentTest.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Bindables/BindableNumberWithCurrent.cs
  osu.Framework/Bindables/BindableWithCurrent.cs
  osu.Framework/Bindables/IBindableWithCurrent.cs
  osu.Framework/Utils/Validation.cs
Labels: area:bindable, size/M, type:code-quality

#4547 Expose virtual method in `MarkdownImage`
  osu.Framework/Graphics/Containers/Markdown/MarkdownImage.cs
Labels: size/M
