Repository ppy/osu-framework, pull requests merged in 2021-08, with the labels that each got.

#4645 Replace enum localisation mapper with general `LocalisableDescription` attribute
  osu.Framework.Benchmarks/BenchmarkLocalisableDescription.cs
  osu.Framework.Tests/Localisation/LocalisableDescriptionAttributeTest.cs
  osu.Framework.Tests/Localisation/LocalisableEnumAttributeTest.cs
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Localisation/EnumLocalisationMapper.cs
  osu.Framework/Localisation/LocalisableDescriptionAttribute.cs
  osu.Framework/Localisation/LocalisableEnumAttribute.cs
Labels: area:localisation, size/L

#4650 Add `DocumentNew` platform binding
  osu.Framework/Input/PlatformAction.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
Labels: area:input, size/XS

#4649 Rename `Drawable.Click` to `Drawable.TriggerClick` to avoid naming conflict
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: size/S, type:testing

#4652 Add the ability to actuate `PlatformAction`s via `ManualInputManager`
  osu.Framework.Tests/Visual/Testing/TestSceneManualInputManagerTestScene.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: size/L, type:testing

#4651 Disable SpriteText assertion on cyclic computation
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: area:drawable, size/XS

#4646 Implement shader for SaturationValueSelector
  osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
  osu.Framework/Resources/Shaders/sh_SaturationSelectorBackground.fs
  osu.Framework/Resources/Shaders/sh_SaturationSelectorBackgroundRounded.fs
Labels: area:UI, size/L

#4291 Switch audio subsystem to use BassMix
  osu.Framework.Android/arm64-v8a/libbass.so
  osu.Framework.Android/arm64-v8a/libbassmix.so
  osu.Framework.Android/armeabi-v7a/libbass.so
  osu.Framework.Android/armeabi-v7a/libbassmix.so
  osu.Framework.Android/x86/libbass.so
  osu.Framework.Android/x86/libbassmix.so
  osu.Framework.NativeLibs/runtimes/linux-x64/native/libbass.so
  osu.Framework.NativeLibs/runtimes/linux-x64/native/libbassmix.so
  osu.Framework.NativeLibs/runtimes/linux-x86/native/libbass.so
  osu.Framework.NativeLibs/runtimes/linux-x86/native/libbassmix.so
  osu.Framework.NativeLibs/runtimes/osx-x64/native/libbass.dylib
  osu.Framework.NativeLibs/runtimes/osx-x64/native/libbass_fx.dylib
  osu.Framework.NativeLibs/runtimes/osx-x64/native/libbassmix.dylib
  osu.Framework.NativeLibs/runtimes/win-x64/native/bass.dll
  osu.Framework.NativeLibs/runtimes/win-x64/native/bassmix.dll
  osu.Framework.NativeLibs/runtimes/win-x86/native/bass.dll
  osu.Framework.NativeLibs/runtimes/win-x86/native/bassmix.dll
  osu.Framework.Tests/Audio/BassAudioMixerTest.cs
  osu.Framework.Tests/Audio/BassTestComponents.cs
  osu.Framework.Tests/Audio/SampleBassInitTest.cs
  osu.Framework.Tests/Audio/SampleBassTest.cs
  osu.Framework.Tests/Audio/TrackBassTest.cs
  osu.Framework.Tests/Visual/Audio/TestSceneAudioMixer.cs
  osu.Framework.iOS.props
  osu.Framework.iOS/app.config
  osu.Framework.iOS/libbass.a
  osu.Framework.iOS/libbass_fx.a
  osu.Framework.iOS/libbassmix.a
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/BassAmplitudeProcessor.cs
  osu.Framework/Audio/BassUtils.cs
  osu.Framework/Audio/Mixing/AudioMixer.cs
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
  osu.Framework/Audio/Mixing/Bass/IBassAudioChannel.cs
  osu.Framework/Audio/Mixing/IAudioChannel.cs
  osu.Framework/Audio/Mixing/IAudioMixer.cs
  osu.Framework/Audio/Sample/SampleBass.cs
  osu.Framework/Audio/Sample/SampleBassFactory.cs
  osu.Framework/Audio/Sample/SampleChannel.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
  osu.Framework/Audio/Sample/SampleStore.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Audio/Track/TrackStore.cs
  osu.Framework/Graphics/Audio/DrawableAudioMixer.cs
  osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
  osu.Framework/Graphics/Audio/DrawableSample.cs
  osu.Framework/Graphics/Audio/DrawableTrack.cs
  osu.Framework/Input/FrameworkActionContainer.cs
  osu.Framework/Statistics/FrameStatistics.cs
  osu.Framework/Threading/AudioThread.cs
  osu.Framework/osu.Framework.csproj
Labels: area:audio, size/XXL

#4643 Add audio mixer visualiser (Ctrl+F9)
  osu.Framework.Tests/Visual/Testing/TestSceneAudioMixerVisualiser.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
  osu.Framework/Game.cs
  osu.Framework/Graphics/Visualisation/Audio/AudioChannelDisplay.cs
  osu.Framework/Graphics/Visualisation/Audio/AudioMixerVisualiser.cs
  osu.Framework/Graphics/Visualisation/Audio/MixerDisplay.cs
  osu.Framework/Input/FrameworkActionContainer.cs
Labels: area:audio, size/L

#4657 Interpolate between colours in linear space
  osu.Framework.Tests/Resources/Textures/colour-interpolation.png
  osu.Framework.Tests/Visual/Drawables/TestSceneColourInterpolation.cs
  osu.Framework/Utils/Interpolation.cs
Labels: area:transformations, size/L

#4658 Update bass packages and sync iOS Microsoft.Diagnostics.Runtime reference
  osu.Framework.Android.props
  osu.Framework.iOS.props
  osu.Framework/osu.Framework.csproj
Labels: area:libraries, size/S

#4660 Update ReSharper tools to 2021.2
  .config/dotnet-tools.json
  .github/workflows/ci.yml
  osu-framework.sln.DotSettings
  osu.Framework.Tests/Visual/Containers/TestSceneLifetimeManagementContainer.cs
  osu.Framework.Tests/Visual/Layout/TestSceneScrollableFlow.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Graphics/Textures/ArrayPoolTextureUpload.cs
  osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Labels: type:code-quality, area:tooling, size/L

#4663 Fix collection modified exception in audio mixer visualiser
  osu.Framework/Graphics/Visualisation/Audio/AudioMixerVisualiser.cs
Labels: area:tooling, size/S

#4666 Revert InspectCode to 2020.3.2
  .config/dotnet-tools.json
  .github/workflows/ci.yml
Labels: area:tooling, size/XS

#4664 Fix glyph edge interpolation for non-transparent pixels
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLAtlas.cs
  osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs
Labels: size/L, area:fonts

#4665 Enable inspections for unused method parameters
  osu-framework.sln.DotSettings
  osu.Framework/Host.cs
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/SDL2DesktopWindow.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/Platform/Windows/WindowsMouseHandler.cs
  osu.Framework/Statistics/DotNetRuntimeListener.cs
Labels: type:code-quality, size/S

#4668 Update SDL native libraries
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#4674 Update build status badge to gh actions and add release badge
  README.md
Labels: type:documentation, size/XS

#4672 Migrate track BASS sync usages to mixer infrastructure
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
  osu.Framework/Audio/Track/TrackBass.cs
Labels: area:audio, size/L

#4676 Flush audio mixer on critical BASS operations (seek/stop)
  osu.Framework.Tests/Audio/TrackBassTest.cs
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
Labels: area:audio, size/M

#4675 Update osuTK with android timing precision crash resolution
  osu.Framework.iOS.props
  osu.Framework/osu.Framework.csproj
Labels: area:libraries, size/XS

#4669 Fix joystick/controller axes potentially sticking at non-zero values
  osu.Framework.Tests/Visual/Input/TestSceneJoystick.cs
  osu.Framework/Input/StateChanges/JoystickAxisInput.cs
Labels: area:input, size/M

#4656 Make font store has more flexibility to accept different type of glyph store
  osu.Framework/IO/Stores/FontStore.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/IGlyphStore.cs
Labels: size/M, area:fonts

#4678 Disable audio mixer channel ramping
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
Labels: area:audio, size/XS

#4681 Fix localisation overhead in `SpriteText` / `LocalisedBindableString`
  osu.Framework.Benchmarks/BenchmarkLocalisedBindableString.cs
  osu.Framework/Localisation/LocalisationManager.cs
  osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
Labels: type:performance, area:localisation, size/M

#4680 Pause channels on seek from a stopped state
  osu.Framework.Tests/Audio/BassAudioMixerTest.cs
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
Labels: area:audio, size/M

#4653 Fix startup crash when publishing game in SingleFile and Portable mode
  osu.Framework/RuntimeInfo.cs
Labels: size/XS, type:reliability

#4682 Obsolete `DebugUtils.GetEntryPath()`
  osu.Framework/Development/DebugUtils.cs
Labels: type:code-quality, size/XS

#4684 Reduce amount of audio mixer flushes
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
  osu.Framework/Audio/Track/TrackBass.cs
Labels: type:performance, area:audio, size/M

#4687 Remove abandoned interface from the old localisation system
  osu.Framework/Localisation/IUnicodeBindableString.cs
Labels: type:code-quality, size/M

#4691 Drop float flag from audio mixer
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
Labels: area:audio, size/XS

#4688 Avoid LINQ and array copies in `AggregateBindable`
  osu.Framework.Benchmarks/BenchmarkAggregateBindable.cs
  osu.Framework/Bindables/AggregateBindable.cs
Labels: type:performance, size/M

#4694 Disable timeout in until-steps when debugger attached
  osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
Labels: type:testing, size/XS

#4689 Optimise `GetBoundCopy` to not rely on reflection to create bindable instances
  osu.Framework.Benchmarks/BenchmarkBindableInstantiation.cs
  osu.Framework.Tests/Bindables/BindableBindingTest.cs
  osu.Framework.Tests/Bindables/RangeConstrainedBindableTest.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/BindableBool.cs
  osu.Framework/Bindables/BindableDictionary.cs
  osu.Framework/Bindables/BindableDouble.cs
  osu.Framework/Bindables/BindableFloat.cs
  osu.Framework/Bindables/BindableInt.cs
  osu.Framework/Bindables/BindableList.cs
  osu.Framework/Bindables/BindableLong.cs
  osu.Framework/Bindables/BindableMarginPadding.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Bindables/BindableNumberWithCurrent.cs
  osu.Framework/Bindables/BindableSafeArea.cs
  osu.Framework/Bindables/BindableSize.cs
  osu.Framework/Bindables/BindableWithCurrent.cs
  osu.Framework/Bindables/IBindable.cs
  osu.Framework/Bindables/IBindableDictionary.cs
  osu.Framework/Bindables/IBindableList.cs
  osu.Framework/Bindables/LeasedBindable.cs
  osu.Framework/Bindables/NonNullableBindable.cs
  osu.Framework/Properties/AssemblyInfo.cs
  osu.Framework/Utils/ThrowHelper.cs
Labels: type:performance, area:bindable, size/L

#4695 Use a temporary directory to store unit test headless run files
  osu.Framework.Benchmarks/BenchmarkFontLoading.cs
  osu.Framework.Benchmarks/BenchmarkLocalisedBindableString.cs
  osu.Framework.Tests/Configuration/FrameworkConfigManagerTest.cs
  osu.Framework.Tests/Configuration/InputConfigManagerTest.cs
  osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
  osu.Framework.Tests/IO/BackgroundGameHeadlessGameHost.cs
  osu.Framework.Tests/IO/FontStoreTest.cs
  osu.Framework.Tests/IO/TestDesktopStorage.cs
  osu.Framework.Tests/IO/TestLogging.cs
  osu.Framework.Tests/Platform/ComponentAsyncDisposalTest.cs
  osu.Framework.Tests/Platform/GameHostSuspendTest.cs
  osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
  osu.Framework.Tests/Platform/PortableInstallationTest.cs
  osu.Framework.Tests/Platform/UserInputManagerTest.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Testing/TemporaryNativeStorage.cs
  osu.Framework/Testing/TestRunHeadlessGameHost.cs
  osu.Framework/Testing/TestScene.cs
Labels: type:testing, area:logging, size/L

#4696 Optimise `BeginAbsoluteSequence` recursive case
  osu.Framework.Benchmarks/BenchmarkBeginAbsoluteSequence.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Transforms/TransformSequence.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
Labels: type:performance, size/L

#4701 Mark scrollbar drag-sourced scrolls as user scrolls
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: area:UI, size/XS

#4698 Update SDL and other menial dependencies
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/osu.Framework.csproj
Labels: size/S, dependencies

#4705 Reduce verbosity of STBI errors
  osu.Framework/Graphics/Textures/TextureUpload.cs
Labels: area:logging, size/XS

#4706 Update osuTK again (with android build corrected)
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework/osu.Framework.csproj
Labels: area:libraries, size/XS

#4734 Exclude non-breaking space from fixed width in sprite texts by default
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: area:UI, size/XS

#4737 Allow `HidePopover()` to be called directly on popover containers
  osu.Framework.Tests/Visual/UserInterface/TestScenePopoverContainer.cs
  osu.Framework/Extensions/PopoverExtensions.cs
Labels: area:UI, size/S

#4739 Improve code quality of `.ToLocalisableString()` extension
  osu.Framework/Extensions/LocalisationExtensions/LocalisableStringExtensions.cs
  osu.Framework/Localisation/LocalisableFormattableString.cs
  osu.Framework/Localisation/LocalisableStringExtensions.cs
Labels: type:code-quality, area:localisation, size/M, type:reliability

#4728 Fix `FrameTimeDisplay` delegate leakage
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Statistics/FrameStatistics.cs
  osu.Framework/Statistics/PerformanceMonitor.cs
Labels: type:performance, size/M

#4735 Refactor tooltip test scene to assert behaviour rather than visual only
  osu.Framework.Tests/Visual/UserInterface/TestSceneTooltip.cs
Labels: type:testing, area:UI, size/L

#4729 Add type arguments to `CustomizableTextContainer` and `TextFlowContainer`
  osu.Framework/Graphics/Containers/CustomizableTextContainer.cs
  osu.Framework/Graphics/Containers/TextChunk.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
Labels: type:code-quality, size/M

#4740 Avoid running menu animation code on `Clear()` calls
  osu.Framework/Graphics/UserInterface/Menu.cs
Labels: area:UI, size/S

#4736 Refactor tooltips reusability logic to be dependent on the type and simplify for use cases
  osu.Framework.Tests/Visual/UserInterface/TestSceneTooltip.cs
  osu.Framework/Graphics/Cursor/IHasCustomTooltip.cs
  osu.Framework/Graphics/Cursor/ITooltip.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
Labels: area:UI, size/L
