Repository ppy/osu-framework, pull requests merged in 2021-01, with the labels that each got.

#4132 Improve reliability and performance of GL disposals
  osu.Framework.Tests/Visual/Drawables/TestSceneStressGLDisposal.cs
  osu.Framework/Graphics/OpenGL/GLDisposalQueue.cs
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: area:graphics, size/L, type:performance, type:reliability

#3353 Add interface for leased bindables
  osu.Framework.Tests/Bindables/BindableLeasingTest.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/ILeasedBindable.cs
  osu.Framework/Bindables/LeasedBindable.cs
Labels: area:bindable, size/M

#4135 Enforce thread safety on common transform operations
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
Labels: area:threading, area:transformations, size/L

#4136 Fix potential crash on shutdown due to thread race condition
  osu.Framework/Platform/ThreadRunner.cs
  osu.Framework/Threading/GameThread.cs
Labels: size/S, type:reliability

#4137 Update references to current year
  Directory.Build.props
  LICENCE
  osu.Framework/Graphics/Sprites/Sprite.cs
Labels: size/XS, type:code-quality, type:documentation

#4142 Close MIDI devices when disposing of / disabling MIDI input handler
  osu.Framework/Input/Handlers/Midi/MidiInputHandler.cs
Labels: area:input, size/S

#4143 Fix `GetLoadableTypes()` extension potentially including null `Type` instances
  osu.Framework/Extensions/ExtensionMethods.cs
Labels: size/XS, type:reliability

#4103 Add filtering mode support to FontStore
  osu.Framework/IO/Stores/FontStore.cs
Labels: area:fonts, size/S

#4146 Update osuTK package
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#4144 Add IKeyBinding interface type for flexibility in key bindings
  osu.Framework.Tests/Input/KeybindingInputTest.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingInputQueueChange.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs
  osu.Framework/Input/Bindings/IKeyBinding.cs
  osu.Framework/Input/Bindings/KeyBinding.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Bindings/KeyBindingExtensions.cs
  osu.Framework/Input/FrameworkActionContainer.cs
  osu.Framework/Input/PlatformActionContainer.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: area:input, size/M, type:code-quality

#4151 Fix possible GlobalStatistics thread races
  osu.Framework/Graphics/Performance/GlobalStatisticsDisplay.cs
  osu.Framework/Statistics/GlobalStatistics.cs
Labels: size/M, type:reliability

#4012 Target .NET 5
  .config/dotnet-tools.json
  SampleGame.Desktop/SampleGame.Desktop.csproj
  build/Desktop.proj
  global.json
  osu-framework.sln
  osu-framework.sln.DotSettings
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj
  osu.Framework.Tests/Bindables/BindableListTest.cs
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Performance/LifetimeEntryManager.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/Statistics/BackgroundStackTraceCollector.cs
  osu.Framework/Testing/DynamicClassCompiler.cs
  osu.Framework/Testing/RoslynTypeReferenceBuilder.cs
  osu.Framework/osu.Framework.csproj
Labels: size/M

#4152 Update native libs package to net5.0 supporting version
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#4154 Update .NET SDK requirements in README
  README.md
Labels: size/XS

#4155 Correct documentation typos
  osu.Framework/Bindables/IBindableList.cs
  osu.Framework/Graphics/Containers/Container.cs
  osu.Framework/Graphics/Sprites/SpriteIcon.cs
Labels: size/XS, type:documentation

#4139 Fix playing back SampleChannels ending previous playbacks
  osu.Framework.Tests/Audio/AudioComponentTest.cs
  osu.Framework.Tests/Visual/Audio/TestSceneSampleAmplitudes.cs
  osu.Framework.Tests/Visual/Audio/TestSceneSamples.cs
  osu.Framework/Audio/Sample/ISampleChannel.cs
  osu.Framework/Audio/Sample/ISampleStore.cs
  osu.Framework/Audio/Sample/SampleChannelBass.cs
  osu.Framework/Audio/Sample/SampleStore.cs
Labels: area:audio, size/M

#4156 Attempt to fix macOS crash
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: platform:macOS, size/XS

#4157 Change paths to match dotnet 5.0 for Rider and VSCode
  .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/Benchmarks.xml
  .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/SampleGame.xml
  .idea/.idea.osu-framework.Desktop/.idea/runConfigurations/VisualTests.xml
  .vscode/launch.json
  osu.Framework.Templates/templates/template-empty/.idea/.idea.TemplateGame.Desktop/.idea/runConfigurations/TemplateGame_Desktop.xml
  osu.Framework.Templates/templates/template-empty/.idea/.idea.TemplateGame.Desktop/.idea/runConfigurations/TemplateGame_Tests.xml
  osu.Framework.Templates/templates/template-empty/.vscode/launch.json
  osu.Framework.Templates/templates/template-empty/TemplateGame.Desktop/TemplateGame.Desktop.csproj
  osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/TemplateGame.Game.Tests.csproj
  osu.Framework.Templates/templates/template-empty/TemplateGame.Game/TemplateGame.Game.csproj
  osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
  osu.Framework.Templates/templates/template-flappy/.idea/.idea.FlappyDon.Desktop/.idea/runConfigurations/FlappyDon_Desktop.xml
  osu.Framework.Templates/templates/template-flappy/.idea/.idea.FlappyDon.Desktop/.idea/runConfigurations/FlappyDon_Tests.xml
  osu.Framework.Templates/templates/template-flappy/.vscode/launch.json
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Desktop/FlappyDon.Desktop.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/FlappyDon.Game.Tests.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDon.Game.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
Labels: area:tooling, size/L

#4160 Extend render buffer to use all GL internal formats
  osu.Framework/Graphics/OpenGL/Buffers/BufferFormatExtensions.cs
  osu.Framework/Graphics/OpenGL/Buffers/RenderBuffer.cs
Labels: area:graphics, size/L

#4158 Fix video looping failing when frames are in available post-seek
  osu.Framework/Graphics/Video/Video.cs
Labels: area:video, size/S

#4166 Expose IWindow.Resized event
  osu.Framework/Platform/IWindow.cs
  osu.Framework/Platform/OsuTKWindow.cs
Labels: size/S

#4165 Fix key combination display ordering
  osu.Framework.Tests/Input/KeyCombinationTest.cs
  osu.Framework/Extensions/EnumExtensions/EnumExtensions.cs
  osu.Framework/Input/Bindings/InputKey.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
  osu.Framework/Utils/HasOrderedElementsAttribute.cs
  osu.Framework/Utils/OrderAttribute.cs
Labels: area:input, size/L

#4171 Stop handling unobserved exceptions
  osu.Framework.Tests/IO/TestLogging.cs
  osu.Framework/Platform/GameHost.cs
Labels: size/L, type:reliability

#4172 Drop type constraints on `EnumExtensions` methods
  osu.Framework/Extensions/EnumExtensions/EnumExtensions.cs
Labels: size/XS, type:compatibility

#3630 Fix test cursor not receiving press event when masked away
  osu.Framework.Tests/Visual/Testing/TestSceneManualInputManagerTestScene.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
  osu.Framework/Testing/Input/TestCursorContainer.cs
Labels: area:input, size/L, type:testing

#4140 Fix track not considered complete when reaching beyond length
  osu.Framework.Tests/Audio/TrackBassTest.cs
  osu.Framework/Audio/AudioComponent.cs
  osu.Framework/Audio/Track/Track.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Audio/Track/TrackVirtual.cs
Labels: area:audio, size/L

#4175 Fix framework templates not updated with API changes
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/Elements/Bird.cs
Labels: size/XS
