Repository ppy/osu-framework, pull requests merged in 2021-09, with the labels that each got.

#4743 Fix `GetBackwardWordAmount()` going back two words if the last word is only one character long
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: area:UI, size/M

#4749 Reduce video decode overhead after reaching end of stream
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: type:performance, size/L, area:video

#4750 Fix video stopping playback permanent when reaching end of stream
  osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs
  osu.Framework/Graphics/Video/Video.cs
Labels: size/M, area:video

#4758 Add introduction to README for users looking to use the framework, not work on it
  README.md
Labels: type:code-quality, size/S

#4759 Fix duplicated section in readme
  README.md
Labels: size/S

#4757 Fix user storage potentially losing true existing install directory
  osu.Framework.Android/AndroidGameHost.cs
  osu.Framework.Tests/Platform/UserStorageLookupTest.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/HeadlessGameHost.cs
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/Testing/TestRunHeadlessGameHost.cs
Labels: size/L, area:platform

#4751 Fix video decode running before start time
  osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs
  osu.Framework/Graphics/Animations/AnimationClockComposite.cs
  osu.Framework/Graphics/Video/Video.cs
Labels: type:performance, size/M, area:video

#4763 Improve headless test run efficiency
  osu.Framework/Platform/HeadlessGameHost.cs
  osu.Framework/Testing/TestBrowserTestRunner.cs
  osu.Framework/Testing/TestSceneTestRunner.cs
Labels: type:performance, type:testing, size/M

#4764 Add better documentation and handling of update rate extremities
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Statistics/PerformanceMonitor.cs
  osu.Framework/Threading/GameThread.cs
  osu.Framework/Timing/ThrottledFrameClock.cs
Labels: type:code-quality, size/M

#4756 Let `TabControl` always sort initial selection if auto sort is on
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
Labels: area:UI, size/S

#4765 Add a note warning against using spaces/hyphens when consuming templates
  osu.Framework.Templates/README.md
Labels: area:tooling, size/XS

#4766 Add benchmarks testing overhead of drawable load process
  osu.Framework.Benchmarks/BenchmarkDrawableLoad.cs
Labels: type:performance, size/L

#4769 Mark `GetClipboard()` as possibly returning null
  osu.Framework/Platform/GameHost.cs
Labels: type:code-quality, size/XS

#4772 Fix double disposal of `ThreadedTaskScheduler` throwing an exception
  osu.Framework.Tests/Threading/ThreadedTaskSchedulerTest.cs
  osu.Framework/Threading/ThreadedTaskScheduler.cs
Labels: size/S, type:reliability

#4775 Avoid GL crash from vertex buffer index upload overflow
  osu.Framework/Graphics/Batches/QuadBatch.cs
  osu.Framework/Graphics/OpenGL/Buffers/QuadVertexBuffer.cs
Labels: size/S, type:reliability

#4771 Add flow for testing a nested game instance inside a `TestScene`
  osu.Framework.Tests/Visual/Testing/TestSceneNestedGame.cs
  osu.Framework/Testing/TestScene.cs
Labels: type:testing, size/L

#4774 Align `TextBuilder` characters by their baselines during addition/removal
  osu.Framework.Benchmarks/BenchmarkTextBuilder.cs
  osu.Framework.Tests/Text/TextBuilderTest.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/IO/Stores/FontStore.cs
  osu.Framework/IO/Stores/GlyphStore.cs
  osu.Framework/IO/Stores/IGlyphStore.cs
  osu.Framework/Text/CharacterGlyph.cs
  osu.Framework/Text/ICharacterGlyph.cs
  osu.Framework/Text/TextBuilder.cs
  osu.Framework/Text/TextBuilderGlyph.cs
  osu.Framework/Text/TexturedCharacterGlyph.cs
Labels: area:graphics, size/L, area:fonts

#2601 Use `UIEvent`s in `IKeyBindingHandler<T>`
  osu.Framework.Tests/Input/KeyBindingInputTest.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingInputQueueChange.cs
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingsGrid.cs
  osu.Framework/Game.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/DropdownHeader.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Input/Bindings/IKeyBindingHandler.cs
  osu.Framework/Input/Bindings/IScrollBindingHandler.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Events/KeyBindingEvent.cs
  osu.Framework/Input/Events/KeyBindingPressEvent.cs
  osu.Framework/Input/Events/KeyBindingReleaseEvent.cs
  osu.Framework/Input/Events/KeyBindingScrollEvent.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: area:input, area:drawable, size/L

#4777 Flush all stream writes on dispose to avoid potential disk write failures
  osu.Framework/Platform/FlushingStream.cs
  osu.Framework/Platform/NativeStorage.cs
Labels: size/M, type:reliability

#4780 Publicly expose `SlimReadOnlyListWrapper.Count`
  osu.Framework/Lists/SlimReadOnlyListWrapper.cs
Labels: size/XS

#4781 Avoid throwing errors on failure to flush stream
  osu.Framework/Platform/FlushingStream.cs
Labels: size/S, type:reliability, area:storage

#4782 Reduce benchmark nesting level to avoid `StackOverflow` during test runs
  osu.Framework.Benchmarks/BenchmarkDrawableLoad.cs
Labels: type:testing, size/XS

#4778 Add ability for `SearchContainer` to match even when letters are missing
  osu.Framework.Tests/Visual/UserInterface/TestSceneSearchContainer.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
Labels: area:UI, size/M

#4785 Tidy up some logic surrounding `TypePerformanceMonitor`
  osu.Framework.Tests/Visual/Testing/TestSceneGlobalStatisticsDisplay.cs
  osu.Framework/Statistics/TypePerformanceMonitor.cs
Labels: type:code-quality, size/M

#4786 Fix test execution running indefinitely after exception thrown in asynchronous load thread
  osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
  osu.Framework/Platform/GameHost.cs
Labels: size/M, type:reliability

#4789 Replace BassAudioMixer effects in-place
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
Labels: area:audio, size/S

#4790 Fix inconsistencies in `KeyCombination.getReadableKey()`
  osu.Framework/Input/Bindings/KeyCombination.cs
Labels: size/M

#4787 Fix `windowPositionX/Y` being reset to `0.5` on startup
  osu.Framework/Platform/SDL2DesktopWindow.cs
Labels: size/XS, area:platform

#4791 Fix incorrect variable usage when switching threading mode
  osu.Framework.Tests/Visual/Platform/TestSceneExecutionModes.cs
  osu.Framework/Platform/ThreadRunner.cs
Labels: area:threading, size/S

#4792 Fix `ExecutionMode` potentially changing between equality and set calls
  osu.Framework/Platform/ThreadRunner.cs
Labels: size/XS, type:reliability

#4795 Fix TestSceneTextures test failures
  osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
Labels: type:testing, size/M

#4796 Fix TestSceneDelayedLoadUnloadWrapper test failures
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
Labels: type:testing, size/S

#4794 Fix CI failures due to file access denied to log files
  osu.Framework.Tests/Visual/Platform/TestSceneResourceStores.cs
Labels: type:testing, size/S

#4797 Fix another potential DLUW test failure
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
Labels: type:testing, size/XS

#4793 Remove SQLite specific methods from framework `Storage` classes
  osu.Framework/Platform/NativeStorage.cs
  osu.Framework/Platform/Storage.cs
Labels: type:code-quality, size/S

#4799 Disable intermittently-failing test for now
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
Labels: type:testing, size/XS

#4798 Remove online requirements from TestSceneTextures
  osu.Framework.Tests/Visual/Sprites/TestSceneTextures.cs
Labels: type:testing, size/M

#4783 Update `IsPrimaryInstance` on first access rather than after `GameHost.Run`
  osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Platform/GameHost.cs
Labels: size/M, type:reliability

#4784 Add global mutex on `GameHost` running state
  osu.Framework/Platform/GameHost.cs
Labels: type:testing, size/XS, type:reliability
