Repository ppy/osu-framework, pull requests merged in 2021-05, with the labels that each got.

#4425 Fix Test Coverage Reporting
  .github/workflows/ci.yml
  .github/workflows/report-nunit.yml
  osu.Framework.Tests/osu.Framework.Tests.csproj
Labels: area:tooling, size/M

#4428 Update SDL2 version
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#4427 Allow setting the startup thread mode via environment variable for test runs
  osu.Framework/Platform/HeadlessGameHost.cs
  osu.Framework/Platform/ThreadRunner.cs
Labels: size/XS, type:testing

#4431 Fix culture changes not working when single-threaded
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/ThreadRunner.cs
Labels: area:localisation, size/S, type:reliability

#4433 Fix SampleChannels with zero frequency not playing in single-threaded execution
  osu.Framework/Audio/Sample/SampleChannelBass.cs
Labels: area:audio, size/XS

#4432 Fix race condition in gamehost suspension test
  osu.Framework.Tests/Platform/GameHostSuspendTest.cs
Labels: area:threading, size/S

#4436 Remove early return before bass init
  osu.Framework/Audio/AudioManager.cs
Labels: area:audio, size/XS, type:testing

#4430 Run Test Job as Matrix
  .github/workflows/ci.yml
  .github/workflows/report-nunit.yml
Labels: area:tooling, size/M

#4437 Fix sample channel test failing intermittently
  osu.Framework.Tests/Visual/Audio/TestSceneSampleChannels.cs
Labels: area:audio, size/S, type:testing

#4443 Change `CreateTextFlow` to virtual method in `MarkdownTableCell`
  osu.Framework/Graphics/Containers/Markdown/MarkdownTableCell.cs
Labels: area:drawable, size/XS, type:code-quality

#4441 Remove DLW's special lifetime handling
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadWrapper.cs
  osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
Labels: area:drawable, size/L

#4438 Split Pack Tasks Entirely
  .github/workflows/ci.yml
  .github/workflows/deploy-nativelibs.yml
  .github/workflows/deploy-pack.yml
  .github/workflows/report-nunit.yml
Labels: area:tooling, size/L

#4404 Abstractify bindable number constraints logic and use for `BindableSize`
  osu.Framework.Tests/Bindables/BindableNumberTest.cs
  osu.Framework.Tests/Bindables/RangeConstrainedBindableTest.cs
  osu.Framework/Bindables/BindableMarginPadding.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Bindables/BindableSize.cs
  osu.Framework/Bindables/RangeConstrainedBindable.cs
Labels: area:bindable, size/XL

#4393 Fix `InputHandler`s being initialised before enabled state is read from config
  osu.Framework/Platform/GameHost.cs
Labels: area:input, size/S

#4445 Keep anchor and origin when wrapping drawable via `ContainerExtensions.Wrap`
  osu.Framework/Graphics/Containers/ContainerExtensions.cs
Labels: area:drawable, size/XS

#4450 Fix incorrect comparison in `Dropdown` resulting in deselection of valid selection
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
Labels: area:UI, size/M

#4452 Run Compile Step with `-warnaserror` flag
  .github/workflows/ci.yml
Labels: size/XS

#4167 Fix ModelBackedDrawable not applying transforms on reloaded wrapper
  osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawableWithUnloading.cs
  osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
Labels: area:drawable, size/L

#4453 Remove using arbitrary acronyms in code/comments
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawableWithUnloading.cs
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
  osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs
Labels: size/S, type:code-quality, type:documentation

#4454 Reword xmldocs of Origin* properties
  osu.Framework/Graphics/Drawable.cs
Labels: area:drawable, size/S, type:documentation

#4455 Add BindableDictionary<TKey, TValue>
  osu.Framework.Tests/Bindables/BindableDictionaryTest.cs
  osu.Framework/Bindables/BindableDictionary.cs
  osu.Framework/Bindables/BindableList.cs
  osu.Framework/Bindables/IBindableDictionary.cs
  osu.Framework/Bindables/NotifyDictionaryChangedEventArgs.cs
Labels: area:bindable, size/XXL

#4460 Fix incorrect GetParentScreen()/GetChildScreen() values for screens not in stack
  osu.Framework.Tests/Lists/TestEnumerableExtensions.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
  osu.Framework/Extensions/IEnumerableExtensions/EnumerableExtensions.cs
  osu.Framework/Screens/ScreenStack.cs
Labels: area:screens, size/M

#4459 Fix `TranslatableString.Format` null ref when no languages are added to `LocalisationManager`
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework/Localisation/LocalisationManager.cs
  osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs
  osu.Framework/Localisation/TranslatableString.cs
Labels: area:localisation, size/M

#4458 Fix test scene restoring volume at an unsafe point in execution
  osu.Framework/Graphics/UserInterface/SliderBar.cs
  osu.Framework/Testing/TestSceneTestRunner.cs
Labels: area:threading, size/S

#4462 Flush framebuffer after FBO bind on macOS
  osu.Framework/Graphics/OpenGL/GLWrapper.cs
Labels: area:graphics, size/XS

#4461 Populate connected controllers after SDL init.
  osu.Framework/Platform/SDL2DesktopWindow.cs
Labels: area:input, size/M

#4468 Disable dotnet-format from running on CI
  .github/workflows/ci.yml
Labels: area:tooling, size/XS, type:reliability

#4467 Fix intermittent test failures
  osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneModelBackedDrawableWithUnloading.cs
Labels: size/XS, type:testing

#4466 Fix DelayedLoadUnloadWrapper asserting incorrectly
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
  osu.Framework/Graphics/Containers/DelayedLoadUnloadWrapper.cs
Labels: area:drawable, size/M

#4469 Fix audio devices not working after being disconnected then reconnected
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Threading/AudioThread.cs
Labels: size/S

#4470 Add `LifetimeChanged` event to `LifetimeEntry`
  osu.Framework/Graphics/Performance/LifetimeEntry.cs
  osu.Framework/Graphics/Performance/LifetimeEntryManager.cs
Labels: size/S

#4472 Disable relative mode only when leaving the window
  osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
Labels: area:input, size/S

#4473 Fix TextureAtlas generating mipmaps when requested not to
  osu.Framework/Graphics/Textures/TextureStore.cs
Labels: area:graphics, size/XS

#4457 Add support for `TestCaseSourceAttribute` in test scenes
  osu.Framework.Tests/Visual/Testing/TestSceneDerivedTestWithDerivedSource.cs
  osu.Framework.Tests/Visual/Testing/TestSceneTestWithExternalSource.cs
  osu.Framework.Tests/Visual/Testing/TestSceneTestWithSource.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: size/L, type:testing
