Repository ppy/osu-framework, pull requests merged in 2022-12, with the labels that each got.

#5558 Fix inconsistent body style inspection
  osu.Framework.SourceGeneration/Common/Emitters/DependenciesFileEmitter.cs
Labels: type:code-quality, size/S

#5560 Rework source generator to promote memoisation
  osu.Framework.SourceGeneration/Common/Emitters/DependenciesFileEmitter.cs
  osu.Framework.SourceGeneration/Common/GeneratorClassCandidate.cs
  osu.Framework.SourceGeneration/Common/SyntaxHelpers.cs
  osu.Framework.SourceGeneration/Roslyn3.11/DependencyInjectionSourceGenerator.cs
  osu.Framework.SourceGeneration/Roslyn3.11/GeneratorClassCandidateComparer.cs
  osu.Framework.SourceGeneration/Roslyn3.11/osu.Framework.SourceGeneration.Roslyn3.11.csproj
  osu.Framework.SourceGeneration/Roslyn4.0/DependencyInjectionSourceGenerator.cs
  osu.Framework.SourceGeneration/Roslyn4.0/SyntaxTarget.cs
  osu.Framework.SourceGeneration/Roslyn4.0/SyntaxTargetNameComparer.cs
  osu.Framework.SourceGeneration/Roslyn4.0/osu.Framework.SourceGeneration.Roslyn4.0.csproj
Labels: type:performance, area:dependency-injection, size/L

#5561 Bump source generator package
  osu.Framework/osu.Framework.csproj
Labels: size/XS, dependencies

#5564 Bump `dorny/test-reporter` action to 1.6.0
  .github/workflows/report-nunit.yml
Labels: size/XS, dependencies

#5562 Add multi phase source generator test
  osu.Framework.SourceGeneration.Tests/AbstractGeneratorTests.cs
  osu.Framework.SourceGeneration.Tests/DependencyInjectionMultiPhaseSourceGeneratorTests.cs
  osu.Framework.SourceGeneration.Tests/DependencyInjectionSourceGeneratorTests.cs
  osu.Framework.SourceGeneration.Tests/GeneratorTestHelper.cs
  osu.Framework.SourceGeneration.Tests/Resources/GeneratorCached/Generated/g_A_Dependencies.0.txt
  osu.Framework.SourceGeneration.Tests/Resources/GeneratorCached/Generated/g_A_Dependencies.1.txt
  osu.Framework.SourceGeneration.Tests/Resources/GeneratorCached/Sources/A.0.txt
  osu.Framework.SourceGeneration.Tests/Resources/GeneratorCached/Sources/A.1.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPartialResolvedMember/Generated/g_DefaultParameters_Dependencies.0.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPartialResolvedMember/Generated/g_DefaultParameters_Dependencies.1.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPartialResolvedMember/Generated/g_DefaultParameters_Dependencies.2.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPartialResolvedMember/Sources/DefaultParameters.0.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPartialResolvedMember/Sources/DefaultParameters.1.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPartialResolvedMember/Sources/DefaultParameters.2.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Generated/g_DifferentFile_Dependencies.0.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Generated/g_DifferentFile_Dependencies.1.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Generated/g_SameFile_Dependencies.0.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Generated/g_SameFile_Dependencies.1.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Sources/DifferentFile_Class.0.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Sources/DifferentFile_Class.1.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Sources/DifferentFile_Interface.0.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Sources/DifferentFile_Interface.1.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Sources/SameFile.0.txt
  osu.Framework.SourceGeneration.Tests/Resources/MultiPhasePartialCachedInterface/Sources/SameFile.1.txt
  osu.Framework.SourceGeneration.Tests/Verifiers/CSharpMultiPhaseSourceGeneratorVerifier.cs
  osu.Framework.SourceGeneration.Tests/Verifiers/CSharpMultiPhaseSourceGeneratorVerifier_Test.cs
  osu.Framework.SourceGeneration.Tests/Verifiers/CSharpSourceGeneratorVerifier.cs
  osu.Framework.SourceGeneration.Tests/osu.Framework.SourceGeneration.Tests.csproj
  osu.Framework.SourceGeneration/Roslyn4.0/DependencyInjectionSourceGenerator.cs
  osu.Framework.SourceGeneration/Roslyn4.0/DependencyInjectionSourceGenerator_GeneratorEvent.cs
  osu.Framework.SourceGeneration/Roslyn4.0/osu.Framework.SourceGeneration.Roslyn4.0.csproj
Labels: type:testing, area:dependency-injection, size/XL

#5567 Update source generator package
  osu.Framework/osu.Framework.csproj
Labels: dependencies

#5571 Remove `IBindable.ToString()` default interface implementations
  osu.Framework/Bindables/IBindable.cs
  osu.Framework/Configuration/IniConfigManager.cs
  osu.Framework/Extensions/FormattableExtensions.cs
Labels: platform:android, size/S

#5572 Fix source generator csproj wildcard
  osu.Framework.SourceGeneration/Build.targets
  osu.Framework.SourceGeneration/pack.sh
Labels: size/S

#5570 Fix broken iOS build configurations of template projects in framework solution
  osu-framework.iOS.slnf
  osu-framework.sln
Labels: area:tooling, size/S

#5573 Retrieve span outside of loop to improve performance of glyph texture creation
  osu.Framework/IO/Stores/RawCachingGlyphStore.cs
Labels: size/XS

#5566 Throw if `SDL_GetNumVideoDisplays()` returns an invalid number
  osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
Labels: size/XS, area:platform, type:reliability

#5577 Fix WhitePixel texture rectangle doesn't respect provided area
  osu.Framework/Graphics/Textures/TextureWhitePixel.cs
Labels: size/XS

#5080 Bring Android framework to .NET 6
  .github/workflows/ci.yml
  .github/workflows/deploy-pack.yml
  SampleGame.Android/AndroidManifest.xml
  SampleGame.Android/SampleGame.Android.csproj
  build.ps1
  build.sh
  build/build.cake
  osu.Framework.Android.props
  osu.Framework.Android/AndroidGameActivity.cs
  osu.Framework.Android/AndroidGameView.cs
  osu.Framework.Android/Graphics/Video/AndroidVideoDecoder.cs
  osu.Framework.Android/Input/AndroidInputHandler.cs
  osu.Framework.Android/Input/AndroidJoystickHandler.cs
  osu.Framework.Android/Input/AndroidMouseHandler.cs
  osu.Framework.Android/Input/AndroidTouchHandler.cs
  osu.Framework.Android/app.config
  osu.Framework.Android/global.json
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj
  osu.Framework.NativeLibs/runtimes/android/native/_._
  osu.Framework.Tests.Android/AndroidManifest.xml
  osu.Framework.Tests.Android/osu.Framework.Tests.Android.csproj
  osu.Framework.Tests/Visual/Containers/TestSceneCompositeDrawable.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
  osu.Framework/Graphics/Video/FFmpegFuncs.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/Platform/GameHost.cs
Labels: blocked, area:tooling, platform:android, size/L

#5579 Update SDL2
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#5578 Fix search container filtering too much
  osu.Framework/Graphics/Containers/SearchContainer.cs
Labels: area:drawable, size/XS

#5580 Fix one more case of using AutoGen's `ffmpeg` class for constants
  osu.Framework/Graphics/Video/FFmpegFuncs.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: platform:mobile, size/M, type:reliability

#5574 Guard against attempting to call `OpenUrlExternally` with non-http content
  osu.Framework.Android/AndroidGameHost.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Platform/DesktopGameHost.cs
Labels: size/M

#5584 Fix SDL error on startup caused by setting min/max size before window creation
  osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
Labels: type:code-quality, area:platform

#5586 Add `StringFormatMethod` annotation to `LocalisableString.Format`
  osu.Framework/Localisation/LocalisableString.cs
Labels: area:localisation, size/XS

#5585 Add more logging to `SDL2DesktopWindow`
  osu.Framework/Platform/SDL2DesktopWindow.cs
  osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
Labels: size/XS, area:platform

#5583 Move away from .NET Standard
  .github/workflows/ci.yml
  .github/workflows/deploy-pack.yml
  SampleGame/SampleGame.csproj
  appveyor_deploy.yml
  build/build.cake
  osu.Framework.Templates/osu.Framework.Templates.csproj
  osu.Framework.Templates/templates/template-empty/TemplateGame.Game/TemplateGame.Game.csproj
  osu.Framework.Templates/templates/template-empty/TemplateGame.Resources/TemplateGame.Resources.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDon.Game.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Resources/FlappyDon.Resources.csproj
  osu.Framework.Tests/Visual/Input/TestSceneTabletInput.cs
  osu.Framework/Bindables/BindableDictionary.cs
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Extensions/StreamExtensions.cs
  osu.Framework/Extensions/TypeExtensions/TypeExtensions.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/Input/Handlers/Tablet/AbsoluteTabletMode.cs
  osu.Framework/Input/Handlers/Tablet/ITabletHandler.cs
  osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
  osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
  osu.Framework/Input/Handlers/Tablet/TabletInfo.cs
  osu.Framework/Localisation/CultureInfoHelper.cs
  osu.Framework/Platform/DesktopGameHost.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/Properties/AssemblyInfo.cs
  osu.Framework/RuntimeInfo.cs
  osu.Framework/Statistics/BackgroundStackTraceCollector.cs
  osu.Framework/Statistics/DotNetRuntimeListener.cs
  osu.Framework/osu.Framework.csproj
Labels: area:tooling, size/L

#5483 Add bare-minimum Veldrid renderer implementation
  osu-framework.sln.DotSettings
  osu.Framework.Android/AndroidGameHost.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework/Graphics/OpenGL/GLRenderer.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
  osu.Framework/Graphics/Rendering/IRenderer.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
  osu.Framework/Graphics/Veldrid/VeldridExtensions.cs
  osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/GraphicsSurfaceType.cs
  osu.Framework/Platform/IGraphicsBackend.cs
  osu.Framework/Platform/IGraphicsSurface.cs
  osu.Framework/Platform/IMetalGraphicsSurface.cs
  osu.Framework/Platform/IOpenGLGraphicsSurface.cs
  osu.Framework/Platform/IWindow.cs
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/MacOS/MacOSWindow.cs
  osu.Framework/Platform/OsuTKGraphicsSurface.cs
  osu.Framework/Platform/OsuTKWindow.cs
  osu.Framework/Platform/PassthroughGraphicsBackend.cs
  osu.Framework/Platform/SDL2/SDL2Extensions.cs
  osu.Framework/Platform/SDL2/SDL2GraphicsBackend.cs
  osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs
  osu.Framework/Platform/SDL2DesktopWindow.cs
  osu.Framework/Platform/Windows/WindowsGLRenderer.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/Platform/Windows/WindowsWindow.cs
  osu.Framework/Threading/DrawThread.cs
  osu.Framework/osu.Framework.csproj
Labels: area:graphics, size/XXL

#5587 Fix some issues with Veldrid/Vulkan on Linux
  osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
  osu.Framework/Platform/ILinuxGraphicsSurface.cs
  osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs
  osu.Framework/Platform/SDL2DesktopWindow.cs
Labels: area:graphics, size/M

#5591 Fix osuTK graphics surface causing mobile platforms to crash
  osu.Framework/Platform/OsuTKGraphicsSurface.cs
Labels: area:graphics, platform:mobile, size/S

#5593 Include missing properties to iOS templates
  osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
Labels: area:tooling, platform:iOS, size/S

#5594 Replace project references during packing templates in GH workflow
  .github/workflows/deploy-pack.yml
  osu.Framework.Templates/replace-references.sh
  osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
Labels: area:tooling, size/M

#5589 Add footnote support to Markdown container
  osu.Framework.Tests/Visual/UserInterface/TestSceneMarkdownContainer.cs
  osu.Framework/Graphics/Containers/Markdown/Footnotes/MarkdownFootnote.cs
  osu.Framework/Graphics/Containers/Markdown/Footnotes/MarkdownFootnoteBacklink.cs
  osu.Framework/Graphics/Containers/Markdown/Footnotes/MarkdownFootnoteGroup.cs
  osu.Framework/Graphics/Containers/Markdown/Footnotes/MarkdownFootnoteLink.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownTextFlowContainer.cs
Labels: area:UI, size/L

#5601 Fix bypassing front-to-back not actually disabling depth test
  osu.Framework/Platform/GameHost.cs
Labels: area:graphics, size/XS

#5600 Avoid performing GL occlusion queries on Veldrid
  osu.Framework.Tests/Visual/Containers/TestSceneFrontToBack.cs
Labels: type:testing, area:graphics, size/M

#5592 Work around DirectX libraries blocking iOS from building
  osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
  osu.Framework.iOS.props
  osu.Framework.iOS/osu.Framework.iOS.Workarounds.targets
  osu.Framework.iOS/osu.Framework.iOS.csproj
  osu.Framework.iOS/stubs/SharpGen.Runtime.COM.dll
  osu.Framework.iOS/stubs/SharpGen.Runtime.dll
  osu.Framework.iOS/stubs/Vortice.DXGI.dll
  osu.Framework.iOS/stubs/Vortice.Direct3D11.dll
  osu.Framework.iOS/stubs/Vortice.DirectX.dll
Labels: area:tooling, platform:iOS, size/M

#5595 Implement Veldrid vertex buffers
  osu.Framework/Graphics/Rendering/Vertices/VertexMemberAttribute.cs
  osu.Framework/Graphics/Veldrid/Batches/VeldridLinearBatch.cs
  osu.Framework/Graphics/Veldrid/Batches/VeldridQuadBatch.cs
  osu.Framework/Graphics/Veldrid/Batches/VeldridVertexBatch.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridIndexData.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridLinearBuffer.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridQuadBuffer.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs
  osu.Framework/Graphics/Veldrid/VeldridExtensions.cs
  osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
  osu.Framework/Graphics/Veldrid/Vertices/VeldridVertexUtils.cs
Labels: area:graphics, size/XL

#5602 Remove unnecessary `yield return` from `getSDLDisplays()` and log errors
  osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
Labels: type:code-quality, size/S

#5603 Fix wrong path separator used in templates pack CI
  .github/workflows/deploy-pack.yml
Labels: area:tooling, size/XS

#5606 Fix iOS workflow failing to restore workloads
  .github/workflows/ci.yml
Labels: area:tooling, size/XS

#5605 Use new ArgumentNullException.ThrowIfNull throw-helper API
  osu.Framework.Android/AndroidGameView.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Bindables/BindableDictionary.cs
  osu.Framework/Bindables/BindableList.cs
  osu.Framework/Bindables/BindableNumberWithCurrent.cs
  osu.Framework/Bindables/BindableWithCurrent.cs
  osu.Framework/Bindables/NonNullableBindable.cs
  osu.Framework/Extensions/ExtensionMethods.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/Container.cs
  osu.Framework/Graphics/Containers/CustomizableTextContainer.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/Performance/LifetimeEntryManager.cs
  osu.Framework/Graphics/Transforms/Transform.cs
  osu.Framework/Graphics/Transforms/Transformable.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
  osu.Framework/IO/Network/WebRequest.cs
  osu.Framework/Lists/SortedList.cs
  osu.Framework/Platform/NativeStorage.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/Threading/Scheduler.cs
Labels: type:code-quality, size/M

#5610 Fix iPad devices not rendering colour pickers and circular progresses/blobs
  osu.Framework/Resources/Shaders/sh_Texture2D.vs
  osu.Framework/Resources/Shaders/sh_Texture3D.vs
Labels: area:graphics, platform:iOS, size/S

#5613 Use generic Enum and CreateDelegate methods
  osu.Framework/Audio/AudioAdjustments.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
  osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
  osu.Framework/Graphics/Transforms/TransformCustom.cs
  osu.Framework/Graphics/Visualisation/DrawableInspector.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/States/TouchState.cs
  osu.Framework/Logging/Logger.cs
  osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
  osu.Framework/RuntimeInfo.cs
  osu.Framework/Statistics/FrameStatistics.cs
  osu.Framework/Utils/Interpolation.cs
Labels: type:code-quality, size/M
