Repository ppy/osu-framework, pull requests merged in 2022-09, with the labels that each got.

#5382 Update `IContainer` interface to add explicit disposal argument on `Remove` methods
  osu.Framework.Benchmarks/BenchmarkDrawableAudioWrapper.cs
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/Elements/Backdrop.cs
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/Elements/Obstacles.cs
  osu.Framework.Tests/Audio/TestSceneDrawableTrack.cs
  osu.Framework.Tests/Containers/TestSceneContainerState.cs
  osu.Framework.Tests/Exceptions/TestAddRemoveExceptions.cs
  osu.Framework.Tests/Input/KeyboardInputTest.cs
  osu.Framework.Tests/Input/MouseInputTest.cs
  osu.Framework.Tests/Visual/Audio/TestSceneAudioMixer.cs
  osu.Framework.Tests/Visual/Containers/TestSceneBufferedContainer.cs
  osu.Framework.Tests/Visual/Containers/TestSceneLifetimeManagementContainer.cs
  osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneComplexBlending.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneDelayedLoadUnloadWrapper.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneDrawNodeDisposal.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneStressGLDisposal.cs
  osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneScreenStack.cs
  osu.Framework/Graphics/Containers/AudioContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/Container.cs
  osu.Framework/Graphics/Containers/CustomizableTextContainer.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
  osu.Framework/Graphics/Containers/IContainer.cs
  osu.Framework/Graphics/Containers/LifetimeManagementContainer.cs
  osu.Framework/Graphics/Containers/ModelBackedDrawable.cs
  osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
  osu.Framework/Graphics/Cursor/TooltipContainer.cs
  osu.Framework/Graphics/DrawableExtensions.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Graphics/Visualisation/Audio/AudioMixerVisualiser.cs
  osu.Framework/Graphics/Visualisation/Audio/MixerDisplay.cs
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
  osu.Framework/Screens/ScreenStack.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/Testing/TestSceneTestRunner.cs
Labels: type:code-quality, area:drawable, size/L

#5385 Pull iOS / android platform detection methods locally to avoid potential usage before ready
  osu.Framework/RuntimeInfo.cs
Labels: size/XS

#5386 Remove "GL" prefix from performance collection type enum
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Statistics/FrameStatistics.cs
Labels: area:tooling, size/XS

#5391 Don't fabricate `UIEvent`s in `TestSceneDropdown`
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
Labels: type:testing, size/M

#5388 Add `unmanaged` constraint to vertex/uniform generic types
  osu.Framework/Graphics/OpenGL/Batches/GLLinearBatch.cs
  osu.Framework/Graphics/OpenGL/Batches/GLQuadBatch.cs
  osu.Framework/Graphics/OpenGL/Batches/GLVertexBatch.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLLinearBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLQuadBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLVertexBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLVertexUtils.cs
  osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyShader.cs
  osu.Framework/Graphics/Rendering/IRenderer.cs
  osu.Framework/Graphics/Rendering/IVertexBatch.cs
  osu.Framework/Graphics/Rendering/Vertices/DepthWrappingVertex.cs
  osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
  osu.Framework/Graphics/Shaders/GlobalUniform.cs
  osu.Framework/Graphics/Shaders/IShader.cs
  osu.Framework/Graphics/Shaders/IUniformWithValue.cs
  osu.Framework/Graphics/Shaders/Uniform.cs
  osu.Framework/Graphics/Shaders/UniformMapping.cs
Labels: type:code-quality, area:graphics, size/M, area:shader

#5387 Update `GlobalPropertyManager` to support registering `IShader`s
  osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyShader.cs
  osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
  osu.Framework/Graphics/Shaders/IShader.cs
  osu.Framework/Graphics/Shaders/IUniform.cs
Labels: type:code-quality, size/M, area:shader

#5392 Improve invalidation/validation performance
  osu.Framework.Benchmarks/BenchmarkInvalidationList.cs
  osu.Framework/Graphics/InvalidationList.cs
Labels: type:performance, size/M, area:layout

#5390 Rename `DepthStencilFunction` to `BufferTestFunction`
  osu.Framework.Tests/Visual/Graphics/TestSceneStencil.cs
  osu.Framework/Graphics/OpenGL/GLUtils.cs
  osu.Framework/Graphics/Rendering/BufferTestFunction.cs
  osu.Framework/Graphics/Rendering/DepthInfo.cs
  osu.Framework/Graphics/Rendering/StencilInfo.cs
Labels: type:code-quality, area:graphics, size/M

#5394 Allow Drawable `Scale` to be exactly zero
  osu.Framework.Tests/Visual/Drawables/TestSceneDrawableScale.cs
  osu.Framework/Graphics/Containers/DrawSizePreservingFillContainer.cs
  osu.Framework/Graphics/DrawInfo.cs
  osu.Framework/Graphics/Drawable.cs
Labels: area:drawable, size/L

#5395 Attempt to fix AppVeyor not publishing .snupkgs
  build/build.cake
Labels: area:tooling, size/XS

#5397 Make `IsPresent` consider `DrawScale` instead of `Scale`
  osu.Framework/Graphics/Drawable.cs
Labels: area:drawable, size/XS

#5396 Throw exception when modifying contents of Container<T> while iterating through it
  osu.Framework.Tests/Containers/TestSceneEnumeratorVersion.cs
  osu.Framework/Graphics/Containers/Container.cs
Labels: size/L, type:reliability

#5400 Mark `TestSceneEnumeratorVersion` as headless
  osu.Framework.Tests/Containers/TestSceneEnumeratorVersion.cs
Labels: type:testing, size/XS

#5401 Fix dropdown selected visual state not being maintained when `Items` are set after `Current`
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
Labels: area:UI, size/S

#5405 Update ReSharper CLI to 2022.2.3
  .config/dotnet-tools.json
  osu.Framework.Tests/Bindables/AggregateBindableTest.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
Labels: area:tooling, size/S, dependencies

#5411 Remove `EnumerateBaseTypes` overhead in `UnbindAllBindables`
  osu.Framework.Benchmarks/BenchmarkUnbindAllBindables.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
Labels: type:performance, size/L

#5410 Preallocate layout members list size to reduce allocations from list resize
  osu.Framework.Benchmarks/BenchmarkDrawableTypeAllocations.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Layout/LayoutMember.cs
Labels: type:performance, size/L

#5409 Fix `PoolableDrawable` prepare call schedules potentially creating overhead if drawable never updated
  osu.Framework/Graphics/Pooling/PoolableDrawable.cs
Labels: type:performance, size/S

#5414 Reduce overhead of `Waveform`
  osu.Framework.Benchmarks/BenchmarkWaveform.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs
  osu.Framework/Audio/Track/Waveform.cs
  osu.Framework/Graphics/Audio/WaveformGraph.cs
Labels: type:performance, size/L

#5418 Fix unbind action caching occurring too late
  osu.Framework/Graphics/Drawable.cs
Labels: size/XS, type:reliability

#5419 Ensure unbind action is always available on request
  osu.Framework/Graphics/Drawable.cs
Labels: area:drawable, size/M

#5420 Close open parenthesis in `README.md`
  README.md
Labels: size/XS

#5404 Introduce base implementation for `IRenderer`
  osu.Framework.Tests/Shaders/TestSceneShaderDisposal.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLFrameBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLLinearBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLQuadBuffer.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLVertexBuffer.cs
  osu.Framework/Graphics/OpenGL/GLRenderer.cs
  osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
  osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
  osu.Framework/Graphics/OpenGL/Textures/GLVideoTexture.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyNativeTexture.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
  osu.Framework/Graphics/Rendering/INativeTexture.cs
  osu.Framework/Graphics/Rendering/IRenderer.cs
  osu.Framework/Graphics/Rendering/IVertexBuffer.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
  osu.Framework/Graphics/Rendering/RendererDisposalQueue.cs
  osu.Framework/Graphics/Shaders/IUniform.cs
  osu.Framework/Graphics/Shaders/IUniformWithValue.cs
  osu.Framework/Graphics/Textures/Texture.cs
  osu.Framework/Graphics/Visualisation/TextureVisualiser.cs
Labels: type:code-quality, area:graphics, size/XXL

#5403 Expose `TextureAtlas.Add()`
  osu.Framework/Graphics/Textures/TextureAtlas.cs
Labels: area:graphics, size/M

#5422 Add support for blending "write mask" in `IRenderer`
  osu.Framework/Graphics/BlendingMask.cs
  osu.Framework/Graphics/OpenGL/GLRenderer.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
  osu.Framework/Graphics/Rendering/IRenderer.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:graphics, size/M

#5424 Unsubscribe from tablet driver events on disposal
  osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
Labels: area:input, size/M, type:reliability

#5425 Fix unsubscription logic not handling null tablet drivers
  osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
  osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
Labels: size/M, type:reliability

#5421 Forward tablet driver output to custom logging target
  osu.Framework.Android/Input/AndroidInputHandler.cs
  osu.Framework.Android/Input/AndroidJoystickHandler.cs
  osu.Framework/Input/Handlers/InputHandler.cs
  osu.Framework/Input/Handlers/Midi/MidiHandler.cs
  osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
  osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
  osu.Framework/Logging/Logger.cs
Labels: area:input, area:logging, size/M

#5383 Fix nested storage lookup check not accounting for case insensitive filesystems
  osu.Framework.Tests/IO/TestDesktopStorage.cs
  osu.Framework/Platform/NativeStorage.cs
Labels: size/M, type:reliability

#5428 Fix potential `null` return to `ArrayPool` in `Waveform`
  osu.Framework/Audio/Track/Waveform.cs
Labels: size/S, type:reliability

#5431 Fix VBO incorrectly flushing on no-op shader bind
  osu.Framework/Graphics/Rendering/Renderer.cs
Labels: type:performance, size/XS

#5434 Expose `ScrollContainer.Target`
  osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: area:UI, size/S

#5432 Always show exclusive fullscreen as enabled on Intel platforms
  osu.Framework/Platform/Windows/IWindowsRenderer.cs
  osu.Framework/Platform/Windows/WindowsGLRenderer.cs
  osu.Framework/Platform/Windows/WindowsGameHost.cs
  osu.Framework/Platform/Windows/WindowsWindow.cs
Labels: area:graphics, size/L, platform:windows
