Repository ppy/osu-framework, pull requests merged in 2022-11, with the labels that each got.

#5496 Fix directory selector breadcrumb flow not correctly wrapping vertically
  osu.Framework/Graphics/UserInterface/BasicDirectorySelectorBreadcrumbDisplay.cs
  osu.Framework/Graphics/UserInterface/DirectorySelectorBreadcrumbDisplay.cs
Labels: area:UI, size/S

#5490 Refactor drawable pool statistics output to make more sense
  osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs
  osu.Framework/Graphics/Pooling/DrawablePool.cs
Labels: type:code-quality, size/L

#5495 Compute CircularBlob's noise position in the DrawNode
  osu.Framework/Graphics/UserInterface/CircularBlob.cs
  osu.Framework/Resources/Shaders/sh_CircularBlob.fs
  osu.Framework/Resources/Shaders/sh_CircularBlobRounded.fs
  osu.Framework/Resources/Shaders/sh_CircularBlobUtils.h
Labels: area:drawable, size/S

#5502 Change game thread prefixes to suffixes
  osu.Framework.Tests/Audio/BassTestComponents.cs
  osu.Framework.Tests/Audio/SampleChannelVirtualTest.cs
  osu.Framework.Tests/Audio/TrackVirtualTest.cs
  osu.Framework/Threading/GameThread.cs
Labels: area:tooling, size/S

#5504 Fix `FrameworkSetting.Locale` not changing `InputThread` culture
  osu.Framework.Tests/Localisation/ThreadCultureTest.cs
  osu.Framework/Platform/ThreadRunner.cs
  osu.Framework/Threading/GameThread.cs
Labels: type:code-quality, area:localisation, size/S

#5427 Fix disabling `UseFullGlyphHeight` does not trim top part of sprite text glyphs
  osu.Framework.Tests/Text/TextBuilderTest.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteText.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteTextTruncate.cs
  osu.Framework/Text/TextBuilder.cs
  osu.Framework/Text/TextBuilderGlyph.cs
Labels: area:UI, size/L

#5505 Default `CurrentCulture` to system culture
  osu.Framework.Tests/Localisation/CultureInfoHelperTest.cs
  osu.Framework.Tests/Localisation/ThreadCultureTest.cs
  osu.Framework/Localisation/CultureInfoHelper.cs
  osu.Framework/Localisation/LocalisationManager.cs
Labels: area:localisation, size/M

#5506 Remove all usage of `Add`/`RemoveMemoryPressure`
  osu.Framework/Graphics/OpenGL/Buffers/GLVertexBuffer.cs
  osu.Framework/Platform/NativeMemoryTracker.cs
Labels: type:performance, size/S

#5501 Use (high resolution) waitable timers on windows when available
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Platform/Windows/Native/Execution.cs
  osu.Framework/Statistics/FrameStatistics.cs
  osu.Framework/Statistics/PerformanceMonitor.cs
  osu.Framework/Threading/GameThread.cs
  osu.Framework/Timing/FramedClock.cs
  osu.Framework/Timing/ThrottledFrameClock.cs
Labels: type:performance, size/L

#5503 Don't yield when game can't keep up
  osu.Framework/Timing/ThrottledFrameClock.cs
Labels: type:performance, size/XS

#5509 Log sources of VBO flushes (aka batching interruptions) to global statistics
  osu.Framework/Graphics/Rendering/FlushBatchSource.cs
  osu.Framework/Graphics/Rendering/IVertexBatch.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
Labels: area:tooling, area:graphics, size/M

#5510 Remove `internal` access modifier from `CompositeDrawable.AddInternal`
  osu.Framework.Tests/Visual/Containers/TestSceneLifetimeManagementContainer.cs
  osu.Framework/Graphics/Animations/AnimationClockComposite.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/Container.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
  osu.Framework/Graphics/Containers/LifetimeManagementContainer.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
  osu.Framework/Graphics/UserInterface/Popover.cs
  osu.Framework/Testing/TestScene.cs
Labels: type:code-quality, size/S

#5511 Fix tool overlays not scaling with DPI / window size
  osu.Framework/Game.cs
Labels: area:tooling, size/S

#5513 Display tool overlays in front on toggle
  osu.Framework/Game.cs
Labels: area:tooling, size/M

#5512 Use rounded fragment shader exclusively
  osu.Framework.Tests/Visual/Sprites/TestSceneTextureUnit.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneVideo.cs
  osu.Framework.Tests/Visual/Sprites/TestVideo.cs
  osu.Framework/Graphics/Audio/WaveformGraph.cs
  osu.Framework/Graphics/BufferedDrawNode.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/ITexturedShaderDrawable.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
  osu.Framework/Graphics/Shaders/GlobalProperty.cs
  osu.Framework/Graphics/Shaders/GlobalPropertyManager.cs
  osu.Framework/Graphics/Shaders/ShaderManager.cs
  osu.Framework/Graphics/Sprites/BufferedContainerView.cs
  osu.Framework/Graphics/Sprites/Sprite.cs
  osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
  osu.Framework/Graphics/TexturedShaderDrawNode.cs
  osu.Framework/Graphics/UserInterface/CircularBlob.cs
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
  osu.Framework/Graphics/UserInterface/HSVColourPicker_HueSelector.cs
  osu.Framework/Graphics/UserInterface/HSVColourPicker_SaturationValueSelector.cs
  osu.Framework/Graphics/Video/VideoSprite.cs
  osu.Framework/Graphics/Video/VideoSpriteDrawNode.cs
  osu.Framework/Resources/Shaders/sh_CircularBlob.fs
  osu.Framework/Resources/Shaders/sh_CircularBlobRounded.fs
  osu.Framework/Resources/Shaders/sh_CircularProgress.fs
  osu.Framework/Resources/Shaders/sh_CircularProgressRounded.fs
  osu.Framework/Resources/Shaders/sh_Colour.fs
  osu.Framework/Resources/Shaders/sh_Colour.vs
  osu.Framework/Resources/Shaders/sh_ColourRounded.fs
  osu.Framework/Resources/Shaders/sh_HueSelectorBackground.fs
  osu.Framework/Resources/Shaders/sh_HueSelectorBackgroundRounded.fs
  osu.Framework/Resources/Shaders/sh_Masking.h
  osu.Framework/Resources/Shaders/sh_SaturationSelectorBackground.fs
  osu.Framework/Resources/Shaders/sh_SaturationSelectorBackgroundRounded.fs
  osu.Framework/Resources/Shaders/sh_Texture.fs
  osu.Framework/Resources/Shaders/sh_TextureRounded.fs
  osu.Framework/Resources/Shaders/sh_Utils.h
  osu.Framework/Resources/Shaders/sh_Video.fs
  osu.Framework/Resources/Shaders/sh_VideoRounded.fs
Labels: size/L, area:shader

#5514 Fix possible NRE in `GetAsync` between `DllResourceStore` and `ResourceStore`
  osu.Framework.Tests/IO/DllResourceStoreTest.cs
  osu.Framework/IO/Stores/DllResourceStore.cs
Labels: size/M, type:reliability

#5516 Fix `Dropdown` calling `GenerateItemText` before it's loaded
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
Labels: area:UI, size/S, type:reliability

#5518 Load genuine font for text builder test in favour of hardcoded glyph numbers
  osu.Framework.Tests/Text/TextBuilderTest.cs
Labels: type:testing, size/L, area:fonts

#5515 Make `IBindable : IFormattable` to allow formatting its value with `InvariantCulture`
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/BindableBool.cs
  osu.Framework/Bindables/BindableDictionary.cs
  osu.Framework/Bindables/BindableDouble.cs
  osu.Framework/Bindables/BindableFloat.cs
  osu.Framework/Bindables/BindableInt.cs
  osu.Framework/Bindables/BindableList.cs
  osu.Framework/Bindables/BindableMarginPadding.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Bindables/BindableSize.cs
  osu.Framework/Bindables/IBindable.cs
  osu.Framework/Configuration/IniConfigManager.cs
Labels: area:bindable, size/M

#5517 Refactor `SpriteIcon` tests to allow slowly adding new icons
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs
Labels: type:testing, size/L

#5522 Small code quality pass on `SDL2DesktopWindow`
  osu.Framework/Platform/SDL2DesktopWindow_Input.cs
  osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
Labels: type:code-quality, area:platform

#5525 Initialise BufferedDrawNode FBOs as late as possible
  osu.Framework/Graphics/BufferedDrawNodeSharedData.cs
Labels: type:performance, area:graphics, size/M

#5520 Refactor and simplify text builder bounds calculation
  osu.Framework.Tests/Text/TextBuilderTest.cs
  osu.Framework/Text/TextBuilder.cs
  osu.Framework/Text/TextBuilderGlyph.cs
Labels: type:code-quality, area:UI, size/L

#5527 Fix incorrect nullability specific on `ITrackableConfigManager`
  osu.Framework/Configuration/Tracking/ITrackableConfigManager.cs
Labels: size/XS

#5533 Fix potentially incorrect implementation of double-locking in `Drawable.Scheduler` retrieval
  osu.Framework/Graphics/Drawable.cs
Labels: type:code-quality, size/S

#5532 Lazy init `AudioAdjustments` in `AdjustableAudioComponent` usage
  osu.Framework/Audio/AdjustableAudioComponent.cs
Labels: type:performance, size/M

#5523 Fix displays sometimes not getting updated and failing assertion
  osu.Framework/Platform/SDL2DesktopWindow_Windowing.cs
Labels: size/XS

#5531 Add `Bindable<T>.CopyTo` and use in `GetUnboundCopy` implementation
  osu.Framework.Benchmarks/BenchmarkBindableInstantiation.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/BindableNumber.cs
  osu.Framework/Bindables/RangeConstrainedBindable.cs
Labels: type:performance, size/M

#5536 Cleanup `LocalisationManager` and related classes
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework/Game.cs
  osu.Framework/Localisation/CaseTransformableString.cs
  osu.Framework/Localisation/CultureInfoHelper.cs
  osu.Framework/Localisation/LocalisationManager.cs
  osu.Framework/Localisation/LocalisationParameters.cs
  osu.Framework/Localisation/RomanisableString.cs
Labels: area:localisation, size/M

#5537 Refactor `LocaleMapping` lookup to require an exact match to `FrameworkSetting.Locale`
  osu.Framework.Tests/Localisation/LocalisationTest.cs
  osu.Framework/Localisation/CultureInfoHelper.cs
  osu.Framework/Localisation/LocalisationManager.cs
Labels: area:localisation, size/L

#5539 Correctly return `AVERROR_EOF` in `VideoDecoder`
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: size/XS, area:video

#5542 Fix wrong range constrained bindable value transferal in `CopyTo()`
  osu.Framework.Tests/Bindables/RangeConstrainedBindableTest.cs
  osu.Framework/Bindables/RangeConstrainedBindable.cs
Labels: area:bindable, size/M

#5534 Silently return rather than throwing when performing mutations on disposed drawables
  osu.Framework.Tests/Containers/TestSceneContainerState.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/Container.cs
Labels: area:tooling, size/S

#5544 Move early return conditions away from CircularProgress and CircularBlob shaders
  osu.Framework/Graphics/UserInterface/CircularBlob.cs
  osu.Framework/Graphics/UserInterface/CircularProgress.cs
  osu.Framework/Resources/Shaders/sh_CircularBlob.fs
  osu.Framework/Resources/Shaders/sh_CircularProgress.fs
Labels: size/S

#5545 Use fully qualified name to ensure uniqueness
  osu.Framework.SourceGeneration.Tests/AbstractGeneratorTests.cs
  osu.Framework.SourceGeneration.Tests/DependencyInjectionSourceGeneratorTests.cs
  osu.Framework.SourceGeneration.Tests/Resources/CommonGenerated/g_osu.Framework.Graphics.Drawable_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/GenericEmptyPartialDrawable/Generated/g_DoubleGeneric{T1, T2}_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/GenericEmptyPartialDrawable/Generated/g_SingleGeneric{T}_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/NestedCachedClass/Generated/[0]g_A_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/NestedCachedClass/Generated/[1]g_A.B_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/PartialNestedClasses/Generated/[0]g_ClassA_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/PartialNestedClasses/Generated/[1]g_ClassA.ClassB_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/TestableDependencyInjectionSourceGenerator.cs
  osu.Framework.SourceGeneration/DependencyInjectionSourceGenerator.cs
Labels: area:tooling, size/M

#5547 Fix incorrect source gen in edge cases of dependency injection
  osu.Framework.SourceGeneration.Tests/DependencyInjectionSourceGeneratorTests.cs
  osu.Framework.SourceGeneration.Tests/Resources/CachedBaseType/Generated/g_BaseType_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/CachedBaseType/Generated/g_DerivedType_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/CachedBaseType/Sources/BaseType.txt
  osu.Framework.SourceGeneration.Tests/Resources/CachedBaseType/Sources/DerivedType.txt
  osu.Framework.SourceGeneration.Tests/Resources/CachedInheritedInterface/Generated/g_CachedInheritedInterface_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/CachedInheritedInterface/Sources/CachedInheritedInterface.txt
  osu.Framework.SourceGeneration.Tests/Resources/PartialBackgroundDependencyLoadedDrawable/Generated/g_NRTNullableReferenceType_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/PartialBackgroundDependencyLoadedDrawable/Generated/g_NRTNullableValueType_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/PartialBackgroundDependencyLoadedDrawable/Generated/g_NullableValueType_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/PartialResolvedMember/Generated/g_NRTNullableReferenceType_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/PartialResolvedMember/Generated/g_NRTNullableValueType_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/PartialResolvedMember/Generated/g_NullableValueType_Dependencies.txt
  osu.Framework.SourceGeneration.Tests/Resources/PartialResolvedNullableBindable/Generated/g_DefaultParameters_Dependencies.txt
  osu.Framework.SourceGeneration/SyntaxContextReceiver.cs
  osu.Framework.SourceGeneration/SyntaxHelpers.cs
Labels: area:dependency-injection, size/L

#5550 Update dependency injection to use incremental source generation
  osu.Framework.SourceGeneration.Tests/Verifiers/CSharpSourceGeneratorVerifier.cs
  osu.Framework.SourceGeneration.Tests/Verifiers/CSharpSourceGeneratorVerifier_Test.cs
  osu.Framework.SourceGeneration.Tests/osu.Framework.SourceGeneration.Tests.csproj
  osu.Framework.SourceGeneration/Analysers/DrawableCodeFixProvider.cs
  osu.Framework.SourceGeneration/Data/BackgroundDependencyLoaderAttributeData.cs
  osu.Framework.SourceGeneration/Data/BackgroundDependencyLoaderParameterData.cs
  osu.Framework.SourceGeneration/Data/CachedAttributeData.cs
  osu.Framework.SourceGeneration/Data/ResolvedAttributeData.cs
  osu.Framework.SourceGeneration/DependencyInjectionSourceGenerator.cs
  osu.Framework.SourceGeneration/Emitters/BackgroundDependencyLoaderEmitter.cs
  osu.Framework.SourceGeneration/Emitters/CachedClassEmitter.cs
  osu.Framework.SourceGeneration/Emitters/CachedInterfaceEmitter.cs
  osu.Framework.SourceGeneration/Emitters/CachedMemberEmitter.cs
  osu.Framework.SourceGeneration/Emitters/DependenciesFileEmitter.cs
  osu.Framework.SourceGeneration/Emitters/ResolvedMemberEmitter.cs
  osu.Framework.SourceGeneration/GeneratorClassCandidate.cs
  osu.Framework.SourceGeneration/SyntaxContextReceiver.cs
  osu.Framework.SourceGeneration/SyntaxHelpers.cs
  osu.Framework.SourceGeneration/osu.Framework.SourceGeneration.csproj
  osu.Framework/osu.Framework.csproj
Labels: area:dependency-injection, size/XL

#5530 Adjust search container logic to address game-side issues with hiding its children
  osu.Framework.Tests/Visual/UserInterface/TestSceneSearchContainer.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
  osu.Framework/Graphics/Containers/IConditionalFilterable.cs
  osu.Framework/Graphics/Containers/IFilterable.cs
  osu.Framework/Graphics/Containers/IHasFilterableChildren.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
  osu.Framework/Testing/Drawables/TestGroupButton.cs
Labels: area:drawable, size/L

#5552 Remove unnecessary caching in dependencies tests
  osu.Framework.Tests/Dependencies/SourceGeneration/CachedAttributeTest.cs
  osu.Framework.Tests/Dependencies/SourceGeneration/CachedModelDependenciesTest.cs
Labels: type:testing, area:dependency-injection, size/XS

#5554 Add Roslyn 3.11 source generator package
  osu-framework.Desktop.slnf
  osu-framework.sln
  osu.Framework.SourceGeneration.Tests/osu.Framework.SourceGeneration.Tests.csproj
  osu.Framework.SourceGeneration/Common/Analysers/DiagnosticRules.cs
  osu.Framework.SourceGeneration/Common/Analysers/DrawableAnalyser.cs
  osu.Framework.SourceGeneration/Common/Analysers/DrawableCodeFixProvider.cs
  osu.Framework.SourceGeneration/Common/Data/BackgroundDependencyLoaderAttributeData.cs
  osu.Framework.SourceGeneration/Common/Data/BackgroundDependencyLoaderParameterData.cs
  osu.Framework.SourceGeneration/Common/Data/CachedAttributeData.cs
  osu.Framework.SourceGeneration/Common/Data/ResolvedAttributeData.cs
  osu.Framework.SourceGeneration/Common/Emitters/BackgroundDependencyLoaderEmitter.cs
  osu.Framework.SourceGeneration/Common/Emitters/CachedClassEmitter.cs
  osu.Framework.SourceGeneration/Common/Emitters/CachedInterfaceEmitter.cs
  osu.Framework.SourceGeneration/Common/Emitters/CachedMemberEmitter.cs
  osu.Framework.SourceGeneration/Common/Emitters/DependenciesFileEmitter.cs
  osu.Framework.SourceGeneration/Common/Emitters/IStatementEmitter.cs
  osu.Framework.SourceGeneration/Common/Emitters/ResolvedMemberEmitter.cs
  osu.Framework.SourceGeneration/Common/GeneratorClassCandidate.cs
  osu.Framework.SourceGeneration/Common/SyntaxHelpers.cs
  osu.Framework.SourceGeneration/Roslyn3.11/DependencyInjectionSourceGenerator.cs
  osu.Framework.SourceGeneration/Roslyn3.11/osu.Framework.SourceGeneration.Roslyn3.11.csproj
  osu.Framework.SourceGeneration/Roslyn4.0/DependencyInjectionSourceGenerator.cs
  osu.Framework.SourceGeneration/Roslyn4.0/osu.Framework.SourceGeneration.Roslyn4.0.csproj
  osu.Framework.SourceGeneration/osu.Framework.SourceGeneration.targets
  osu.Framework.SourceGeneration/pack.sh
Labels: area:dependency-injection, size/L

#5556 Add multi target file to source generator package
  osu.Framework.SourceGeneration/Build.targets
  osu.Framework.SourceGeneration/Roslyn3.11/osu.Framework.SourceGeneration.Roslyn3.11.csproj
  osu.Framework.SourceGeneration/Roslyn4.0/osu.Framework.SourceGeneration.Roslyn4.0.csproj
  osu.Framework.SourceGeneration/targets/ppy.osu.Framework.SourceGeneration.targets
  osu.Framework/osu.Framework.csproj
Labels: area:dependency-injection, size/M, type:reliability
