Repository ppy/osu-framework, pull requests merged in 2023-09, with the labels that each got.

#5985 Update native libraries
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#5987 Fix masking broken with TexturedVertex3D
  osu.Framework/Graphics/Lines/Path_DrawNode.cs
  osu.Framework/Graphics/Rendering/Vertices/TexturedVertex3D.cs
Labels: area:graphics, size/M

#5990 Revert masking ssbo changes
  osu.Framework/Graphics/Audio/WaveformGraph.cs
  osu.Framework/Graphics/BufferedDrawNode.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
  osu.Framework/Graphics/Lines/Path_DrawNode.cs
  osu.Framework/Graphics/OpenGL/GLRenderer.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
  osu.Framework/Graphics/Rendering/FlushBatchSource.cs
  osu.Framework/Graphics/Rendering/GlobalUniformData.cs
  osu.Framework/Graphics/Rendering/IRenderer.cs
  osu.Framework/Graphics/Rendering/MaskingInfo.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
  osu.Framework/Graphics/Rendering/RendererExtensions.cs
  osu.Framework/Graphics/Rendering/ShaderMaskingInfo.cs
  osu.Framework/Graphics/Rendering/Vertices/TexturedVertex2D.cs
  osu.Framework/Graphics/Rendering/Vertices/TexturedVertex3D.cs
  osu.Framework/Graphics/Shaders/ShaderManager.cs
  osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
  osu.Framework/Resources/Shaders/Internal/sh_GlobalUniforms.h
  osu.Framework/Resources/Shaders/Internal/sh_MaskingInfo.h
  osu.Framework/Resources/Shaders/sh_Masking.h
  osu.Framework/Resources/Shaders/sh_Texture2D.vs
  osu.Framework/Resources/Shaders/sh_Texture2D_NoMasking.vs
  osu.Framework/Resources/Shaders/sh_Texture3D.vs
Labels: area:graphics, size/XL

#5992 Tidy up `InterpolatingFramedClock`
  osu.Framework.Tests/Visual/Drawables/TestSceneTransformRewinding.cs
  osu.Framework/Timing/FramedClock.cs
  osu.Framework/Timing/IFrameBasedClock.cs
  osu.Framework/Timing/ISourceChangeableClock.cs
  osu.Framework/Timing/InterpolatingFramedClock.cs
Labels: type:code-quality, size/L

#5989 Fix `OpenUrlExternally` potentially crashing applications due to misconfigurations (and log errors instead)
  osu.Framework.Android/AndroidGameHost.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework/Platform/DesktopGameHost.cs
Labels: size/M, area:platform, type:reliability

#5998 Avoid throwing exception when attempting to access `WebRequest` response in fail path
  osu.Framework/IO/Network/JsonWebRequest.cs
  osu.Framework/IO/Network/WebRequest.cs
Labels: type:code-quality, size/S

#5999 Bump OpenTabletDriver to 0.6.3.0
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#5997 Don't block cut/copy platform actions on empty textbox selection
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: area:UI, size/S

#6004 Bump SPIRV with `plist` versioning fix
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#6003 Add fluXis to project list
  README.md
Labels: size/XS

#6006 Stop logging non-error output from OpenTabletDriver
  osu.Framework/Input/Handlers/Tablet/TabletDriver.cs
Labels: size/XS

#6001 Add new `DecouplingClock` and obsolete `DecoupleableInterpolatingFramedClock`
  osu.Framework.Tests/Clocks/DecoupleableInterpolatingFramedClockTest.cs
  osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
  osu.Framework.Tests/Clocks/TestClock.cs
  osu.Framework.Tests/Clocks/TestStopwatchClockWithRangeLimit.cs
  osu.Framework.Tests/Visual/Clocks/LaggyFramedClock.cs
  osu.Framework.Tests/Visual/Clocks/TestSceneClock.cs
  osu.Framework.Tests/Visual/Clocks/TestSceneClocks.cs
  osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs
  osu.Framework/Timing/DecouplingFramedClock.cs
  osu.Framework/Timing/InterpolatingFramedClock.cs
  osu.Framework/Timing/ManualFramedClock.cs
  osu.Framework/Timing/StopwatchClock.cs
Labels: area:clocks, size/XL

#6005 Fix keyboard handler getting disabled on window creation failure
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/HeadlessGameHost.cs
Labels: area:input, size/M
