Repository ppy/osu-framework, pull requests merged in 2023-12, with the labels that each got.

#6073 Cleanup `DrawNode` drawing methods
  osu.Framework.Tests/Visual/Containers/TestSceneFrontToBack.cs
  osu.Framework.Tests/Visual/Graphics/TestSceneShaderStorageBufferObject.cs
  osu.Framework.Tests/Visual/Graphics/TestSceneStencil.cs
  osu.Framework.Tests/Visual/Graphics/TestSceneVertexBatching.cs
  osu.Framework/Graphics/Audio/WaveformGraph.cs
  osu.Framework/Graphics/BufferedDrawNode.cs
  osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
  osu.Framework/Graphics/DrawNode.cs
  osu.Framework/Graphics/Drawable_ProxyDrawable.cs
  osu.Framework/Graphics/Lines/Path_DrawNode.cs
  osu.Framework/Graphics/Rendering/DepthValue.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
  osu.Framework/Graphics/Rendering/IRenderer.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
  osu.Framework/Graphics/Rendering/Vertices/TexturedVertex2D.cs
  osu.Framework/Graphics/Sprites/BufferedContainerView.cs
  osu.Framework/Graphics/Sprites/SpriteDrawNode.cs
  osu.Framework/Graphics/Sprites/SpriteText_DrawNode.cs
  osu.Framework/Graphics/Visualisation/TextureVisualiser.cs
  osu.Framework/Platform/GameHost.cs
Labels: type:code-quality, area:graphics, size/L

#6074 FFmpeg: Add VP6 and WMV2 video formats
  osu.Framework.NativeLibs/scripts/ffmpeg/common.sh
Labels: size/S

#6063 Add a session timestamp prefix to log files (and retain 7 days of logs)
  osu.Framework/Logging/Logger.cs
Labels: area:logging, size/M

#6065 Add format provider argument to `IParseable.Parse()`
  osu.Framework.Tests/Bindables/BindableBoolTest.cs
  osu.Framework.Tests/Bindables/BindableColour4Test.cs
  osu.Framework.Tests/Bindables/BindableDictionaryTest.cs
  osu.Framework.Tests/Bindables/BindableDoubleTest.cs
  osu.Framework.Tests/Bindables/BindableEnumTest.cs
  osu.Framework.Tests/Bindables/BindableFloatTest.cs
  osu.Framework.Tests/Bindables/BindableIntTest.cs
  osu.Framework.Tests/Bindables/BindableListTest.cs
  osu.Framework.Tests/Bindables/BindableLongTest.cs
  osu.Framework.Tests/Bindables/BindableMarginPaddingTest.cs
  osu.Framework.Tests/Bindables/BindableSizeTest.cs
  osu.Framework.Tests/Bindables/BindableStringTest.cs
  osu.Framework.Tests/Bindables/BindableTest.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/BindableBool.cs
  osu.Framework/Bindables/BindableColour4.cs
  osu.Framework/Bindables/BindableDictionary.cs
  osu.Framework/Bindables/BindableList.cs
  osu.Framework/Bindables/BindableMarginPadding.cs
  osu.Framework/Bindables/BindableSize.cs
  osu.Framework/Bindables/IParseable.cs
  osu.Framework/Configuration/IniConfigManager.cs
Labels: size/L

#6061 Add proper handling for `BindableList` collection changes in dropdown
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
Labels: area:UI, size/L

#6056 Add method to convert piecewise linear curves to spline control points
  osu.Framework.Benchmarks/BenchmarkPiecewiseLinearToBezier.cs
  osu.Framework.Tests/Visual/Drawables/TestScenePiecewiseLinearToBSpline.cs
  osu.Framework/Utils/PathApproximator.cs
  osu.Framework/osu.Framework.csproj
Labels: size/XL

#6066 Improve incremental B-spline builder via stochastic optimisation
  osu.Framework.Tests/Visual/Drawables/TestSceneInteractivePathDrawing.cs
  osu.Framework.Tests/Visual/Drawables/TestScenePiecewiseLinearToBSpline.cs
  osu.Framework/Utils/IncrementalBSplineBuilder.cs
  osu.Framework/Utils/PathApproximator.cs
Labels: size/L

#6072 Implement dropdown searching
  osu.Framework.Tests/Visual/Layout/TestSceneFillFlowContainer.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxKeyEvents.cs
  osu.Framework/Graphics/UserInterface/BasicDropdown.cs
  osu.Framework/Graphics/UserInterface/BasicTextBox.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/DropdownHeader.cs
  osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Testing/Input/ManualTextInputSource.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: area:UI, size/XL

#6080 Fix dropdowns showing popup keyboard on mobile even when search bar is initially hidden
  osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs
Labels: area:UI, platform:mobile, size/S, next-release

#6090 Fix audio device names not being populated in time for bass device initialisation
  osu.Framework/Audio/AudioManager.cs
Labels: area:audio, size/XS, next-release

#6086 Bump OpenTabletDriver to 0.6.4.0
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#6091 Rename concept of "global" mixer with "fallback"
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/Mixing/AudioMixer.cs
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
Labels: type:code-quality

#6087 Add basic global statistics for input handler events
  osu.Framework.Android/Input/AndroidJoystickHandler.cs
  osu.Framework.Android/Input/AndroidKeyboardHandler.cs
  osu.Framework.Android/Input/AndroidMouseHandler.cs
  osu.Framework.Android/Input/AndroidTouchHandler.cs
  osu.Framework/Input/Handlers/InputHandler.cs
  osu.Framework/Input/Handlers/Joystick/JoystickHandler.cs
  osu.Framework/Input/Handlers/Keyboard/KeyboardHandler.cs
  osu.Framework/Input/Handlers/Midi/MidiHandler.cs
  osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
  osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
  osu.Framework/Input/Handlers/Touch/TouchHandler.cs
  osu.Framework/Platform/Windows/WindowsMouseHandler.cs
Labels: area:input, type:testing, size/M

#6088 Add low latency initialisation support on windows by directly interacting with WASAPI
  osu.Framework.Tests/Audio/BassTestComponents.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
  osu.Framework/Graphics/Visualisation/Audio/AudioChannelDisplay.cs
  osu.Framework/Threading/AudioThread.cs
  osu.Framework/osu.Framework.csproj
Labels: area:audio, size/L, platform:windows, next-release

#6093 Disable WASAPI initialisation mode for now
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Threading/AudioThread.cs
Labels: area:audio, size/XS

#5309 Fix Windows Ink events being handled as touch events
  osu.Framework/Platform/SDL2/SDL2Extensions.cs
  osu.Framework/Platform/SDL2Window.cs
  osu.Framework/Platform/SDL2Window_Input.cs
  osu.Framework/Platform/Windows/WindowsWindow.cs
  osu.Framework/osu.Framework.csproj
Labels: area:input, size/M, platform:windows

#6094 Add setting to control automatic minimising on focus loss in fullscreen mode
  osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
  osu.Framework/Configuration/FrameworkConfigManager.cs
  osu.Framework/Platform/SDL2Window.cs
  osu.Framework/Platform/SDL2Window_Windowing.cs
Labels: area:configuration, size/M, area:platform
