Repository ppy/osu-framework, pull requests merged in 2023-05, with the labels that each got.

#5765 Disable manual mipmap generation (and decrease atlas size again)
  osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
  osu.Framework/Graphics/Textures/TextureStore.cs
  osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
Labels: area:graphics, size/XL, next-release

#5255 Add long tap to right click support
  osu.Framework.Tests/Visual/Input/TestSceneTouchInput.cs
  osu.Framework/Graphics/Cursor/CursorContainer.cs
  osu.Framework/Graphics/Cursor/TouchLongPressFeedback.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/MouseButtonEventManager.cs
  osu.Framework/Input/TouchEventManager.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: area:input, size/L

#5769 Prefer block scoped namespaces
  .editorconfig
  osu-framework.sln.DotSettings
  osu.Framework.Tests/Visual/Containers/TestSceneBufferedContainerClipping.cs
  osu.Framework/Platform/SDL2DesktopWindow.cs
Labels: type:code-quality, size/L

#5768 Move `ActiveCursor` initial population to ctor to allow safe non-null specification
  osu.Framework/Graphics/Cursor/CursorContainer.cs
Labels: size/XS, type:reliability

#5771 Remove cast in `ResourceStore` constructor
  osu.Framework/IO/Stores/ResourceStore.cs
Labels: type:code-quality, size/XS

#5773 Remove `[ExcludeFromDynamicCompile]` attribute
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Testing/ExcludeFromDynamicCompileAttribute.cs
  osu.Framework/Testing/TestScene.cs
Labels: type:code-quality, size/S

#5780 Update veldrid SPIRV with fix for older macOS versions
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#5776 Disable relative-mode mouse by default on Linux
  osu.Framework/Platform/Linux/LinuxGameHost.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
Labels: area:input, platform:linux, size/S

#5781 updating the dotnet command because -i is deprecated.
  osu.Framework.Templates/README.md
Labels: size/XS

#5784 Reduce overhead induced by checking Bass CPU usage
  osu.Framework/Threading/AudioThread.cs
Labels: type:performance, area:audio, size/XS, next-release

#5783 Cache value of `VerticalSync` to avoid overhead retrieving from SDL2 each time
  osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs
Labels: type:performance, size/S, next-release

#5785 Fix D3D11 losing performance by constantly mapping/unmapping buffers
  osu.Framework/Graphics/Veldrid/Batches/VeldridLinearBatch.cs
  osu.Framework/Graphics/Veldrid/Batches/VeldridQuadBatch.cs
  osu.Framework/Graphics/Veldrid/Buffers/Staging/IStagingBuffer.cs
  osu.Framework/Graphics/Veldrid/Buffers/Staging/ManagedStagingBuffer.cs
  osu.Framework/Graphics/Veldrid/Buffers/Staging/PersistentStagingBuffer.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridLinearBuffer.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridQuadBuffer.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs
  osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
Labels: type:performance, size/L, next-release, area:renderer-veldrid

#5787 Revert changes to texture upload from manual mipmap generation pull
  osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
  osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
Labels: size/L, next-release, area:renderer-veldrid, area:renderer-gl

#5793 Change method group inspection to warning to match osu!
  osu-framework.sln.DotSettings
  osu.Framework.Tests/Containers/TestSceneLoadComponentAsync.cs
  osu.Framework.Tests/Exceptions/TestLoadExceptions.cs
  osu.Framework.Tests/Visual/Containers/TestSceneCursorContainer.cs
  osu.Framework.Tests/Visual/Containers/TestSceneFrontToBackBox.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneSynchronizationContext.cs
  osu.Framework/Audio/Track/TrackBass.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Handlers/Midi/MidiHandler.cs
Labels: type:code-quality, size/M

#5796 Revert method group change in hot path
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
Labels: type:performance, size/XS

#5794 Revert `Schedule` changes to `Dropdown`
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
Labels: area:UI, size/M

#5797 Add `BindableList.ReplaceRange` as an atomic operation
  osu.Framework.Tests/Bindables/BindableListTest.cs
  osu.Framework/Bindables/BindableList.cs
Labels: area:bindable, size/M

#5798 Fix event bindings from long press flow in `CursorContainer` not being cleaned up
  osu.Framework/Graphics/Cursor/CursorContainer.cs
Labels: size/S, type:reliability

#5801 Show more information in frame statistic display
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
  osu.Framework/Graphics/Performance/PerformanceOverlay.cs
Labels: area:tooling, size/M

#5800 Unmap persistent buffers before uploading
  osu.Framework/Graphics/Veldrid/Buffers/Staging/PersistentStagingBuffer.cs
Labels: size/S, area:renderer-veldrid

#5804 Pin builds to .NET 6
  global.json
Labels: area:tooling, size/XS

#5805 Update SDL native libraries
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/TemplateGame.Game.Tests.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/FlappyDon.Game.Tests.csproj
  osu.Framework.Tests/osu.Framework.Tests.csproj
  osu.Framework/osu.Framework.csproj
Labels: size/S, dependencies

#5802 Use float for color space conversion
  osu.Framework.Benchmarks/BenchmarkColourInfo.cs
  osu.Framework.Benchmarks/osu.Framework.Benchmarks.csproj
  osu.Framework.Tests/Visual/Graphics/TestSceneColours.cs
  osu.Framework/Extensions/Color4Extensions/Color4Extensions.cs
  osu.Framework/Graphics/Colour4.cs
Labels: type:performance, size/L

#5806 Force `FrameTimeDisplay` font choice to framework font
  osu.Framework/Graphics/Performance/FrameTimeDisplay.cs
Labels: area:UI, size/XS

#5807 Avoid creating new `List<RectangleI>` when no texture uploads are required
  osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
  osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
Labels: type:performance, size/S

#5810 Use `DummyRenderer` in `HeadlessGameHost`
  osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
  osu.Framework/Platform/HeadlessGameHost.cs
Labels: type:testing, size/XS

#5778 Simplify UBO uploads
  osu.Framework/Graphics/OpenGL/Buffers/GLUniformBuffer.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridUniformBuffer.cs
  osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
Labels: type:code-quality, size/M

#5758 Simplify GL renderer uniform buffer binding
  osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
  osu.Framework/Graphics/OpenGL/Shaders/GLUniformBlock.cs
  osu.Framework/Graphics/Veldrid/Shaders/VeldridShader.cs
Labels: size/M, area:renderer-gl

#5814 Match BDL SGen attributes by full type name
  osu.Framework.SourceGeneration/SyntaxHelpers.cs
Labels: area:tooling, size/S

#5812 Combine source-gen and reflection BDL pathways
  osu.Framework/Allocation/BackgroundDependencyLoaderAttribute.cs
  osu.Framework/Allocation/CachedAttribute.cs
  osu.Framework/Allocation/ResolvedAttribute.cs
  osu.Framework/Utils/SourceGeneratorUtils.cs
Labels: type:code-quality, area:dependency-injection, size/M

#5772 Allow `SearchContainer` implementations to manually trigger a `Filter` operation
  osu.Framework/Graphics/Containers/SearchContainer.cs
Labels: size/M

#5815 Fix not being able to parse empty string into nullable bindable
  osu-framework.sln.DotSettings
  osu.Framework.Tests/Bindables/BindableEnumTest.cs
  osu.Framework.Tests/Bindables/BindableTest.cs
  osu.Framework/Bindables/Bindable.cs
  osu.Framework/Bindables/BindableBool.cs
  osu.Framework/Bindables/BindableColour4.cs
  osu.Framework/Bindables/BindableMarginPadding.cs
  osu.Framework/Bindables/BindableSize.cs
Labels: area:bindable, size/L

#5821 Update veldrid with macOS `CVDisplayLink` support
  osu.Framework/osu.Framework.csproj
Labels: type:performance, platform:macOS, size/XS

#5820 Improve iOS/iPadOS frame timings by using `CADisplayLink`
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework.iOS/IOSWindow.cs
  osu.Framework/Platform/SDL2Window.cs
Labels: type:performance, platform:iOS, size/M
