Repository ppy/osu-framework, pull requests merged in 2023-06, with the labels that each got.

#5636 Expose truncated state of `SpriteText`
  osu.Framework/Graphics/Sprites/SpriteText.cs
  osu.Framework/Text/TruncatingTextBuilder.cs
Labels: area:drawable, size/S

#5824 Remove redundant nullable suppression directives
  osu.Framework.Tests/Dependencies/Reflection/DependencyContainerTest.cs
  osu.Framework.Tests/Dependencies/Reflection/ResolvedAttributeTest.cs
  osu.Framework.Tests/Dependencies/SourceGeneration/DependencyContainerTest.cs
  osu.Framework.Tests/Dependencies/SourceGeneration/ResolvedAttributeTest.cs
  osu.Framework/Graphics/Sprites/IHasLineBaseHeight.cs
  osu.Framework/Graphics/Textures/TextureTooLargeForGLException.cs
  osu.Framework/Graphics/Transforms/IEasingFunction.cs
  osu.Framework/Graphics/Transforms/ITransformSequence.cs
  osu.Framework/Graphics/UserInterface/Button.cs
  osu.Framework/Graphics/Visualisation/TreeContainerStatus.cs
  osu.Framework/IO/Network/RequestParameterType.cs
  osu.Framework/IUpdateable.cs
  osu.Framework/Input/ConfineMouseMode.cs
  osu.Framework/Input/IHandleGlobalKeyboardInput.cs
  osu.Framework/Input/IRequireHighFrequencyMousePosition.cs
  osu.Framework/Input/ISuppressKeyEventLogging.cs
  osu.Framework/Input/PlatformAction.cs
  osu.Framework/Input/StateChanges/ButtonStateChangeKind.cs
  osu.Framework/Input/TabletAuxiliaryButton.cs
  osu.Framework/Input/TabletPenButton.cs
  osu.Framework/Input/TouchSource.cs
Labels: type:code-quality, size/M

#5825 Reduce invalidations of `childrenSizeDependencies` in edge cases
  osu.Framework.Tests/Layout/TestSceneContainerLayout.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: type:performance, size/L, area:layout

#5826 Update Veldrid package to revert `CADisplayLink` implementation from veldrid-side
  osu.Framework/osu.Framework.csproj
Labels: area:libraries, size/XS, area:renderer-veldrid

#5832 Add include guards to all shaders
  osu.Framework/Resources/Shaders/Internal/sh_Compatibility.h
  osu.Framework/Resources/Shaders/Internal/sh_GlobalUniforms.h
  osu.Framework/Resources/Shaders/Internal/sh_Vertex_Output.h
  osu.Framework/Resources/Shaders/sh_Blur.fs
  osu.Framework/Resources/Shaders/sh_Blur.vs
  osu.Framework/Resources/Shaders/sh_CircularBlob.fs
  osu.Framework/Resources/Shaders/sh_CircularBlobUtils.h
  osu.Framework/Resources/Shaders/sh_CircularProgress.fs
  osu.Framework/Resources/Shaders/sh_CircularProgressUtils.h
  osu.Framework/Resources/Shaders/sh_HueSelectorBackground.fs
  osu.Framework/Resources/Shaders/sh_Masking.h
  osu.Framework/Resources/Shaders/sh_Particle.vs
  osu.Framework/Resources/Shaders/sh_Position.vs
  osu.Framework/Resources/Shaders/sh_SaturationSelectorBackground.fs
  osu.Framework/Resources/Shaders/sh_Texture.fs
  osu.Framework/Resources/Shaders/sh_Texture2D.vs
  osu.Framework/Resources/Shaders/sh_Texture3D.vs
  osu.Framework/Resources/Shaders/sh_TextureWrapping.h
  osu.Framework/Resources/Shaders/sh_Utils.h
  osu.Framework/Resources/Shaders/sh_Video.fs
  osu.Framework/Resources/Shaders/sh_mipmap.fs
  osu.Framework/Resources/Shaders/sh_mipmap.vs
  osu.Framework/Resources/Shaders/sh_yuv2rgb.h
Labels: size/L, area:shader, type:reliability

#5833 Update README.md to include VS Code plugin prerequisites
  README.md
Labels: size/XS

#5831 Remove `Dropdown.AddDropdownItem(text, value)` overload
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Testing/Drawables/Sections/ToolbarAssemblySection.cs
  osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: area:UI, size/M

#5835 Add UseLocalVeldrid scripts
  UseLocalVeldrid.ps1
  UseLocalVeldrid.sh
Labels: area:tooling, size/M

#5837 Fix cases of incorrect nullability in `ToString` override definitions
  osu.Framework/Bindables/BindableColour4.cs
  osu.Framework/Bindables/BindableSize.cs
Labels: type:code-quality, size/XS

#5829 Add disk cache for shader compilations
  osu.Framework.Tests/Shaders/TestSceneShaderDisposal.cs
  osu.Framework.Tests/Shaders/TestShaderLoading.cs
  osu.Framework/Graphics/OpenGL/GLRenderer.cs
  osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
  osu.Framework/Graphics/OpenGL/Shaders/GLShaderPart.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
  osu.Framework/Graphics/Rendering/IRenderer.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
  osu.Framework/Graphics/Shaders/ComputeProgramCompilation.cs
  osu.Framework/Graphics/Shaders/ShaderCompilationStore.cs
  osu.Framework/Graphics/Shaders/VertexFragmentShaderCompilation.cs
  osu.Framework/Graphics/Veldrid/Shaders/VeldridShader.cs
  osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
  osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
  osu.Framework/Platform/GameHost.cs
Labels: type:performance, size/L, area:shader

#5834 Remove overrides of PopIn/PopOut in FocusedOverlayContainer
  osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneFocusedOverlayContainer.cs
  osu.Framework/Graphics/Containers/FocusedOverlayContainer.cs
  osu.Framework/Graphics/UserInterface/Popover.cs
Labels: type:code-quality, size/M

#5838 Add new `DeferredStagingBuffer` type
  osu.Framework/FrameworkEnvironment.cs
  osu.Framework/Graphics/Veldrid/Buffers/Staging/DeferredStagingBuffer.cs
  osu.Framework/Graphics/Veldrid/VeldridRenderer.cs
Labels: area:graphics, size/L

#5840 Fix `WaitUntilNextFrameReady` not being accounted for as `Sleep` time
  osu.Framework/Platform/GameHost.cs
Labels: area:tooling, size/XS

#5839 Move midi initialisation to a thread
  osu.Framework/Input/Handlers/Midi/MidiHandler.cs
Labels: type:performance, size/S

#5687 Enforce presence of all fragment shader inputs in Veldrid
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
  osu.Framework/Graphics/Shaders/ShaderManager.cs
  osu.Framework/Graphics/Veldrid/Shaders/VeldridShader.cs
  osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
  osu.Framework/Resources/Shaders/Internal/sh_Fragment_Output.h
  osu.Framework/Resources/Shaders/sh_Blur.fs
  osu.Framework/Resources/Shaders/sh_Blur.vs
Labels: size/L, area:renderer-veldrid

#5830 Expose `Path.BackgroundColour` as a settable property
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/Lines/SmoothPath.cs
Labels: area:drawable, size/M

#5842 Fix `UseLocalVeldrid` not adding satellite assemblies to slnf files
  UseLocalVeldrid.ps1
  UseLocalVeldrid.sh
Labels: size/S

#5841 Fix nested DI candidates not analysed in non-candidate parent types
  osu.Framework.SourceGeneration/Analysers/DiagnosticRules.cs
  osu.Framework.SourceGeneration/Analysers/DrawableAnalyser.cs
Labels: area:tooling, size/M

#5843 Fix performance when viewing the tail end of a long / zoomed-in waveform
  osu.Framework.Tests/Visual/Drawables/TestSceneWaveform.cs
  osu.Framework/Graphics/Audio/WaveformGraph.cs
Labels: type:performance, size/M

#5846 Ensure renderer-api-driven frame wait is only invoked when a frame is actually drawn
  osu.Framework/Platform/GameHost.cs
Labels: type:performance, size/S, next-release, area:renderer-veldrid

#5847 Improve metal frame rendering when more than one display is connected
  osu.Framework/Platform/GameHost.cs
  osu.Framework/osu.Framework.csproj
Labels: size/S, next-release

#5849 Avoid initialising `VeldridVertexBuffer` immediately
  osu.Framework/Graphics/Veldrid/Buffers/VeldridVertexBuffer.cs
Labels: type:performance, size/S

#5850 Fix item labels not generated while dropdown is in `Ready` state
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
Labels: area:UI, size/M, next-release

#5856 Fix stray inspection showing up in rider
  osu.Framework.SourceGeneration/Generators/HandleInput/HandleInputSourceEmitter.cs
Labels: size/M

#5854 Tidy up hot reload notification toast
  osu.Framework/Testing/TestBrowser.cs
Labels: area:tooling, size/M

#5845 Improve nested `ScrollContainer` tests
  osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
  osu.Framework.Tests/Visual/Containers/TestSceneScrollContainerNested.cs
Labels: area:input, type:testing, size/L

#5859 Bump OpenTabletDriver version to 0.6.1.0
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#5857 Cleanup Veldrid shader resource layouts and add header guard
  osu.Framework/Graphics/OpenGL/Shaders/GLShader.cs
  osu.Framework/Graphics/Veldrid/Shaders/VeldridShader.cs
  osu.Framework/Resources/Shaders/Internal/sh_Fragment_Output.h
Labels: type:code-quality, size/M, area:renderer-veldrid

#5862 Fix possible nullref when binding textures under Veldrid
  osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
Labels: size/XS, type:reliability, area:renderer-veldrid

#5855 Remove assembly dropdown from visual test browser
  osu.Framework/Testing/Drawables/Sections/ToolbarRunAllStepsSection.cs
  osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: area:tooling, size/L

#5853 Ensure triple buffer never uses the same buffer twice in a row
  osu.Framework.Tests/Graphics/TripleBufferTest.cs
  osu.Framework/Allocation/ObjectUsage.cs
  osu.Framework/Allocation/TripleBuffer.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:threading, size/L

#5865 Don't apply `RenderBufferFormat`s to effect buffers
  osu.Framework.Tests/Visual/Graphics/TestSceneStencil.cs
  osu.Framework/Graphics/BufferedDrawNodeSharedData.cs
  osu.Framework/Graphics/Containers/BufferedContainer.cs
  osu.Framework/Graphics/Containers/BufferedContainer_DrawNode.cs
Labels: area:graphics, size/M

#5869 Exclude U+202F NARROW NO-BREAK SPACE from being treated as fixed-width
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: area:UI, size/XS

#5868 Fix NRT-related issues found game-side
  osu.Framework/Input/StateChanges/Events/InputStateChangeEvent.cs
  osu.Framework/Platform/DesktopStorage.cs
Labels: type:code-quality, size/XS

#5870 Add support for alternative clipboard keys (ctrl-insert / shift-delete / shift-insert)
  osu.Framework/Platform/GameHost.cs
Labels: area:input, size/XS, area:platform

#5872 Fix android safe area not updating after returning to game with a different orientation
  osu.Framework.Android/AndroidGameView.cs
Labels: platform:android, size/S

#5873 Update deployment workflow to automatically run on new tag
  .github/workflows/deploy-pack.yml
Labels: area:tooling, size/L

#5876 Update veldrid
  osu.Framework/osu.Framework.csproj
Labels: size/XS, area:renderer-veldrid
