Repository ppy/osu-framework, pull requests merged in 2024-09, with the labels that each got.

#6367 Update main operating systems to bass beta version
  osu.Framework.NativeLibs/runtimes/osx/native/libbass.dylib
  osu.Framework.NativeLibs/runtimes/osx/native/libbass_fx.dylib
  osu.Framework.NativeLibs/runtimes/osx/native/libbassmix.dylib
  osu.Framework.NativeLibs/runtimes/win-x64/native/bass.dll
  osu.Framework.NativeLibs/runtimes/win-x64/native/bass_fx.dll
  osu.Framework.NativeLibs/runtimes/win-x64/native/bassmix.dll
  osu.Framework.NativeLibs/runtimes/win-x86/native/bass.dll
  osu.Framework.NativeLibs/runtimes/win-x86/native/bass_fx.dll
  osu.Framework.NativeLibs/runtimes/win-x86/native/bassmix.dll
Labels: size/XS

#6368 Fix alloc overhead in hot path for keyboard checks
  osu.Framework/Input/Bindings/KeyCombination.cs
Labels: type:performance, size/XS, next-release

#6369 Update managed-midi to fix disposal issue
  osu.Framework/osu.Framework.csproj
Labels: area:input, size/XS

#6370 Update ppy.Veldrid.SPIRV
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#6372 Fix typo in `CompositeDrawable`
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: size/XS

#6374 Update SDL3-CS
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework/Platform/SDL3/SDL3Clipboard.cs
  osu.Framework/Platform/SDL3/SDL3Window.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
  osu.Framework/Platform/SDL3/SDL3Window_Windowing.cs
  osu.Framework/osu.Framework.csproj
Labels: size/L

#6377 Expose `LocalisationManager.GetLocalisedString()` as public
  osu.Framework/Localisation/LocalisationManager.cs
Labels: area:localisation, size/XS

#6378 Fix DecouplingFramedClock retaining old lastSeekFailed
  osu.Framework.Tests/Clocks/DecouplingFramedClockTest.cs
  osu.Framework/Timing/DecouplingFramedClock.cs
Labels: size/S

#6379 Fix iOS CI build
  .github/workflows/ci.yml
  .github/workflows/deploy-pack.yml
Labels: area:tooling, platform:iOS
