Repository ppy/osu-framework, pull requests merged in 2024-06, with the labels that each got.

#6307 Make shader setter in `SpriteText` protected
  osu.Framework/Graphics/Sprites/Sprite.cs
  osu.Framework/Graphics/Sprites/SpriteText.cs
Labels: size/S, area:shader

#6311 Ignore editlist when decoding mp4/mov videos
  osu.Framework/Graphics/Video/FFmpegFuncs.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: size/S, area:video

#6310 Replace audio effect `BindableList` by Add/Remove methods
  osu.Framework.Tests/Audio/BassAudioMixerTest.cs
  osu.Framework.Tests/Visual/Audio/TestSceneAudioMixer.cs
  osu.Framework/Audio/Mixing/AudioMixer.cs
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
  osu.Framework/Audio/Mixing/IAudioMixer.cs
  osu.Framework/Graphics/Audio/DrawableAudioMixer.cs
Labels: area:audio, size/L

#6313 Fix video decoding failing on Android due to missing `av_dict_{set,free}`
  osu.Framework/Graphics/Video/FFmpegFuncs.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
Labels: platform:android, size/XS, area:video, next-release

#6315 Fix clicking on padded dropdown search bars not opening the menu
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/DropdownHeader.cs
  osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs
Labels: area:input, size/M

#6312 Add virtualised list container
  osu-framework.sln.DotSettings
  osu.Framework.Tests/Visual/Containers/TestSceneVirtualisedListContainer.cs
  osu.Framework/Graphics/Containers/VirtualisedListContainer.cs
Labels: type:performance, area:drawable, size/L, area:pooling

#6316 Fix `VirtualisedListContainer` rows not returning child to pool on disposal
  osu.Framework.Tests/Visual/Containers/TestSceneVirtualisedListContainer.cs
  osu.Framework/Graphics/Containers/VirtualisedListContainer.cs
Labels: type:performance, area:drawable, size/S

#6317 Remove faulty assertion in scroll container
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: area:UI, size/XS

#6319 Rewrite TripleBuffer as a true lockless, flipping, triple buffer
  osu.Framework.Tests/Graphics/TripleBufferTest.cs
  osu.Framework.Tests/Visual/Graphics/TestSceneTripleBufferOccupancy.cs
  osu.Framework/Allocation/ObjectUsage.cs
  osu.Framework/Allocation/TripleBuffer.cs
  osu.Framework/Graphics/Veldrid/Batches/VeldridVertexBatch.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:graphics, size/XL, type:reliability

#6255 FFmpeg build: Update to 7.0
  .github/workflows/build-ffmpeg.yml
  .gitignore
  osu.Framework.NativeLibs/scripts/ffmpeg/build-android.sh
  osu.Framework.NativeLibs/scripts/ffmpeg/build-iOS.sh
  osu.Framework.NativeLibs/scripts/ffmpeg/build-linux.sh
  osu.Framework.NativeLibs/scripts/ffmpeg/build-win.sh
  osu.Framework.NativeLibs/scripts/ffmpeg/combine_dylibs.sh
  osu.Framework.NativeLibs/scripts/ffmpeg/common.sh
  osu.Framework.NativeLibs/scripts/ffmpeg/create-xcframeworks.sh
  osu.Framework.NativeLibs/scripts/ffmpeg/fix-binutils-2.41.patch
  osu.Framework.NativeLibs/scripts/ffmpeg/iOS-set-install-name-for-xcframework.patch
Labels: area:libraries, size/XL, area:video

#6322 Fix typo in `Drawable` documentation
  osu.Framework/Graphics/Drawable.cs
Labels: type:documentation, size/XS
