Repository ppy/osu-framework, pull requests merged in 2024-01, with the labels that each got.

#6085 add window hide/show methods (preliminary work for boss key)
  osu.Framework/Platform/IWindow.cs
  osu.Framework/Platform/OsuTKWindow.cs
  osu.Framework/Platform/SDL2Window.cs
Labels: size/S

#6100 Fix android storage path on .NET 8
  osu.Framework.Android/AndroidGameActivity.cs
Labels: platform:android, size/XS

#6096 Fix dropdown header handling platform actions when not hovered
  osu.Framework/Graphics/UserInterface/DropdownHeader.cs
Labels: area:input, area:UI, size/XS

#6103 Make `Insert` for `SlimReadOnlyListWrapper` unsupported
  osu.Framework/Lists/SlimReadOnlyListWrapper.cs
Labels: size/S

#6107 Update year references
  Directory.Build.props
  LICENCE
Labels: size/XS

#6104 Set process priority of framework window to high when focused
  osu.Framework/Platform/Windows/WindowsGameHost.cs
Labels: type:performance, size/S

#6106 Use `HashSet` instead of `List` for temporary check in transform handling
  osu.Framework.Benchmarks/BenchmarkTransform.cs
  osu.Framework/Graphics/Transforms/TargetGroupingTransformTracker.cs
Labels: type:performance, size/M

#6109 Reduce allocs when setting value on `BindableNumber` with precision
  osu.Framework.Benchmarks/BenchmarkBindableNumber.cs
  osu.Framework/Bindables/BindableNumber.cs
Labels: type:performance, area:bindable, size/M

#6108 Remove per-call array allocations from `InputSampler`
  osu.Framework/Input/InputResampler.cs
Labels: type:performance, size/S

#6111 Simplify `SpriteIcon`
  osu.Framework/Graphics/Sprites/SpriteIcon.cs
Labels: type:performance, area:UI, size/L

#6116 Remove alloc overhead for `NormalizedValue`
  osu.Framework/Bindables/RangeConstrainedBindable.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
Labels: type:performance, size/M

#6118 Fix frame statistics display GC boxes not correctly being cleaned up
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
Labels: area:tooling, size/XS

#6113 Expose `RunTestsFromNUnit` as `public`
  osu.Framework.Tests/Visual/Testing/TestSceneNestedGame.cs
  osu.Framework/Testing/TestScene.cs
Labels: type:code-quality, size/XS

#6120 Reduce input processing overheads in `PassThroughInputManager`
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Input/States/TouchState.cs
Labels: type:performance, size/L

#6119 Avoid creating a new texture in `SmoothPath` if the existing one is already the correct size
  osu.Framework/Graphics/Lines/SmoothPath.cs
Labels: type:performance, size/S

#6123 Remove allocations when checking if mouse outside all displays
  osu.Framework/Input/UserInputManager.cs
  osu.Framework/Platform/IWindow.cs
  osu.Framework/Platform/OsuTKWindow.cs
  osu.Framework/Platform/SDL2Window_Windowing.cs
Labels: type:performance, size/S

#6121 Reduce string allocations during shader creation
  osu.Framework/Graphics/OpenGL/Shaders/GLShaderPart.cs
  osu.Framework/Graphics/Veldrid/Shaders/VeldridShaderPart.cs
Labels: type:performance, size/M

#6122 Remove delegate allocation in jitter calculation in `FramedClock`
  osu.Framework/Timing/FramedClock.cs
Labels: type:performance, size/S

#6128 Remove `VeldridTexture.Bind()`
  osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
Labels: type:code-quality, size/S, area:renderer-veldrid

#6125 Remove overheads of MIDI device polling
  osu.Framework/Input/Handlers/Midi/MidiHandler.cs
Labels: type:performance, size/M

#6124 Remove allocations during bass device sync polling operation
  osu.Framework.Tests/Audio/AudioManagerWithDeviceLoss.cs
  osu.Framework/Audio/AudioManager.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
  osu.Framework/Platform/SDL2Window_Windowing.cs
Labels: type:performance, size/M

#6126 Reduce allocation overhead for keyboard / binding / button handling
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
  osu.Framework/Input/ButtonEventManager.cs
Labels: type:performance, size/M

#6130 Fix `KeyCombination` throwing when duplicates are fed in
  osu.Framework.Tests/Input/KeyCombinationTest.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
Labels: size/M, type:reliability

#6132 Fix incorrect implementation of `OsuTKWindow.Displays`
  osu.Framework/Platform/OsuTKWindow.cs
Labels: platform:android, size/XS, area:platform, type:reliability

#6133 Fix runaway texture uploads when window is minimised with frame statistics visible
  osu.Framework/Graphics/OpenGL/Textures/GLTexture.cs
  osu.Framework/Graphics/Performance/FrameStatisticsDisplay.cs
  osu.Framework/Graphics/Veldrid/Textures/VeldridTexture.cs
Labels: size/S, type:reliability

#6136 Guard against potential usage of `DrawablePool` without being added to hierarchy
  osu.Framework.Tests/Visual/Drawables/TestSceneDrawablePool.cs
  osu.Framework/Graphics/Pooling/DrawablePool.cs
Labels: type:code-quality, size/M

#6101 Fix `InputManager` including non-loaded direct children in input queue
  osu.Framework.Tests/Visual/Input/TestSceneKeyBindingContainer.cs
  osu.Framework/Input/InputManager.cs
Labels: area:input, size/M

#6129 Make IPC port configurable via `HostOptions`
  osu.Framework.Tests/Platform/HeadlessGameHostTest.cs
  osu.Framework.Tests/Platform/UserInputManagerTest.cs
  osu.Framework/HostOptions.cs
  osu.Framework/Platform/DesktopGameHost.cs
Labels: area:configuration, size/S

#6135 Fix DragStart and TouchMove input events possibly being handled by unrooted drawables
  osu.Framework.Tests/Input/KeyboardInputTest.cs
  osu.Framework.Tests/Input/MouseInputTest.cs
  osu.Framework.Tests/Input/TouchInputTest.cs
  osu.Framework/Input/KeyEventManager.cs
  osu.Framework/Input/MouseButtonEventManager.cs
  osu.Framework/Input/TouchEventManager.cs
Labels: size/L, type:reliability

#6139 Fix missing invalidation on `SpriteIcon` texture change
  osu.Framework/Graphics/Sprites/SpriteIcon.cs
Labels: priority:0, size/XS, next-release

#6140 Add flaky test attribute and mark `CanSeekForwardOnInterpolationFail` as flaky
  osu.Framework.Tests/Clocks/InterpolatingFramedClockTest.cs
  osu.Framework.Tests/FlakyTestAttribute.cs
Labels: type:testing, area:clocks, size/M

#6146 Fix `TemplateGameTestScene` showing up in test browser
  osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/Visual/TemplateGameTestScene.cs
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/Visual/FlappyDonTestScene.cs
Labels: size/XS

#6143 Include rounded corner radius in android safe area implementation
  osu.Framework.Android/AndroidGameView.cs
Labels: platform:android, size/S

#6144 Ignore autogenerated .idea android file
  .gitignore
Labels: platform:android, size/XS

#6148 Fix allocation overhead in `TabFillFlowContainer` when it can't fit all the items
  osu.Framework/Graphics/Containers/FlowContainer.cs
Labels: type:performance, size/XS

#6138 Write log header later to ensure game identifiers are present
  osu.Framework/Logging/Logger.cs
Labels: area:logging, size/S

#6137 Add the ability to solo a test in visual testing using `[Solo]` attribute
  osu.Framework/Testing/SoloAttribute.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: type:testing, size/S

#6155 Fix `IBindableList.GetEnumerator()` boxing and allocating
  osu.Framework.Benchmarks/BenchmarkBindableList.cs
  osu.Framework/Bindables/IBindableList.cs
Labels: type:performance, area:bindable, size/S

#6156 Reduce allocations when calling BeginAbsoluteSequence()
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: type:performance, area:transformations, size/S

#6158 Fix build warning
  osu.Framework/Statistics/DotNetRuntimeListener.cs
Labels: type:code-quality, size/S

#6145 Implement `Padding` property in `GridContainer`
  osu.Framework.Tests/Visual/Layout/TestSceneGridContainer.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneAnimationLayout.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneLargeTextureStore.cs
  osu.Framework.Tests/Visual/Sprites/TestSceneVideoLayout.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Testing/Drawables/TestBrowserToolbar.cs
Labels: area:drawable, size/L

#6147 Reduce mouse move overhead when `IRequireHighFrequencyMousePosition` are present
  osu.Framework/Input/InputManager.cs
Labels: type:performance, size/S

#6160 Fix nested absolute sequences
  osu.Framework.Tests/Visual/Drawables/TestSceneTransformSequence.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
Labels: size/M

#6161 Fix `SpriteIcon` flickering for one frame
  osu.Framework.Tests/Visual/Sprites/TestSceneSpriteIcon.cs
  osu.Framework/Graphics/Sprites/SpriteIcon.cs
Labels: area:UI, size/S

#6162 Revert "Fix `IBindableList.GetEnumerator()` boxing and allocating"
  osu.Framework/Bindables/IBindableList.cs
Labels: platform:android, size/XS, type:reliability
