Repository ppy/osu-framework, pull requests merged in 2024-11, with the labels that each got.

#6411 Add attribute to hide arbitrary drawables from draw visualiser
  osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
  osu.Framework/Graphics/Visualisation/DrawVisualiserHiddenAttribute.cs
Labels: area:tooling, size/M

#6410 Fix texture wrapping not updating when atlas is already bound
  osu.Framework.Tests/Graphics/RendererTest.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
Labels: size/S

#6412 Add better support for adding form file parameters to web requests
  osu.Framework/IO/Network/WebRequest.cs
Labels: area:network, size/S

#6413 Fix SDL3 attempting to render IME composition text
  osu.Framework/Platform/SDL3/SDL3Window.cs
Labels: area:input, area:UI, size/XS

#6415 Allow customising `ScrollContainer`'s scrollbar mapping
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: area:UI, size/S

#6420 Make draw visualiser follow proxied drawables to their visual layer
  osu.Framework/Graphics/Visualisation/DrawVisualiser.cs
Labels: area:tooling, size/XS

#6418 Refactor step buttons + improve assertion messages
  osu.Framework.Tests/Visual/Testing/TestSceneStepButton.cs
  osu.Framework.Tests/Visual/Testing/TestSceneTest.cs
  osu.Framework/Testing/Drawables/Steps/AssertButton.cs
  osu.Framework/Testing/Drawables/Steps/LabelStep.cs
  osu.Framework/Testing/Drawables/Steps/RepeatStepButton.cs
  osu.Framework/Testing/Drawables/Steps/SingleStepButton.cs
  osu.Framework/Testing/Drawables/Steps/StepButton.cs
  osu.Framework/Testing/Drawables/Steps/ToggleStepButton.cs
  osu.Framework/Testing/Drawables/Steps/UntilStepButton.cs
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestScene.cs
Labels: type:testing, size/L

#6421 Fix error triggered in label step execution not being logged
  osu.Framework/Testing/TestBrowser.cs
  osu.Framework/Testing/TestScene.cs
  osu.Framework/Testing/TestSceneTestRunner.cs
Labels: type:testing, size/S

#6422 Fix CI test report workflow
  .github/workflows/report-nunit.yml
Labels: area:tooling, size/M

#6407 Disable `OnScreenKeyboardOverlapsGameWindow` on iOS when hardware keyboard is attached
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework.iOS/IOSWindow.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/ISDLWindow.cs
  osu.Framework/Platform/SDL2/SDL2Window.cs
  osu.Framework/Platform/SDL3/SDL3Window.cs
  osu.Framework/Platform/SDLGameHost.cs
Labels: area:UX, size/S

#6419 Use SDL3 text editing events on windows
  osu.Framework/Platform/SDL3/SDL3Window.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
  osu.Framework/Platform/Windows/SDL3WindowsWindow.cs
Labels: area:input, size/L, platform:windows

#6424 Fix `RearrangeableListContainer<>` crashing on replacement operations
  osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
  osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
Labels: area:drawable, size/M, type:reliability

#6426 Revert "Use SDL3 windowing by default"
  osu.Framework/FrameworkEnvironment.cs
Labels: size/XS, area:platform

#6427 Remove `NuGet.ProjectModel` dependency
  osu.Framework/osu.Framework.csproj
Labels: size/XS, dependencies

#6430 Remove SourceLink package reference
  osu.Framework/osu.Framework.csproj
Labels: area:tooling, size/XS

#6425 Make `RearrangeableListContainer<>` only replace differences
  osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
  osu.Framework/Graphics/Containers/RearrangeableListContainer.cs
Labels: area:drawable, size/L

#6432 Factor window scale in `UserInputManager.mouseOutsideAllDisplays`
  osu.Framework/Input/UserInputManager.cs
Labels: area:input, size/XS

#6436 Work around Android CI workflow errors
  .github/workflows/ci.yml
  .github/workflows/deploy-pack.yml
Labels: area:tooling, platform:android, size/S

#6434 Set up-to-date .NET code quality analyzers
  .globalconfig
  CodeAnalysis/BannedSymbols.txt
  CodeAnalysis/osu-framework.ruleset
  Directory.Build.props
  osu-framework.sln
  osu.Framework.SourceGeneration.Tests/GeneratorTestHelper.cs
  osu.Framework.Tests/Audio/AudioThreadTest.cs
  osu.Framework.Tests/Containers/TestSceneContainerState.cs
  osu.Framework.Tests/IO/TestWebRequest.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTabControl.cs
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
  osu.Framework/Audio/Track/Waveform.cs
  osu.Framework/Graphics/Containers/FlowContainer.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLShaderStorageBufferObject.cs
  osu.Framework/Graphics/Rendering/Deferred/DeferredVertexBatch.cs
  osu.Framework/Graphics/UserInterface/Dropdown.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/Visualisation/PropertyDisplay.cs
  osu.Framework/Input/Bindings/KeyBindingContainer.cs
  osu.Framework/Input/Bindings/KeyCombination.cs
  osu.Framework/Input/Handlers/Midi/MidiHandler.cs
  osu.Framework/Platform/Windows/WindowsMouseHandler_SDL2.cs
  osu.Framework/Testing/TestBrowser.cs
Labels: type:code-quality, size/L

#6438 Clean up `IWindow` and remove platform-agnostic code probing `ISDLWindow`
  osu.Framework.Tests/Visual/Platform/TestSceneBorderless.cs
  osu.Framework.Tests/Visual/Platform/TestSceneFullscreen.cs
  osu.Framework.Tests/Visual/Platform/TestSceneWindowed.cs
  osu.Framework.Tests/Visual/Platform/WindowDisplaysPreview.cs
  osu.Framework/Input/UserInputManager.cs
  osu.Framework/Platform/ISDLWindow.cs
  osu.Framework/Platform/IWindow.cs
  osu.Framework/Platform/Windows/WindowsGLRenderer.cs
Labels: type:code-quality, size/L, area:platform
