Repository ppy/osu-framework, pull requests merged in 2024-10, with the labels that each got.

#6381 Change textbox deletion animation easing to closer match gravity
  osu.Framework/Graphics/UserInterface/BasicTextBox.cs
Labels: size/XS

#6384 Rollback iOS workload to last known working version
  .github/workflows/ci.yml
  .github/workflows/deploy-pack.yml
  workloads.json
Labels: area:tooling, platform:iOS, size/S

#6383 Expose slider bar commit method as virtual
  osu.Framework/Graphics/UserInterface/SliderBar.cs
Labels: area:UI, size/XS

#6380 Add `NineSliceSprite`
  osu.Framework.Tests/Resources/Textures/sample-nine-slice-texture.png
  osu.Framework.Tests/Visual/Sprites/TestSceneNineSliceSprite.cs
  osu.Framework/Graphics/MarginPadding.cs
  osu.Framework/Graphics/Sprites/NineSliceSprite.cs
  osu.Framework/Graphics/Textures/Texture.cs
Labels: size/L

#6385 Hide iOS home indicator by default
  osu.Framework.iOS/IOSWindow.cs
Labels: platform:iOS, size/XS

#6386 Enable NRT in `LocalisableStringEqualityComparer`
  osu.Framework.Tests/Localisation/LocalisableStringTest.cs
  osu.Framework/Localisation/LocalisableStringEqualityComparer.cs
Labels: area:localisation, size/S

#6389 Update SDL3-CS
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.iOS/IOSWindow.cs
  osu.Framework/Platform/SDL3/SDL3Clipboard.cs
  osu.Framework/Platform/SDL3/SDL3DesktopWindow.cs
  osu.Framework/Platform/SDL3/SDL3MobileWindow.cs
  osu.Framework/Platform/SDL3/SDL3ReadableKeyCombinationProvider.cs
  osu.Framework/Platform/SDL3/SDL3Window.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
  osu.Framework/Platform/SDL3/SDL3Window_Windowing.cs
  osu.Framework/Platform/Windows/SDL3WindowsWindow.cs
  osu.Framework/osu.Framework.csproj
Labels: size/M

#6394 Update SDL3-CS
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework/osu.Framework.csproj
Labels: size/XS, dependencies

#6396 Use SDL3 windowing by default
  osu.Framework/FrameworkEnvironment.cs
Labels: size/XS, area:platform

#6390 Allow slider bar to take focus and accept keyboard input while not hovered
  osu.Framework.Tests/Visual/UserInterface/TestSceneSliderBar.cs
  osu.Framework/Graphics/UserInterface/BasicSliderBar.cs
  osu.Framework/Graphics/UserInterface/SliderBar.cs
Labels: area:UI, size/M, next-release
