Repository ppy/osu-framework, pull requests merged in 2024-08, with the labels that each got.

#6347 Fix `PassThroughInputManager` not always releasing input
  osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
  osu.Framework/Input/PassThroughInputManager.cs
Labels: area:input, size/M

#6348 Remove HashSet allocations during BindableList methods
  osu.Framework.Benchmarks/BenchmarkBindableList.cs
  osu.Framework/Bindables/BindableList.cs
Labels: type:performance, area:bindable, size/M

#6349 Update SDL3 bindings
  osu.Framework.Android/AndroidGameActivity.cs
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework.iOS/IOSWindow.cs
  osu.Framework/Platform/MacOS/SDL3MacOSWindow.cs
  osu.Framework/Platform/SDL3/SDL3GraphicsSurface.cs
  osu.Framework/Platform/SDL3/SDL3ReadableKeyCombinationProvider.cs
  osu.Framework/Platform/SDL3/SDL3Window.cs
  osu.Framework/Platform/SDL3/SDL3Window_Windowing.cs
  osu.Framework/osu.Framework.csproj
Labels: size/M, dependencies

#6350 Fix texture wrapping not updating on consecutive WhitePixel use
  osu.Framework.Tests/Graphics/RendererTest.cs
  osu.Framework.Tests/Graphics/ShaderStorageBufferObjectStackTest.cs
  osu.Framework.Tests/Visual/Graphics/TestSceneVertexBatching.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLShaderStorageBufferObject.cs
  osu.Framework/Graphics/OpenGL/Buffers/GLUniformBuffer.cs
  osu.Framework/Graphics/Rendering/Deferred/DeferredShaderStorageBufferObject.cs
  osu.Framework/Graphics/Rendering/Deferred/DeferredUniformBuffer.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyFrameBuffer.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyNativeTexture.cs
  osu.Framework/Graphics/Rendering/Dummy/DummyRenderer.cs
  osu.Framework/Graphics/Rendering/Renderer.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridShaderStorageBufferObject.cs
  osu.Framework/Graphics/Veldrid/Buffers/VeldridUniformBuffer.cs
Labels: area:graphics, size/L

#6351 Remove `iPhone`/`iPhoneSimulator` platform configurations
  osu-framework.iOS.slnf
  osu-framework.sln
  osu.Framework.Templates/templates/template-empty/TemplateGame.iOS/TemplateGame.iOS.csproj
  osu.Framework.Templates/templates/template-flappy/FlappyDon.iOS/FlappyDon.iOS.csproj
  osu.Framework.iOS.props
  osu.Framework/osu.Framework.csproj
Labels: area:tooling, platform:iOS, size/L

#6345 Do not unfocus on click if the focused drawable changed during the click
  osu.Framework.Tests/Visual/Drawables/TestSceneFocus.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/MouseButtonEventManager.cs
Labels: area:input, size/M

#6346 Fix double clicking on dropdown header not changing menu state
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/DropdownHeader.cs
  osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs
Labels: area:input, size/M

#6353 Allow clicking on empty search header to close dropdown
  osu.Framework.Tests/Visual/UserInterface/TestSceneDropdown.cs
  osu.Framework/Graphics/UserInterface/DropdownHeader.cs
  osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs
Labels: area:input, size/S

#6354 Fix tempo attributes being ignored
  osu.Framework/Audio/Track/TrackBass.cs
Labels: size/XS

#6356 Revert BindableList GC reduction change
  osu.Framework.Benchmarks/BenchmarkBindableList.cs
  osu.Framework/Bindables/BindableList.cs
Labels: size/M, type:reliability

#6360 Remove unnecessary boxing allocation
  osu.Framework/Graphics/BufferedDrawNode.cs
Labels: type:performance, size/XS

#6362 Bring back `HasFlagsFast`
  CodeAnalysis/BannedSymbols.txt
  osu.Framework.Android/Graphics/Video/AndroidVideoDecoder.cs
  osu.Framework.Benchmarks/BenchmarkEnum.cs
  osu.Framework.Tests/Visual/Containers/TestSceneSafeAreaOverrides.cs
  osu.Framework.Tests/Visual/Drawables/TestSceneIsMaskedAway.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneContextMenu.cs
  osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs
  osu.Framework/Extensions/AnchorExtensions.cs
  osu.Framework/Extensions/EnumExtensions/EnumExtensions.cs
  osu.Framework/Extensions/TaskExtensions.cs
  osu.Framework/Graphics/Containers/AudioContainer.cs
  osu.Framework/Graphics/Containers/CompositeDrawable.cs
  osu.Framework/Graphics/Containers/ContainerExtensions.cs
  osu.Framework/Graphics/Containers/FillFlowContainer.cs
  osu.Framework/Graphics/Containers/GridContainer.cs
  osu.Framework/Graphics/Containers/Markdown/MarkdownContainer.cs
  osu.Framework/Graphics/Containers/SafeAreaContainer.cs
  osu.Framework/Graphics/Containers/TextFlowContainer.cs
  osu.Framework/Graphics/Cursor/PopoverContainer.cs
  osu.Framework/Graphics/Drawable.cs
  osu.Framework/Graphics/Lines/Path.cs
  osu.Framework/Graphics/OpenGL/GLRenderer.cs
  osu.Framework/Graphics/Pooling/PoolableDrawable.cs
  osu.Framework/Graphics/Textures/Texture.cs
  osu.Framework/Graphics/UserInterface/BasicPopover.cs
  osu.Framework/Graphics/UserInterface/DirectorySelector.cs
  osu.Framework/Graphics/UserInterface/DirectorySelectorDirectory.cs
  osu.Framework/Graphics/UserInterface/FileSelector.cs
  osu.Framework/Graphics/UserInterface/Menu.cs
  osu.Framework/Graphics/UserInterface/Popover.cs
  osu.Framework/Graphics/UserInterface/TabControl.cs
  osu.Framework/Graphics/Veldrid/VeldridExtensions.cs
  osu.Framework/Graphics/Video/VideoDecoder.cs
  osu.Framework/Input/Handlers/Mouse/MouseHandler.cs
  osu.Framework/Input/MouseButtonEventManager.cs
  osu.Framework/Input/UserInputManager.cs
  osu.Framework/Platform/SDL2/SDL2Extensions.cs
  osu.Framework/Platform/SDL2/SDL2Window.cs
  osu.Framework/Platform/SDL2/SDL2Window_Input.cs
  osu.Framework/Platform/SDL3/SDL3Extensions.cs
  osu.Framework/Platform/SDL3/SDL3Window.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
  osu.Framework/Platform/Windows/Native/Imm.cs
  osu.Framework/Platform/Windows/WindowsMouseHandler_SDL2.cs
Labels: size/L

#6361 Update veldrid
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#6363 Fix Android safe area
  osu.Framework.Android/AndroidGameActivity.cs
  osu.Framework.Android/AndroidGameSurface.cs
Labels: platform:android, size/S

#6364 Fix tabbable container not checking if its next tab stop is focusable
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Graphics/Containers/TabbableContainer.cs
Labels: area:drawable, area:UX, size/M

#6365 Implement native method for `PresentFileExternally` in MacOS
  osu.Framework.Tests/Visual/Platform/TestScenePresentFileExternally.cs
  osu.Framework/Platform/MacOS/MacOSGameHost.cs
  osu.Framework/Platform/MacOS/Native/Finder.cs
  osu.Framework/Platform/MacOS/Native/NSWorkspace.cs
Labels: platform:macOS, size/M

#6366 Fix renderers can't batch vertices with the same blending parameters in some cases
  osu.Framework/Graphics/Containers/CompositeDrawable_DrawNode.cs
  osu.Framework/Graphics/DrawNode.cs
Labels: type:performance, area:graphics, size/S

#6290 Implement `FastCircle` component
  osu.Framework.Tests/Visual/Drawables/TestSceneFastCircle.cs
  osu.Framework.Tests/Visual/Performance/TestSceneCircleBoxAlternatePerformance.cs
  osu.Framework.Tests/Visual/Performance/TestSceneFastCircleBoxAlternatePerformance.cs
  osu.Framework.Tests/Visual/Performance/TestSceneFastCirclePerformance.cs
  osu.Framework/Graphics/Shapes/FastCircle.cs
  osu.Framework/Resources/Shaders/sh_FastCircle.fs
Labels: size/L
