Repository ppy/osu-framework, pull requests merged in 2025-01, with the labels that each got.

#6477 Expose game host from iOS app delegate class
  osu.Framework.iOS/GameApplicationDelegate.cs
Labels: type:code-quality, platform:iOS, size/XS

#6445 Implement system-provided file selection display on iOS
  osu.Framework.Tests/Visual/UserInterface/TestSceneFileSelector.cs
  osu.Framework.iOS/IIOSWindow.cs
  osu.Framework.iOS/IOSFilePresenter.cs
  osu.Framework.iOS/IOSFileSelector.cs
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework.iOS/IOSWindow.cs
  osu.Framework/Graphics/UserInterface/BasicFileSelector.cs
  osu.Framework/Graphics/UserInterface/DirectorySelector.cs
  osu.Framework/Graphics/UserInterface/FileSelector.cs
  osu.Framework/Platform/GameHost.cs
  osu.Framework/Platform/ISystemFileSelector.cs
Labels: area:UI, area:UX, platform:iOS, size/L

#6481 Show whether drawable is receiving input in draw visualiser
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
Labels: area:tooling, size/M

#6479 Disable dropdown searching on mobile when no hardware keyboard is attached
  osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs
Labels: area:UI, area:UX, platform:mobile, size/S

#6486 Update SDL3-CS to 2025.104.0
  osu.Framework.Android/osu.Framework.Android.csproj
  osu.Framework/osu.Framework.csproj
Labels: size/XS, dependencies, area:platform

#6485 Fix crash when dragging in a text box while a key is held down
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
Labels: size/M

#6467 Use `double` in `ScrollContainer` for scroll tracking
  osu.Framework.Tests/Visual/Containers/TestSceneScrollContainer.cs
  osu.Framework.Tests/Visual/Containers/TestSceneScrollContainerDoublePrecision.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneRearrangeableListContainer.cs
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: size/L

#6408 Allow `TextBox` to specify type of text being input
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBoxEvents.cs
  osu.Framework/Graphics/UserInterface/BasicPasswordTextBox.cs
  osu.Framework/Graphics/UserInterface/DropdownSearchBar.cs
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Input/ButtonEventManager.cs
  osu.Framework/Input/ICanSuppressKeyEventLogging.cs
  osu.Framework/Input/InputManager.cs
  osu.Framework/Input/KeyEventManager.cs
  osu.Framework/Input/SDLWindowTextInput.cs
  osu.Framework/Input/TextInputProperties.cs
  osu.Framework/Input/TextInputSource.cs
  osu.Framework/Input/TextInputType.cs
  osu.Framework/Platform/ISDLWindow.cs
  osu.Framework/Platform/SDL2/SDL2Window_Input.cs
  osu.Framework/Platform/SDL3/SDL3Extensions.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
  osu.Framework/Platform/Windows/SDL2WindowsWindow.cs
  osu.Framework/Platform/Windows/SDL3WindowsWindow.cs
  osu.Framework/Testing/Input/ManualTextInputSource.cs
Labels: area:UI, size/L

#6492 Change `OffsetScrollPosition` to take a `double`
  osu.Framework/Graphics/Containers/ScrollContainer.cs
Labels: size/XS

#6493 Add entry point to `Game` for logging setup purposes
  osu.Framework/Game.cs
  osu.Framework/Platform/GameHost.cs
Labels: size/S, area:storage

#6494 Bump NVika tool to 4.0.0
  .config/dotnet-tools.json
Labels: size/XS

#6495 Fix incorrect release pattern in macOS/iOS texture loading code
  osu.Framework.iOS/Graphics/Textures/IOSTextureLoaderStore.cs
  osu.Framework/Platform/Apple/Native/Class.cs
  osu.Framework/Platform/Apple/Native/NSArray.cs
  osu.Framework/Platform/Apple/Native/NSAutoreleasePool.cs
  osu.Framework/Platform/Apple/Native/NSData.cs
  osu.Framework/Platform/Apple/Native/NSMutableData.cs
  osu.Framework/Platform/Apple/Native/NSNotificationCenter.cs
  osu.Framework/Platform/Apple/Native/NSString.cs
  osu.Framework/Platform/Apple/Native/Selector.cs
  osu.Framework/Platform/MacOS/MacOSClipboard.cs
  osu.Framework/Platform/MacOS/MacOSTextureLoaderStore.cs
  osu.Framework/Platform/MacOS/SDL2MacOSWindow.cs
  osu.Framework/Platform/MacOS/SDL3MacOSWindow.cs
Labels: type:performance, platform:macOS, platform:iOS, size/L

#6497 Remove a char[] allocation in SearchContainer.cs
  osu.Framework/Graphics/Containers/SearchContainer.cs
Labels: size/XS

#6469 Disable "relative mode" by default on iOS
  osu.Framework.iOS/IOSGameHost.cs
Labels: area:input, platform:iOS, size/S

#6478 Disable auto-capitalisation in textboxes
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
  osu.Framework/Input/TextInputProperties.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
Labels: area:UI, size/S

#6499 Add simple `InputProperties` / `TextInputType` test
  osu.Framework.Tests/Visual/UserInterface/TestSceneTextInputProperties.cs
Labels: type:testing, area:UI, size/M

#6500 Change IsRootedAt method from internal to public in DrawableExtensions
  osu.Framework/Graphics/DrawableExtensions.cs
Labels: size/XS

#6502 Fix file presentation on iPadOS not working
  osu.Framework.iOS/IOSFilePresenter.cs
Labels: platform:iOS, size/S

#6504 Fix `SetupLogging` not being called in game test scenario
  osu.Framework.Templates/templates/template-empty/TemplateGame.Game.Tests/Visual/TestSceneTemplateGameGame.cs
  osu.Framework.Templates/templates/template-flappy/FlappyDon.Game.Tests/Visual/TestSceneFlappyDonGame.cs
  osu.Framework/Testing/TestScene.cs
Labels: size/S

#6488 Add a way to distinguish mouse from tablet pen inputs
  osu.Framework.Tests/Visual/Input/TestSceneInputManager.cs
  osu.Framework.Tests/Visual/Input/TestScenePassThroughInputManager.cs
  osu.Framework/Input/Handlers/Pen/PenHandler.cs
  osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs
  osu.Framework/Input/PassThroughInputManager.cs
  osu.Framework/Input/StateChanges/ISourcedFromPen.cs
  osu.Framework/Input/StateChanges/MouseButtonInputFromPen.cs
  osu.Framework/Input/StateChanges/MousePositionAbsoluteInputFromPen.cs
  osu.Framework/Input/StateChanges/MousePositionRelativeInputFromPen.cs
  osu.Framework/Input/StateChanges/TabletPenDeviceType.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
  osu.Framework/Platform/SDLGameHost.cs
  osu.Framework/Testing/Input/ManualInputManager.cs
Labels: area:input, size/L

#6235 Async mouse input on windows
  osu.Framework/Platform/SDL3/SDL3Window.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
  osu.Framework/Platform/Windows/SDL3WindowsWindow.cs
Labels: area:input, size/M, platform:windows

#6505 Roll back windows build image to 2019 on android build job
  .github/workflows/ci.yml
Labels: area:tooling, size/XS

#6513 Add text input type for alphanumeric code
  osu.Framework/Input/TextInputType.cs
  osu.Framework/Platform/SDL3/SDL3Extensions.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
Labels: area:UX, size/S

#6512 Revert changes to `OnScreenKeyboardOverlapsGameWindow` on iOS
  osu.Framework.iOS/IOSGameHost.cs
  osu.Framework/Platform/GameHost.cs
Labels: area:UX, platform:iOS, size/XS

#6511 Update SDL3, bringing in support for Windows Ink pen input, and enable it on desktop platforms once again
  osu.Framework/FrameworkEnvironment.cs
  osu.Framework/Platform/SDL3/SDL3Extensions.cs
  osu.Framework/Platform/SDL3/SDL3Window.cs
  osu.Framework/Platform/SDL3/SDL3Window_Input.cs
  osu.Framework/Platform/Windows/SDL3WindowsWindow.cs
  osu.Framework/osu.Framework.csproj
Labels: size/M, dependencies, area:platform

#6498 Add input type for decimal numbers
  osu.Framework/Graphics/UserInterface/TextBox.cs
  osu.Framework/Input/TextInputType.cs
  osu.Framework/Platform/SDL3/SDL3Extensions.cs
Labels: area:UI, size/M

#6514 Don't force fs and vs shader file extension if shader load argument string already includes file extension
  osu.Framework/Graphics/Shaders/ShaderManager.cs
Labels: size/XS

#6516 Roll back windows runner in another android workflow
  .github/workflows/deploy-pack.yml
Labels: area:tooling, size/XS

#6517 Fix iOS file presentation code not scheduled to main thread
  osu.Framework.iOS/IOSGameHost.cs
Labels: platform:iOS, size/S, type:reliability, next-release
