Repository ppy/osu-framework, pull requests merged in 2025-09, with the labels that each got.

#6633 Update dependencies
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#6636 Truncate drawable class names so that position and size are always visible in draw visualiser
  osu.Framework/Graphics/Visualisation/ToolWindow.cs
  osu.Framework/Graphics/Visualisation/VisualisedDrawable.cs
Labels: size/M

#6639 Update SDL3-CS to 2025.920.0
  osu.Framework/osu.Framework.csproj
Labels: size/XS

#6642 Work around web request failures on macOS when on networks with no IPv6 support and content filters enabled
  osu.Framework/IO/Network/WebRequest.cs
Labels: area:network, platform:macOS, size/M, type:reliability
